### ISSUE TITLE
Frequent auto-fetch errors

### ISSUE THREAD

**Issue by tobiisan** [zielu/GitToolBox#103]
I recently updated to version 182.4.0 of this plugin, and now I frequently get auto-fetch errors. I think it was fine before the update.

Note that I have 15 repos within a single GoLand project. My wild guess is that the new parallel auto-fetch doesn't play nicely with so many repos. Maybe it's caused by too many connections open to our GitLab server and so some will randomly fail, or maybe something else. Not really sure.

Here's what I frequently see in the event log (repo names obfuscated):
```
6:19 AM	Fetch problems:
					repo-11: fetch failed
					repo-09: fetch failed
					repo-14: fetch failed
					repo-08: fetch failed
					repo-13: fetch failed

6:43 AM	Fetch problems:
					repo-08: fetch failed
					repo-15: fetch failed
					repo-06: fetch failed
					repo-01: fetch failed
					repo-11: fetch failed
					repo-05: fetch failed
					repo-09: fetch failed

7:06 AM	Fetch problems:
					repo-07: fetch failed
					repo-03: fetch failed
					repo-10: fetch failed
					repo-12: fetch failed
					repo-04: fetch failed
					repo-13: fetch failed

7:32 AM	Fetch problems:
					repo-12: fetch failed
					repo-07: fetch failed
					repo-08: fetch failed
					repo-05: fetch failed
					repo-11: fetch failed
					repo-15: fetch failed

7:57 AM	Fetch problems:
					repo-08: fetch failed
					repo-03: fetch failed
					repo-09: fetch failed
					repo-05: fetch failed
					repo-15: fetch failed
					repo-14: fetch failed
					repo-12: fetch failed

8:21 AM	Fetch problems:
					repo-10: fetch failed
					repo-15: fetch failed
					repo-08: fetch failed
					repo-07: fetch failed
```

And in the Version Control Console, I'll see errors like this:
```
08:17:34.291: [repo-01] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.291: [repo-02] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.293: [repo-03] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.293: [repo-04] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.294: [repo-05] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.294: [repo-06] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.294: [repo-07] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.294: [repo-08] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.295: [repo-09] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.308: [repo-10] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.308: [repo-11] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.308: [repo-12] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.309: [repo-13] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.309: [repo-14] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
08:17:34.313: [repo-15] git -c core.quotepath=false -c log.showSignature=false fetch origin --progress --prune
java.io.IOException: There was a problem while connecting to our-internal-gitlab.com:22
	at com.trilead.ssh2.Connection.connect(Connection.java:834)
	at com.trilead.ssh2.Connection.connect(Connection.java:703)
	at com.trilead.ssh2.Connection.connect(Connection.java:617)
	at org.jetbrains.git4idea.ssh.SSHMain.start(SSHMain.java:173)
	at org.jetbrains.git4idea.ssh.SSHMain.main(SSHMain.java:137)
Caused by: java.io.IOException: Premature connection close
	at com.trilead.ssh2.transport.ClientServerHello.readLineRN(ClientServerHello.java:33)
	at com.trilead.ssh2.transport.ClientServerHello.<init>(ClientServerHello.java:68)
	at com.trilead.ssh2.transport.TransportManager.initialize(TransportManager.java:487)
	at com.trilead.ssh2.Connection.connect(Connection.java:774)
	... 4 more
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
java.io.IOException: There was a problem while connecting to our-internal-gitlab.com:22
	at com.trilead.ssh2.Connection.connect(Connection.java:834)
	at com.trilead.ssh2.Connection.connect(Connection.java:703)
	at com.trilead.ssh2.Connection.connect(Connection.java:617)
	at org.jetbrains.git4idea.ssh.SSHMain.start(SSHMain.java:173)
	at org.jetbrains.git4idea.ssh.SSHMain.main(SSHMain.java:137)
Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
	at com.trilead.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:95)
	at com.trilead.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:237)
	at com.trilead.ssh2.Connection.connect(Connection.java:786)
	... 4 more
Caused by: java.io.IOException: Cannot read full block, EOF reached.
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.getBlock(CipherInputStream.java:81)
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.read(CipherInputStream.java:108)
	at com.trilead.ssh2.transport.TransportConnection.receiveMessage(TransportConnection.java:232)
	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:706)
	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:502)
	at java.lang.Thread.run(Thread.java:745)
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
java.io.IOException: There was a problem while connecting to our-internal-gitlab.com:22
	at com.trilead.ssh2.Connection.connect(Connection.java:834)
	at com.trilead.ssh2.Connection.connect(Connection.java:703)
	at com.trilead.ssh2.Connection.connect(Connection.java:617)
	at org.jetbrains.git4idea.ssh.SSHMain.start(SSHMain.java:173)
	at org.jetbrains.git4idea.ssh.SSHMain.main(SSHMain.java:137)
Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
	at com.trilead.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:95)
	at com.trilead.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:237)
	at com.trilead.ssh2.Connection.connect(Connection.java:786)
	... 4 more
Caused by: java.io.IOException: Cannot read full block, EOF reached.
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.getBlock(CipherInputStream.java:81)
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.read(CipherInputStream.java:108)
	at com.trilead.ssh2.transport.TransportConnection.receiveMessage(TransportConnection.java:232)
	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:706)
	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:502)
	at java.lang.Thread.run(Thread.java:745)
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
java.io.IOException: There was a problem while connecting to our-internal-gitlab.com:22
	at com.trilead.ssh2.Connection.connect(Connection.java:834)
	at com.trilead.ssh2.Connection.connect(Connection.java:703)
	at com.trilead.ssh2.Connection.connect(Connection.java:617)
	at org.jetbrains.git4idea.ssh.SSHMain.start(SSHMain.java:173)
	at org.jetbrains.git4idea.ssh.SSHMain.main(SSHMain.java:137)
Caused by: java.io.IOException: Key exchange was not finished, connection is closed.
	at com.trilead.ssh2.transport.KexManager.getOrWaitForConnectionInfo(KexManager.java:95)
	at com.trilead.ssh2.transport.TransportManager.getConnectionInfo(TransportManager.java:237)
	at com.trilead.ssh2.Connection.connect(Connection.java:786)
	... 4 more
Caused by: java.io.IOException: Cannot read full block, EOF reached.
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.getBlock(CipherInputStream.java:81)
	at com.trilead.ssh2.crypto.cipher.CipherInputStream.read(CipherInputStream.java:108)
	at com.trilead.ssh2.transport.TransportConnection.receiveMessage(TransportConnection.java:232)
	at com.trilead.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:706)
	at com.trilead.ssh2.transport.TransportManager$1.run(TransportManager.java:502)
	at java.lang.Thread.run(Thread.java:745)
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

**Comment by zielu** [comment]
Fixed in 182.4.1
