### ISSUE TITLE
Plugin causes IDEA 16 (EAP) to hang

### ISSUE THREAD

**Issue by lots0logs** [zielu/GitToolBox#11]
```
2015-12-22 01:15:24,202 [  22219]  ERROR - plication.impl.ApplicationImpl - git4idea.GitLocalBranch.getHash()Lcom/intellij/vcs/log/Hash; 
java.lang.NoSuchMethodError: git4idea.GitLocalBranch.getHash()Lcom/intellij/vcs/log/Hash;
	at zielu.gittoolbox.cache.RepoStatus.create(RepoStatus.java:32)
	at zielu.gittoolbox.cache.CachedStatus.update(CachedStatus.java:35)
	at zielu.gittoolbox.cache.PerRepoInfoCache.get(PerRepoInfoCache.java:56)
	at zielu.gittoolbox.cache.PerRepoInfoCache.getInfo(PerRepoInfoCache.java:69)
	at zielu.gittoolbox.cache.PerRepoInfoCache.onRepoChanged(PerRepoInfoCache.java:98)
	at zielu.gittoolbox.cache.PerRepoInfoCache.access$000(PerRepoInfoCache.java:21)
	at zielu.gittoolbox.cache.PerRepoInfoCache$1.run(PerRepoInfoCache.java:90)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$2$1.run(PooledThreadExecutor.java:71)
```

**Comment by zielu** [comment]
I was just about to try new EAP :)

**Comment by lots0logs** [comment]
Be sure to keep the previous EAP version because the latest is the buggiest one I've used in a long time! I had to revert back to the previous one to get any work done! :grimacing:

**Comment by zielu** [comment]
I just released new version for 16 EAP. Have fun !
