### ISSUE TITLE
Switch to custom blame loading implementation

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#139]
Options to consider
1. git blame with incremental + intellij detail commit loader (VcsLogData)
2. git blame with incremental + custom git commit loader
3. git blame with incremental + jgit commit loader
4. jgit blame + jgit commit loader

Incremental could start with current line +- 5 lines first and other parts of file in other -L chunks

**Comment by zielu** [comment]
Baseline for using `GitVcs.getAnnotationProvider().annotate(file);` ~ 560ms
Option 1. ~160ms

**Comment by zielu** [comment]
AIOOB when caret is on first line, blame is shown for current line -1

`java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 321
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at zielu.gittoolbox.blame.calculator.BlameRevisionDataProvider.getLineCommit(BlameRevisionDataProvider.java:33)
	at zielu.gittoolbox.blame.calculator.BlameRevisionDataProvider.getRevisionNumber(BlameRevisionDataProvider.java:61)
	at zielu.gittoolbox.blame.BlameAnnotationImpl.getLineRevisionNumber(BlameAnnotationImpl.java:51)
	at zielu.gittoolbox.blame.BlameAnnotationImpl.getBlame(BlameAnnotationImpl.java:32)
	at zielu.gittoolbox.blame.BlameServiceImpl.getLineBlameInternal(BlameServiceImpl.java:107)
	at zielu.gittoolbox.blame.BlameServiceImpl.getLineBlameInternal(BlameServiceImpl.java:97)
	at zielu.gittoolbox.blame.BlameServiceImpl.lambda$getDocumentLineBlame$1(BlameServiceImpl.java:84)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:133)
	at zielu.gittoolbox.blame.BlameServiceImpl.getDocumentLineBlame(BlameServiceImpl.java:84)
	at zielu.gittoolbox.ui.blame.BlameEditorServiceImpl.getLineBlame(BlameEditorServiceImpl.java:147)
	at zielu.gittoolbox.ui.blame.BlameEditorServiceImpl.getInfosWithCaching(BlameEditorServiceImpl.java:110)
	at zielu.gittoolbox.ui.blame.BlameEditorServiceImpl.lambda$getLineAnnotation$1(BlameEditorServiceImpl.java:84)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:133)
	at zielu.gittoolbox.ui.blame.BlameEditorServiceImpl.getLineAnnotation(BlameEditorServiceImpl.java:83)
	at zielu.gittoolbox.ui.blame.BlameEditorServiceImpl.lambda$getLineExtensions$0(BlameEditorServiceImpl.java:73)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:133)
	at zielu.gittoolbox.ui.blame.BlameEditorServiceImpl.getLineExtensions(BlameEditorServiceImpl.java:73)
	at zielu.gittoolbox.ui.blame.BlameEditorLinePainter.getLineExtensions(BlameEditorLinePainter.java:19)
	at com.intellij.openapi.editor.impl.EditorImpl.processLineExtensions(EditorImpl.java:764)`

**Comment by zielu** [comment]
Released on EAP channel in 191.0.12

**Comment by zielu** [comment]
Released in 191.1.0
