### ISSUE TITLE
Error when I deleted all the lines in a file

### ISSUE THREAD

**Issue by terrdavis** [zielu/GitToolBox#145]
I haven't been able to reproduce the error. I suspect I deleted the lines as the plugin was fetching data.
```
java.lang.IndexOutOfBoundsException: Wrong line: 0. Available lines count: 0
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:210)
	at com.intellij.openapi.editor.impl.LineSet.isModified(LineSet.java:215)
	at com.intellij.openapi.editor.impl.DocumentImpl.isLineModified(DocumentImpl.java:283)
	at zielu.gittoolbox.ui.blame.BlameEditorServiceImpl$LineState.<init>(BlameEditorServiceImpl.java:173)
	at zielu.gittoolbox.ui.blame.BlameEditorServiceImpl$LineState.<init>(BlameEditorServiceImpl.java:163)
	at zielu.gittoolbox.ui.blame.BlameEditorServiceImpl.getInfosWithCaching(BlameEditorServiceImpl.java:105)
	at zielu.gittoolbox.ui.blame.BlameEditorServiceImpl.lambda$getLineAnnotation$1(BlameEditorServiceImpl.java:84)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:133)
	at zielu.gittoolbox.ui.blame.BlameEditorServiceImpl.getLineAnnotation(BlameEditorServiceImpl.java:83)
	at zielu.gittoolbox.ui.blame.BlameEditorServiceImpl.lambda$getLineExtensions$0(BlameEditorServiceImpl.java:73)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:133)
	at zielu.gittoolbox.ui.blame.BlameEditorServiceImpl.getLineExtensions(BlameEditorServiceImpl.java:73)
	at zielu.gittoolbox.ui.blame.BlameEditorLinePainter.getLineExtensions(BlameEditorLinePainter.java:20)
	at com.intellij.openapi.editor.impl.EditorImpl.processLineExtensions(EditorImpl.java:764)
	at com.intellij.openapi.editor.impl.view.EditorSizeManager.validateMaxLineWithExtension(EditorSizeManager.java:299)
	at com.intellij.openapi.editor.impl.view.EditorSizeManager.getTextPreferredWidth(EditorSizeManager.java:278)
	at com.intellij.openapi.editor.impl.view.EditorSizeManager.getPreferredSize(EditorSizeManager.java:181)
	at com.intellij.openapi.editor.impl.view.EditorView.getPreferredSize(EditorView.java:276)
	at com.intellij.openapi.editor.impl.EditorImpl.getPreferredSize(EditorImpl.java:2129)
	at com.intellij.openapi.editor.impl.EditorImpl.validateSize(EditorImpl.java:1771)
	at com.intellij.openapi.editor.impl.EditorImpl.changedUpdate(EditorImpl.java:1662)
	at com.intellij.openapi.editor.impl.EditorImpl.access$11900(EditorImpl.java:123)
	at com.intellij.openapi.editor.impl.EditorImpl$EditorDocumentAdapter.documentChanged(EditorImpl.java:4659)
	at com.intellij.openapi.editor.impl.DocumentImpl.changedUpdate(DocumentImpl.java:891)
	at com.intellij.openapi.editor.impl.DocumentImpl.updateText(DocumentImpl.java:796)
	at com.intellij.openapi.editor.impl.DocumentImpl.deleteString(DocumentImpl.java:576)
	at com.intellij.openapi.command.impl.EditorChangeAction.exchangeStrings(EditorChangeAction.java:101)
	at com.intellij.openapi.command.impl.EditorChangeAction.performUndo(EditorChangeAction.java:78)
	at com.intellij.openapi.command.impl.EditorChangeAction.undo(EditorChangeAction.java:65)
	at com.intellij.openapi.command.impl.UndoableGroup.performActions(UndoableGroup.java:179)
	at com.intellij.openapi.command.impl.UndoableGroup.lambda$doUndoOrRedo$0(UndoableGroup.java:151)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at com.intellij.openapi.command.impl.UndoableGroup.doUndoOrRedo(UndoableGroup.java:128)
	at com.intellij.openapi.command.impl.UndoableGroup.undoOrRedo(UndoableGroup.java:117)
	at com.intellij.openapi.command.impl.UndoableGroup.undo(UndoableGroup.java:96)
	at com.intellij.openapi.command.impl.Undo.performAction(Undo.java:40)
	at com.intellij.openapi.command.impl.UndoRedo.execute(UndoRedo.java:132)
	at com.intellij.openapi.command.impl.CommandMerger.undoOrRedo(CommandMerger.java:220)
	at com.intellij.openapi.command.impl.UndoManagerImpl.lambda$undoOrRedo$0(UndoManagerImpl.java:360)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.UndoManagerImpl.undoOrRedo(UndoManagerImpl.java:372)
	at com.intellij.openapi.command.impl.UndoManagerImpl.undo(UndoManagerImpl.java:343)
	at com.intellij.ide.actions.UndoAction.perform(UndoAction.java:30)
	at com.intellij.ide.actions.UndoRedoAction.actionPerformed(UndoRedoAction.java:44)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:622)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:671)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:518)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:473)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:223)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:653)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by zielu** [comment]
Done in 191.2.1
