### ISSUE TITLE
git tool box 191.2.1 error

### ISSUE THREAD

**Issue by NeverGiveUpLZ** [zielu/GitToolBox#149]
Error while calling if active

java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at com.codahale.metrics.jmx.JmxReporter$JmxListener.registerMBean(JmxReporter.java:515)
	at com.codahale.metrics.jmx.JmxReporter$JmxListener.onTimerAdded(JmxReporter.java:644)
	at com.codahale.metrics.MetricRegistry.notifyListenerOfAddedMetric(MetricRegistry.java:476)
	at com.codahale.metrics.MetricRegistry.onMetricAdded(MetricRegistry.java:462)
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:95)
	at com.codahale.metrics.MetricRegistry.getOrAdd(MetricRegistry.java:437)
	at com.codahale.metrics.MetricRegistry.timer(MetricRegistry.java:220)
	at zielu.gittoolbox.metrics.MetricManager.timer(MetricManager.java:23)
	at zielu.gittoolbox.metrics.ProjectMetricsImpl.timer(ProjectMetricsImpl.java:30)
	at zielu.gittoolbox.fetch.AutoFetchTask.executeIdeaFetch(AutoFetchTask.java:165)
	at zielu.gittoolbox.fetch.AutoFetchTask.lambda$tryExecuteFetch$1(AutoFetchTask.java:155)
	at zielu.gittoolbox.util.DisposeSafeCallable.call(DisposeSafeCallable.java:28)
	at zielu.gittoolbox.fetch.AutoFetchExecutor.callIfActive(AutoFetchExecutor.java:146)
	at zielu.gittoolbox.fetch.AutoFetchTask.tryExecuteFetch(AutoFetchTask.java:153)
	at zielu.gittoolbox.fetch.AutoFetchTask.doFetch(AutoFetchTask.java:140)
	at zielu.gittoolbox.fetch.AutoFetchTask.tryToFetch(AutoFetchTask.java:127)
	at zielu.gittoolbox.fetch.AutoFetchTask.lambda$runAutoFetch$4(AutoFetchTask.java:222)
	at zielu.gittoolbox.fetch.AutoFetchExecutor.runIfActive(AutoFetchExecutor.java:139)
	at zielu.gittoolbox.fetch.AutoFetchTask.runAutoFetch(AutoFetchTask.java:219)
	at zielu.gittoolbox.fetch.AutoFetchTask.access$000(AutoFetchTask.java:35)
	at zielu.gittoolbox.fetch.AutoFetchTask$1.run(AutoFetchTask.java:205)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:731)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:403)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zielu** [comment]
Which OS and JVM are you using ? This exception indicates some peculiar setup.

**Comment by zielu** [comment]
Done in 191.2.2
