### ISSUE TITLE
PluginException: getComponentAdapterOfType is used to get zielu.gittoolbox.ui.StatusMessagesServiceLocalGateway

### ISSUE THREAD

**Issue by centreboard** [zielu/GitToolBox#179]
Exception reported using Rider 2019.3 EAP2 with GitToolBox 193.0.3
```
com.intellij.diagnostic.PluginException: getComponentAdapterOfType is used to get zielu.gittoolbox.ui.StatusMessagesServiceLocalGateway (requestorClass=zielu.gittoolbox.ui.StatusMessagesService, requestorConstructor=public zielu.gittoolbox.ui.StatusMessagesService(zielu.gittoolbox.ui.StatusMessagesServiceLocalGateway)).

Probably constructor should be marked as NonInjectable. [Plugin: zielu.gittoolbox]
	at com.intellij.serviceContainer.ConstructorParameterResolver.findTargetAdapter(ConstructorParameterResolver.kt:111)
	at com.intellij.serviceContainer.ConstructorParameterResolver.isResolvable(ConstructorParameterResolver.kt:39)
	at com.intellij.serviceContainer.ConstructorInjectionKt.getGreediestSatisfiableConstructor(constructorInjection.kt:106)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:36)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:506)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:52)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:39)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:289)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:18)
	at zielu.gittoolbox.ui.StatusMessagesService.getInstance(StatusMessagesService.java:39)
	at zielu.gittoolbox.ui.StatusText.format(StatusText.java:19)
	at zielu.gittoolbox.ui.statusbar.GitStatusWidget.updateData(GitStatusWidget.java:188)
	at zielu.gittoolbox.ui.statusbar.GitStatusWidget.update(GitStatusWidget.java:210)
	at zielu.gittoolbox.ui.statusbar.GitStatusWidget.lambda$onCacheChange$0(GitStatusWidget.java:55)
	at zielu.gittoolbox.util.DisposeSafeRunnable.run(DisposeSafeRunnable.java:24)
	at zielu.gittoolbox.util.DisposeSafeRunnable.run(DisposeSafeRunnable.java:24)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

```
JetBrains Rider 2019.3 EAP 2
Build #RD-193.4932.13, built on November 2, 2019
Rider EAP User
Expiration date: December 2, 2019
Runtime version: 11.0.4+10-b520.2 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1933M
Cores: 8
Registry: ide.tree.horizontal.default.autoscrolling=false, performance.watcher.sampling.interval.ms=200, ide.borderless.title.product=false, performance.watcher.unresponsive.interval.ms=1000, ide.tooltip.initialDelay.highlighter=0, search.everywhere.settings=true, parameter.info.max.visible.rows=10, ide.win.file.chooser.native=true, debugger.valueTooltipAutoShowOnSelection=true, ide.borderless.title.project.path=false, search.everywhere.pattern.checking=false, ide.tooltip.initialDelay=0, ide.borderless.title.classpath=false, ide.require.transaction.for.model.changes=false, tabs.alphabetical=true
Non-Bundled Plugins: CMD Support, TFS, com.aemtools, com.fwdekker.randomness, com.intellij.ideolog, com.intellij.plugin.adernov.powershell, com.intellij.resharper.HeapAllocationsViewer, com.microsoft.vso.idea, com.ppolivka.plugin.gitcleaner, io.protostuff.protostuff-jetbrains-plugin, krasa.CpuUsageIndicator, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, org.intellij.RegexpTester, zielu.gittoolbox
```

**Comment by zielu** [comment]
@centreboard already fixed in 193.0.4
