### ISSUE TITLE
2020.1 EAP error

### ISSUE THREAD

**Issue by ForsakenHarmony** [zielu/GitToolBox#208]
Something seems to be erroring occasionally, I haven't really figure out a pattern as to when it happens, but I guess it's related to some internal changes in the git integration

<details>
<summary>Stacktrace</summary>

```
java.lang.Throwable: Assertion failed
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:182)
	at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:191)
	at org.jetbrains.ide.BuiltInServerManagerImpl.waitForStart(BuiltInServerManagerImpl.kt:109)
	at org.jetbrains.git4idea.ssh.GitXmlRpcHandlerService.getXmlRcpPort(GitXmlRpcHandlerService.java:69)
	at git4idea.commands.GitHandlerAuthenticationManager.prepareHttpAuth(GitHandlerAuthenticationManager.java:106)
	at git4idea.commands.GitHandlerAuthenticationManager.lambda$prepare$0(GitHandlerAuthenticationManager.java:67)
	at git4idea.GitUtil.tryRunOrClose(GitUtil.java:1015)
	at git4idea.commands.GitHandlerAuthenticationManager.prepare(GitHandlerAuthenticationManager.java:66)
	at git4idea.commands.GitImplBase.run(GitImplBase.java:153)
	at git4idea.commands.GitImplBase.runCommand(GitImplBase.java:60)
	at git4idea.history.GitHistoryUtils.getCurrentRevision(GitHistoryUtils.java:194)
	at git4idea.diff.GitDiffProvider.getCurrentRevision(GitDiffProvider.java:72)
	at zielu.gittoolbox.blame.calculator.BlameCalculatorLocalGatewayImpl.getCurrentRevisionNumber(BlameCalculatorLocalGatewayImpl.kt:16)
	at zielu.gittoolbox.blame.calculator.BlameCalculator.annotate(BlameCalculator.java:32)
	at zielu.gittoolbox.blame.BlameLoaderImpl.incrementalAnnotation(BlameLoaderImpl.java:29)
	at zielu.gittoolbox.blame.BlameLoaderImpl.annotate(BlameLoaderImpl.java:23)
	at zielu.gittoolbox.blame.BlameCacheImpl$AnnotationLoader.load(BlameCacheImpl.java:219)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:133)
	at zielu.gittoolbox.blame.BlameCacheImpl$AnnotationLoader.run(BlameCacheImpl.java:205)
	at zielu.gittoolbox.blame.BlameCacheExecutor$1.run(BlameCacheExecutor.java:34)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:931)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:433)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:626)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:571)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:245)
	at com.intellij.openapi.progress.impl.ProgressRunner.submit(ProgressRunner.java:253)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcessWithProgressAsync(CoreProgressManager.java:441)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressAsynchronously(ProgressManagerImpl.java:110)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runAsynchronously(CoreProgressManager.java:350)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:337)
	at com.intellij.openapi.progress.Task.queue(Task.java:109)
	at zielu.gittoolbox.blame.BlameCacheExecutor.executeWithProgress(BlameCacheExecutor.java:37)
	at zielu.gittoolbox.blame.BlameCacheExecutor.execute(BlameCacheExecutor.java:26)
	at zielu.gittoolbox.blame.BlameCacheLocalGateway.execute(BlameCacheLocalGateway.kt:44)
	at zielu.gittoolbox.blame.BlameCacheImpl.tryTaskSubmission(BlameCacheImpl.java:98)
	at zielu.gittoolbox.blame.BlameCacheImpl.triggerReload(BlameCacheImpl.java:89)
	at zielu.gittoolbox.blame.BlameCacheImpl.getAnnotationInternal(BlameCacheImpl.java:62)
	at zielu.gittoolbox.blame.BlameCacheImpl.lambda$getAnnotation$0(BlameCacheImpl.java:53)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:133)
	at zielu.gittoolbox.blame.BlameCacheImpl.getAnnotation(BlameCacheImpl.java:53)
	at zielu.gittoolbox.blame.BlameServiceLocalGateway.getAnnotation(BlameServiceLocalGateway.kt:29)
	at zielu.gittoolbox.blame.BlameServiceImpl.getLineBlameInternal(BlameServiceImpl.java:55)
	at zielu.gittoolbox.blame.BlameServiceImpl.getLineBlameInternal(BlameServiceImpl.java:47)
	at zielu.gittoolbox.blame.BlameServiceImpl.lambda$getDocumentLineIndexBlame$0(BlameServiceImpl.java:37)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:133)
	at zielu.gittoolbox.blame.BlameServiceImpl.getDocumentLineIndexBlame(BlameServiceImpl.java:37)
	at zielu.gittoolbox.ui.blame.BlameUiServiceLocalGateway.getLineBlame(BlameUiServiceLocalGateway.kt:78)
	at zielu.gittoolbox.ui.blame.BlameUiServiceImpl.getBlameStatusTooltip(BlameUiServiceImpl.java:98)
	at zielu.gittoolbox.ui.statusbar.BlameStatusWidget.getTooltipText(BlameStatusWidget.java:185)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.lambda$updateWidget$9(IdeStatusBarImpl.java:552)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2311)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.updateWidget(IdeStatusBarImpl.java:545)
	at com.intellij.openapi.wm.impl.status.IdeStatusBarImpl.updateWidgets(IdeStatusBarImpl.java:538)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.updateStatusBar(TextEditorComponent.java:214)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorComponent.selectNotify(TextEditorComponent.java:118)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorImpl.selectNotify(TextEditorImpl.java:173)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer$1.selectionChanged(EditorTabbedContainer.java:99)
	at com.intellij.ui.tabs.impl.JBTabsImpl.fireSelectionChanged(JBTabsImpl.java:1197)
	at com.intellij.ui.tabs.impl.JBTabsImpl.executeSelectionChange(JBTabsImpl.java:1154)
	at com.intellij.ui.tabs.impl.JBTabsImpl.access$2600(JBTabsImpl.java:61)
	at com.intellij.ui.tabs.impl.JBTabsImpl$9.run(JBTabsImpl.java:1107)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer.lambda$null$1(EditorTabbedContainer.java:111)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:212)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer.lambda$new$2(EditorTabbedContainer.java:109)
	at com.intellij.ui.tabs.impl.JBTabsImpl._setSelected(JBTabsImpl.java:1103)
	at com.intellij.ui.tabs.impl.JBTabsImpl.removeTab(JBTabsImpl.java:2059)
	at com.intellij.ui.tabs.impl.JBTabsImpl.removeTab(JBTabsImpl.java:2023)
	at com.intellij.openapi.fileEditor.impl.EditorTabbedContainer.removeTabAt(EditorTabbedContainer.java:166)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.lambda$closeFile$2(EditorWindow.java:180)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1633)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile(EditorWindow.java:162)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.closeFile(EditorsSplitters.java:535)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$closeFileImpl$3(FileEditorManagerImpl.java:593)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1633)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runChange(FileEditorManagerImpl.java:1622)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFileImpl(FileEditorManagerImpl.java:593)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$closeFile$2(FileEditorManagerImpl.java:587)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.java:587)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$MyVirtualFileListener.beforeFileDeletion(FileEditorManagerImpl.java:1680)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$MyVirtualFileListener.before(FileEditorManagerImpl.java:1656)
	at jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:549)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:143)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:472)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:432)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:420)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:402)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:243)
	at com.sun.proxy.$Proxy72.beforePsiChanged(Unknown Source)
	at com.intellij.psi.impl.PsiManagerImpl.beforeChange(PsiManagerImpl.java:444)
	at com.intellij.psi.impl.PsiManagerImpl.beforeChildRemoval(PsiManagerImpl.java:207)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.lambda$beforeFileDeletion$1(PsiVFSListener.java:179)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:958)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.beforeFileDeletion(PsiVFSListener.java:172)
	at com.intellij.psi.impl.file.impl.PsiVFSListener.before(PsiVFSListener.java:687)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$1.before(PsiVFSListener.java:109)
	at jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:549)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:143)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:472)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:432)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:420)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:404)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:243)
	at com.sun.proxy.$Proxy132.before(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvents(PersistentFSImpl.java:972)
	at com.intellij.openapi.vfs.newvfs.AsyncEventSupport.processEvents(AsyncEventSupport.java:124)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEventsInWriteAction(RefreshSessionImpl.java:190)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.lambda$fireEvents$1(RefreshSessionImpl.java:177)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:102)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:177)
	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.lambda$runAsyncListeners$6(RefreshQueueImpl.java:122)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$safeTransferToEdt$6(NonBlockingReadActionImpl.java:532)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:198)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:809)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:844)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:442)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:740)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:441)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:809)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</details>

**Comment by zielu** [comment]
Please try 201.0.1

**Comment by ForsakenHarmony** [comment]
Seems fine, haven't seen any more errors

**Comment by zielu** [comment]
I still get it sometimes, even without my plugin being on the trace. For now I assume it's something  inside git integration.

**Comment by zielu** [comment]
Cannot reproduce anymore
