### ISSUE TITLE
NoClassDefFoundErr: com/codehale/metrics/MetricRegistry

### ISSUE THREAD

**Issue by dickreuter** [zielu/GitToolBox#219]
I'm trying to use Gittoobox plugin for pycharm / intellij but I get the following error:

NoClassDefFoundErr: com/codehale/metrics/MetricRegistry

Note that I have to install the plugin from disk because restrictions to internet access.

**Comment by zielu** [comment]
@dickreuter which version are you trying to install ?

**Comment by zielu** [comment]
Cannot reproduce with 193.7.2

**Comment by dickreuter** [comment]
I have tried multiple different versions: I just tried with the latest Gittoolbox193.7.2 and Pycharm 2019.3.2 Professional. I'm running everything on linux.

**Comment by zielu** [comment]
Cannot reproduce with 193.7.2 and Pycharm Prof 2019.3.3 on macOS. Without that full stack trace from IDE logs I cannot do much more.

**Comment by dickreuter** [comment]
I was able to reproduce it on a separate installation on windows. I also downloaded multiple versions of gittoolbox, they all give me the same error. 

java.lang.NoClassDefFoundError: com/codahale/metrics/MetricRegistry
	at zielu.gittoolbox.metrics.MetricsManager.<init>(MetricsManager.kt:10)
	at zielu.gittoolbox.metrics.ProjectMetricsImpl.<init>(ProjectMetricsImpl.kt:15)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:44)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:505)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:52)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:15)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$$inlined$use$lambda$1.run(ServiceComponentAdapter.kt:44)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:191)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:288)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:22)
	at zielu.gittoolbox.util.AppUtil.getServiceInstance(AppUtil.kt:21)
	at zielu.gittoolbox.metrics.ProjectMetrics$Companion.getInstance(ProjectMetrics.kt:12)
	at zielu.gittoolbox.metrics.ProjectMetrics.getInstance(ProjectMetrics.kt)
	at zielu.gittoolbox.ui.projectview.ProjectViewDecorator.decorateLatency(ProjectViewDecorator.java:36)
	at zielu.gittoolbox.ui.projectview.ProjectViewDecorator.decorate(ProjectViewDecorator.java:25)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.lambda$decorate$0(CompoundProjectViewNodeDecorator.java:49)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.forEach(CompoundProjectViewNodeDecorator.java:60)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.decorate(CompoundProjectViewNodeDecorator.java:49)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$doUpdate$1(AbstractPsiBasedNode.java:166)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:791)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.doUpdate(AbstractPsiBasedNode.java:139)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$update$0(AbstractPsiBasedNode.java:135)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:167)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:125)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:114)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:109)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:135)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:76)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:28)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:451)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:433)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:425)
	at com.intellij.ui.tree.StructureTreeModel$Node.<init>(StructureTreeModel.java:419)
	at com.intellij.ui.tree.StructureTreeModel.getValidChildren(StructureTreeModel.java:389)
	at com.intellij.ui.tree.StructureTreeModel.validateChildren(StructureTreeModel.java:300)
	at com.intellij.ui.tree.StructureTreeModel.getNode(StructureTreeModel.java:294)
	at com.intellij.ui.tree.StructureTreeModel.getChildren(StructureTreeModel.java:314)
	at com.intellij.ui.tree.AsyncTreeModel$CmdGetChildren.getNode(AsyncTreeModel.java:586)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:481)
	at com.intellij.ui.tree.AsyncTreeModel$ObsolescentCommand.get(AsyncTreeModel.java:447)
	at com.intellij.util.concurrency.Command$Processor.lambda$process$1(Command.java:48)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:73)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:127)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:116)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:73)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:191)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:158)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:473)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:222)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:201)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:190)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.codahale.metrics.MetricRegistry PluginClassLoader[zielu.gittoolbox, 193.7.0] com.intellij.ide.plugins.cl.PluginClassLoader@16eb8240
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 73 more

**Comment by zielu** [comment]
Ok, what about that md5 ?

**Comment by dickreuter** [comment]
9fd2b8f758a01efbf84f077b26fa3709 of the zipped GitToolBox-193.7.2 (3).zip

**Comment by dickreuter** [comment]
Selecting the whole zip file resolves the issue. tx

**Comment by zielu** [comment]
Just in case I'll put section about manual installation in the manual
