### ISSUE TITLE
Intellij IDEA 2020.1.1: Exception in plugin RestfulToolkit(2.0.9)

### ISSUE THREAD

**Issue by mailzf** [zielu/GitToolBox#242]
java.lang.NoSuchFieldError: ModulesNode
	at com.zhaow.restful.common.ToolkitIcons.<clinit>(ToolkitIcons.java:39)
	at com.zhaow.restful.navigator.RestServicesNavigator.initToolWindow(RestServicesNavigator.java:118)
	at com.zhaow.restful.navigator.RestServicesNavigator.lambda$initComponent$0(RestServicesNavigator.java:105)
	at com.intellij.util.DisposeAwareRunnable.run(DisposeAwareRunnable.java:86)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:458)
	at com.intellij.ide.startup.impl.StartupManagerImpl$2.lambda$run$0(StartupManagerImpl.java:349)
	at com.intellij.openapi.project.DumbServiceImpl.unsafeRunWhenSmart(DumbServiceImpl.java:283)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runDumbUnawareActivity$10(StartupManagerImpl.java:515)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:284)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runDumbUnawareActivity(StartupManagerImpl.java:514)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$200(StartupManagerImpl.java:48)
	at com.intellij.ide.startup.impl.StartupManagerImpl$2.run(StartupManagerImpl.java:349)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:434)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:426)
	at com.intellij.openapi.project.DumbServiceImpl$TrackedEdtActivity.run(DumbServiceImpl.java:905)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by zielu** [comment]
Hi, how is this related to my plugin ? I don't swe gittoolbox on that stacktrace.

**Comment by mailzf** [comment]
> Hi, how is this related to my plugin ? I don't see gittoolbox on that stacktrace.
> 
> You probably wanted to create issue here: https://github.com/mrmanzhaow/RestfulToolkit

对不起，看错了...
