### ISSUE TITLE
editor inline blame shows [THSP] and is same color as last character in line

### ISSUE THREAD

**Issue by stribor** [zielu/GitToolBox#252]
Since last CLion EAP version (#CL-202.6250.12)editor inline blame is shown as

[THSP] the rest of normal inline blame

The whole inline blame content is same color as last character in line comment is being shown for.

last char on line is green curly brace:
![lastchar green](https://user-images.githubusercontent.com/1141923/87139823-d312c500-c2a0-11ea-8104-c02e514cb6e2.png)
last char on line is orange semicolon:
![lastchar orange](https://user-images.githubusercontent.com/1141923/87139825-d3ab5b80-c2a0-11ea-996b-842e8d8aac27.png)

**Comment by mallowigi** [comment]
Yep, looks like the color scheme highlighting is not working

**Comment by JuanEL0** [comment]
I am using IntelliJ IDEA EAP (#IU-202.6250.13) and I have the same issue.

![image](https://user-images.githubusercontent.com/64238991/87179977-43bbe080-c2a5-11ea-8d10-f3df390658c7.png)

**Comment by mallowigi** [comment]
[GitToolBox-202.0.4-SNAPSHOT.zip](https://github.com/zielu/GitToolBox/files/4904845/GitToolBox-202.0.4-SNAPSHOT.zip)

Not sure if this is meant to be released, but this is a build with the fix for latest EAP. Enjoy!

**Comment by mallowigi** [comment]
[GitToolBox-202.0.4-SNAPSHOT.zip](https://github.com/zielu/GitToolBox/files/4904902/GitToolBox-202.0.4-SNAPSHOT.zip)
Hi, not sure if this branch was meant to be released, but I forked the project and fixed this issue. I'm leaving to the author to release a fix soon, but in the meantime, enjoy!

**Comment by JuanEL0** [comment]
> [GitToolBox-202.0.4-SNAPSHOT.zip](https://github.com/zielu/GitToolBox/files/4904902/GitToolBox-202.0.4-SNAPSHOT.zip)
> Hi, not sure if this branch was meant to be released, but I forked the project and fixed this issue. I'm leaving to the author to release a fix soon, but in the meantime, enjoy!

Wow! Thank you!!

I tried to install it by downloading the Zip but the IDE shows around 9 errors, about a NoClassDefFound Exception, I'm not sure If I'm doing something wrong.

This is a case of the exception:

```
java.lang.NoClassDefFoundError: com/codahale/metrics/MetricRegistry
	at zielu.gittoolbox.metrics.MetricsManager.<init>(MetricsManager.kt:10)
	at zielu.gittoolbox.metrics.AppMetricsImpl.<init>(AppMetricsImpl.kt:9)
	at jdk.internal.reflect.GeneratedConstructorAccessor131.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:47)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:662)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:49)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:13)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.run(ServiceComponentAdapter.kt:43)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:192)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:42)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:411)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:393)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:20)
	at zielu.gittoolbox.util.AppUtil.getServiceInstance(AppUtil.kt:28)
	at zielu.gittoolbox.metrics.AppMetrics$Companion.getInstance(AppMetrics.kt:9)
	at zielu.gittoolbox.config.AppConfig.get(AppConfig.kt:23)
	at zielu.gittoolbox.ui.projectview.ProjectViewDecorator.shouldDecorate(ProjectViewDecorator.java:48)
	at zielu.gittoolbox.ui.projectview.ProjectViewDecorator.decorate(ProjectViewDecorator.java:25)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.lambda$decorate$0(CompoundProjectViewNodeDecorator.java:47)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.forEach(CompoundProjectViewNodeDecorator.java:59)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.decorate(CompoundProjectViewNodeDecorator.java:47)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$doUpdate$1(AbstractPsiBasedNode.java:168)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:835)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.doUpdate(AbstractPsiBasedNode.java:141)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$update$0(AbstractPsiBasedNode.java:137)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:168)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:126)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:115)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:110)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:137)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:74)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:27)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:453)
	at com.intellij.ui.tree.StructureTreeModel$Node.access$200(StructureTreeModel.java:421)
	at com.intellij.ui.tree.StructureTreeModel.invalidateInternal(StructureTreeModel.java:214)
	at com.intellij.ui.tree.StructureTreeModel.lambda$invalidate$5(StructureTreeModel.java:180)
	at com.intellij.ui.tree.StructureTreeModel.lambda$onValidThread$2(StructureTreeModel.java:134)
	at com.intellij.ui.tree.StructureTreeModel.lambda$onValidThread$1(StructureTreeModel.java:116)
	at com.intellij.util.concurrency.Invoker$Wrapper.get(Invoker.java:338)
	at com.intellij.util.concurrency.Invoker$Wrapper.get(Invoker.java:329)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:316)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:77)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:153)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:114)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:56)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:56)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:77)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:205)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:183)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:541)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:215)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:194)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:207)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:183)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mallowigi** [comment]
Make sure you do "Install plugin from disk" and select the zip file

**Comment by stribor** [comment]
I just noticed if I scroll to the right and last character of the line goes out of windows the inline blame gets normal gray color it was supposed to have

**Comment by zielu** [comment]
Hmm, I will take a look at the fix but it seems like IJ bug to me.

**Comment by stribor** [comment]
Bug seems to be gone in CLion 2020.2 Beta

**Comment by zielu** [comment]
I still have it in intellij but latest clion build is 202.6397.12 and my IJ is on 202.6250.13 so almost the same that clion you observed it in. Looks like this was platform issue all along.

**Comment by stribor** [comment]
Probably.
I only use CLion only (Mac and Windows) and on both I had same issue with previous EAP and today's CLion Beta solved it completely (mac and win).

Anyway thanks for wonderful plugin!
