### ISSUE TITLE
java.lang.Throwable: Too many non-blocking read actions submitted at once

### ISSUE THREAD

**Issue by starbuck-ms** [zielu/GitToolBox#261]
While running GoLand 2020.2 and GitlabToolbox Plugin 202.0.6, I saw this error in the IDE. Great plugin by the way!

I have ~50 Git repos loaded into a single session of GoLand.

Here is the stacktrace:

java.lang.Throwable: Too many non-blocking read actions submitted at once. Please use coalesceBy, BoundedTaskExecutor or another way of limiting the number of concurrently running threads.: 11 with similar stack traces are currently active
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:143)
	at com.intellij.openapi.application.impl.SubmissionTracker.preventTooManySubmissions(SubmissionTracker.java:45)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.<init>(NonBlockingReadActionImpl.java:223)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.lambda$submit$1(NonBlockingReadActionImpl.java:187)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:865)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:61)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl.submit(NonBlockingReadActionImpl.java:186)
	at com.intellij.codeInsight.highlighting.BraceHighlightingHandler.lookForInjectedAndMatchBracesInOtherThread(BraceHighlightingHandler.java:109)
	at com.intellij.codeInsight.highlighting.BraceHighlighter.clearBraces(BraceHighlighter.java:124)
	at com.intellij.codeInsight.highlighting.BraceHighlighter.access$300(BraceHighlighter.java:25)
	at com.intellij.codeInsight.highlighting.BraceHighlighter$4.selectionChanged(BraceHighlighter.java:92)
	at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:632)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:406)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:380)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:366)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:32)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:180)
	at com.sun.proxy.$Proxy39.progressWindowCreated(Unknown Source)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:107)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:43)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:35)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:31)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.lambda$runProcessWithProgressAsynchronously$2(ProgressManagerImpl.java:108)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at com.intellij.util.concurrency.PlainEdtExecutor.execute(PlainEdtExecutor.java:15)
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1714)
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1931)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressAsynchronously(ProgressManagerImpl.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runAsynchronously(CoreProgressManager.java:360)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:347)
	at com.intellij.openapi.progress.Task.queue(Task.java:110)
	at zielu.gittoolbox.blame.BlameCacheExecutor.executeWithProgress(BlameCacheExecutor.java:37)
	at zielu.gittoolbox.blame.BlameCacheExecutor.execute(BlameCacheExecutor.java:26)
	at zielu.gittoolbox.blame.BlameCacheLocalGateway.execute(BlameCacheLocalGateway.kt:40)
	at zielu.gittoolbox.blame.BlameCacheImpl.tryTaskSubmission(BlameCacheImpl.java:94)
	at zielu.gittoolbox.blame.BlameCacheImpl.triggerReload(BlameCacheImpl.java:85)
	at zielu.gittoolbox.blame.BlameCacheImpl.getAnnotationInternal(BlameCacheImpl.java:63)
	at zielu.gittoolbox.blame.BlameCacheImpl.lambda$getAnnotation$0(BlameCacheImpl.java:54)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.gittoolbox.blame.BlameCacheImpl.getAnnotation(BlameCacheImpl.java:54)
	at zielu.gittoolbox.blame.BlameServiceLocalGateway.getAnnotation(BlameServiceLocalGateway.kt:25)
	at zielu.gittoolbox.blame.BlameServiceImpl.getLineBlameInternal(BlameServiceImpl.java:57)
	at zielu.gittoolbox.blame.BlameServiceImpl.getLineBlameInternal(BlameServiceImpl.java:49)
	at zielu.gittoolbox.blame.BlameServiceImpl.lambda$getDocumentLineIndexBlame$0(BlameServiceImpl.java:39)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.gittoolbox.blame.BlameServiceImpl.getDocumentLineIndexBlame(BlameServiceImpl.java:39)
	at zielu.gittoolbox.ui.blame.BlameUiServiceLocalGateway.getLineBlame(BlameUiServiceLocalGateway.kt:81)
	at zielu.gittoolbox.ui.blame.BlameUiServiceLocalGateway.getLineBlame(BlameUiServiceLocalGateway.kt:85)
	at zielu.gittoolbox.ui.blame.BlameUiServiceImpl.getStatusWithCaching(BlameUiServiceImpl.java:142)
	at zielu.gittoolbox.ui.blame.BlameUiServiceImpl.lambda$getBlameStatusInternal$1(BlameUiServiceImpl.java:69)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.gittoolbox.ui.blame.BlameUiServiceImpl.getBlameStatusInternal(BlameUiServiceImpl.java:69)
	at zielu.gittoolbox.ui.blame.BlameUiServiceImpl.lambda$getBlameStatus$0(BlameUiServiceImpl.java:62)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.gittoolbox.ui.blame.BlameUiServiceImpl.getBlameStatus(BlameUiServiceImpl.java:62)
	at zielu.gittoolbox.ui.statusbar.BlameStatusWidget.updateStatus(BlameStatusWidget.java:71)
	at zielu.gittoolbox.ui.statusbar.BlameStatusWidget.updateBlame(BlameStatusWidget.java:164)
	at zielu.gittoolbox.ui.statusbar.BlameStatusWidget.selectionChanged(BlameStatusWidget.java:174)
	at jdk.internal.reflect.GeneratedMethodAccessor49.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:632)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:406)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:384)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:366)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:32)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:187)
	at com.sun.proxy.$Proxy98.selectionChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$fireSelectionChanged$20(FileEditorManagerImpl.java:1500)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$6.lambda$run$0(FileEditorManagerImpl.java:971)
	at com.intellij.openapi.util.ExpirableRunnable$1.run(ExpirableRunnable.java:17)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:180)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2254)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:186)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:138)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:171)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:177)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:41)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$6.run(FileEditorManagerImpl.java:970)
	at com.intellij.openapi.util.BusyObject$Impl$Simple.execute(BusyObject.java:105)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.notifyPublisher(FileEditorManagerImpl.java:967)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.fireSelectionChanged(FileEditorManagerImpl.java:1500)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.lambda$setCurrentWindow$5(EditorsSplitters.java:670)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.setCurrentWindow(EditorsSplitters.java:679)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.setEditor(EditorWindow.java:533)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.setEditor(EditorWindow.java:491)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.closeFile(EditorsSplitters.java:569)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$closeFileImpl$4(FileEditorManagerImpl.java:588)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1594)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runChange(FileEditorManagerImpl.java:1583)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFileImpl(FileEditorManagerImpl.java:588)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$closeFile$3(FileEditorManagerImpl.java:582)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:177)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:167)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:153)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.java:582)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.java:576)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$closeAllFiles$21(FileEditorManagerImpl.java:1881)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runBulkTabChange(FileEditorManagerImpl.java:1594)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeAllFiles(FileEditorManagerImpl.java:1879)
	at com.intellij.tasks.context.OpenEditorsContextProvider.clearContext(OpenEditorsContextProvider.java:66)
	at com.intellij.tasks.context.WorkingContextManager.clearContext(WorkingContextManager.java:96)
	at com.intellij.tasks.context.BranchContextTracker.switchContext(BranchContextTracker.java:62)
	at com.intellij.tasks.context.BranchContextTracker.lambda$branchHasChanged$1(BranchContextTracker.java:57)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:45)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:83)
	at com.intellij.tasks.context.BranchContextTracker.branchHasChanged(BranchContextTracker.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:632)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:406)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:384)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:366)
	at com.intellij.util.messages.impl.MessageBusImpl.access$100(MessageBusImpl.java:32)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:187)
	at com.sun.proxy.$Proxy169.branchHasChanged(Unknown Source)
	at git4idea.branch.GitBranchOperation.lambda$notifyBranchHasChanged$3(GitBranchOperation.java:274)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeAndWait$8(ApplicationImpl.java:475)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:126)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:497)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by zielu** [comment]
@starbuck-ms I pushed fix to eap channel (202.0.8) - could you give it a spin ? It basically constrains number of blame calculation tasks.
How to switch: https://github.com/zielu/GitToolBox#eap-builds

**Comment by zielu** [comment]
Done in 202.0.10 (stable)
