### ISSUE TITLE
"Cannot create zielu.gittoolbox.metrics.ProjectMetrics because container is already disposed"

### ISSUE THREAD

**Issue by yiding-he** [zielu/GitToolBox#270]
Version: `202.2.0`

Full stack trace here:

```
com.google.common.util.concurrent.UncheckedExecutionException: com.intellij.openapi.progress.ProcessCanceledException: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create zielu.gittoolbox.metrics.ProjectMetrics because container is already disposed: Project(name=poi-tl-test, containerState=DISPOSE_COMPLETED, componentStore=F:\Projects\Private\private-code\poi-tl-test)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at zielu.intellij.guava.GuavaExtensionsKt.getSafe(GuavaExtensions.kt:9)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculator.annotate(CachingBlameCalculator.kt:44)
	at zielu.gittoolbox.blame.BlameLoaderImpl.annotate(BlameLoaderImpl.java:27)
	at zielu.gittoolbox.blame.BlameCacheImpl$AnnotationLoader.load(BlameCacheImpl.java:226)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.gittoolbox.blame.BlameCacheImpl$AnnotationLoader.run(BlameCacheImpl.java:212)
	at zielu.gittoolbox.blame.BlameCacheExecutor$1.run(BlameCacheExecutor.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:935)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.openapi.progress.ProcessCanceledException: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create zielu.gittoolbox.metrics.ProjectMetrics because container is already disposed: Project(name=poi-tl-test, containerState=DISPOSE_COMPLETED, componentStore=F:\Projects\Private\private-code\poi-tl-test)
	at com.intellij.serviceContainer.ComponentManagerImpl.throwContainerIsAlreadyDisposed(ComponentManagerImpl.kt:452)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:423)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:395)
	at zielu.gittoolbox.util.AppUtil.getServiceInstance(AppUtil.kt:26)
	at zielu.gittoolbox.metrics.ProjectMetrics$Companion.getInstance(ProjectMetrics.kt:13)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculatorLocalGateway.loadFromPersistence(CachingBlameCalculatorLocalGateway.kt:27)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculator.getFromPersistence(CachingBlameCalculator.kt:72)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculator.calculate(CachingBlameCalculator.kt:62)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculator.access$calculate(CachingBlameCalculator.kt:14)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculator$loader$1.loadInContext(CachingBlameCalculator.kt:18)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculator$loader$1.loadInContext(CachingBlameCalculator.kt:16)
	at zielu.intellij.guava.ThreadLocalCacheLoader.load(ThreadLocalCacheLoader.kt:19)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 27 more
Caused by: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create zielu.gittoolbox.metrics.ProjectMetrics because container is already disposed: Project(name=poi-tl-test, containerState=DISPOSE_COMPLETED, componentStore=F:\Projects\Private\private-code\poi-tl-test)
	at com.intellij.serviceContainer.ComponentManagerImpl.throwContainerIsAlreadyDisposed(ComponentManagerImpl.kt:447)
	... 42 more
```

Not a serious issue but wish to handle this exception.

**Comment by zielu** [comment]
Hi, nice catch. This will help towards eventually making plugin dynamic and not requiring restart after update.

**Comment by zielu** [comment]
Done in 202.2.2
