### ISSUE TITLE
com.intellij.serviceContainer.AlreadyDisposedException: Already disposed

### ISSUE THREAD

**Issue by petr-nehez** [zielu/GitToolBox#273]
version 202.2.1
quite a large project

```
com.intellij.serviceContainer.AlreadyDisposedException: Already disposed: Project(name=tipsys2, containerState=DISPOSE_COMPLETED, componentStore=/home/petr/work/src/tipsport/tipsys2)
	at com.intellij.serviceContainer.ComponentManagerImpl.checkStateAndGetPicoContainer(ComponentManagerImpl.kt:132)
	at com.intellij.serviceContainer.ComponentManagerImpl.getComponent(ComponentManagerImpl.kt:364)
	at com.intellij.openapi.fileEditor.FileEditorManager.getInstance(FileEditorManager.java:21)
	at zielu.gittoolbox.ui.blame.BlameUiServiceLocalGateway.getAllEditors(BlameUiServiceLocalGateway.kt:52)
	at zielu.gittoolbox.ui.blame.BlameUiServiceImpl.handleBlameUpdated(BlameUiServiceImpl.java:174)
	at zielu.gittoolbox.ui.blame.BlameUiServiceImpl.lambda$blameUpdated$4(BlameUiServiceImpl.java:169)
	at zielu.intellij.concurrent.DisposeSafeRunnable.run(DisposeSafeRunnable.kt:16)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by zielu** [comment]
Hi, good catch. I'm currently trying to stomp out all of such errors

**Comment by zielu** [comment]
Done in 202.2.2
