### ISSUE TITLE
PluginException: Cannot init component state (componentName=GitToolBoxBlamePersistence, componentClass=BlameCalculationPersistence) [Plugin: zielu.gittoolbox]

### ISSUE THREAD

**Issue by mh080106415** [zielu/GitToolBox#284]
IntelliJ IDEA 2020.3 (Ultimate Edition)
Build #IU-203.5981.155, built on December 1, 2020
Runtime version: 11.0.9+11-b1145.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: vcs.annotations.preload=true, ide.images.show.chessboard=true
Non-Bundled Plugins: Batch Scripts Support, CMD Support, bundled-intellij-idea-help, com.hotels.intellij.plugins.network, com.intellij.ideolog, Error-prone plugin, GrepConsole, IntelliJDeodorant, SequenceDiagram, SpotProfiler, String Manipulation, VisualVMLauncher, com.herbert.george.flutter-snippets, io.codearte.props2yaml, com.intellij.plugins.macoskeymap, com.github.jk1.ytplugin, com.jetbrains.ChooseRuntime, com.jetbrains.annotations.preloader, com.jetbrains.hackathon.indices.viewer, com.jetbrains.intellij.file-manager, com.jetbrains.plugins.code-notes-plugin, com.intellij.plugins.watcher, hunspell, idea.plugin.protoeditor, in.xiv.cs, org.github.plugin.redis-simple, com.intellij.kubernetes, com.atlassian.bitbucket.references, nb-mind-map-idea, DeepBugsJavaScript, org.igu.plugins.consolelog, Dart, io.flutter, org.jetbrains.kotlin, com.jetbrains.space, com.codota.csp.intellij, com.viartemev.requestmapper, zielu.gittoolbox, com.google.gct.core, com.intellij.plugins.html.instantEditing, org.intellij.scala, izhangzhihao.rainbow.brackets, ru.adelf.idea.dotenv, org.asciidoctor.intellij.asciidoc

**the exception** 

```
com.intellij.diagnostic.PluginException: Cannot init component state (componentName=GitToolBoxBlamePersistence, componentClass=BlameCalculationPersistence) [Plugin: zielu.gittoolbox]
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:145)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.initComponent(ComponentStoreWithExtraComponents.kt:49)
	at com.intellij.serviceContainer.ComponentManagerImpl.initializeComponent$intellij_platform_serviceContainer(ComponentManagerImpl.kt:402)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:53)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:13)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.run(ServiceComponentAdapter.kt:43)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:218)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:42)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:457)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:440)
	at zielu.gittoolbox.util.AppUtil.getServiceInstance(AppUtil.kt:26)
	at zielu.gittoolbox.blame.calculator.persistence.BlameCalculationPersistence$Companion.getInstance(BlameCalculationPersistence.kt:86)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculatorLocalGateway$loadFromPersistence$1.invoke(CachingBlameCalculatorLocalGateway.kt:30)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculatorLocalGateway$loadFromPersistence$1.invoke(CachingBlameCalculatorLocalGateway.kt:14)
	at zielu.intellij.metrics.codehale.CodehaleTimer$sam$java_util_function_Supplier$0.get(CodehaleTimer.kt)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.intellij.metrics.codehale.CodehaleTimer.timeSupplierKt(CodehaleTimer.kt:10)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculatorLocalGateway.loadFromPersistence(CachingBlameCalculatorLocalGateway.kt:29)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculator.getFromPersistence(CachingBlameCalculator.kt:87)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculator.calculate(CachingBlameCalculator.kt:77)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculator.access$calculate(CachingBlameCalculator.kt:16)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculator$loader$1.loadInContext(CachingBlameCalculator.kt:22)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculator$loader$1.loadInContext(CachingBlameCalculator.kt:19)
	at zielu.intellij.guava.ThreadLocalCacheLoader.load(ThreadLocalCacheLoader.kt:19)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3974)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4958)
	at zielu.intellij.guava.GuavaExtensionsKt.getSafe(GuavaExtensions.kt:9)
	at zielu.gittoolbox.blame.calculator.CachingBlameCalculator.annotate(CachingBlameCalculator.kt:56)
	at zielu.gittoolbox.blame.BlameLoaderImpl.annotate(BlameLoaderImpl.kt:28)
	at zielu.gittoolbox.blame.BlameCacheImpl$AnnotationLoader.load(BlameCacheImpl.java:226)
	at zielu.intellij.metrics.codehale.CodehaleTimer$sam$java_util_function_Supplier$0.get(CodehaleTimer.kt)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.intellij.metrics.codehale.CodehaleTimer.timeSupplierKt(CodehaleTimer.kt:10)
	at zielu.gittoolbox.blame.BlameCacheLocalGateway.timeLoad(BlameCacheLocalGateway.kt:31)
	at zielu.gittoolbox.blame.BlameCacheImpl$AnnotationLoader.run(BlameCacheImpl.java:211)
	at zielu.gittoolbox.util.DisposeAfterExecutableTask.run(DisposeAfterExecutableTask.kt:13)
	at zielu.gittoolbox.util.DisposeSafeExecutableTask.run(DisposeSafeExecutableTask.kt:9)
	at zielu.gittoolbox.blame.BlameCacheExecutor$1.run(BlameCacheExecutor.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:962)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:235)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
	at zielu.gittoolbox.blame.calculator.persistence.BlameCalculationPersistence$cleanGarbage$1.test(BlameCalculationPersistence.kt:66)
	at zielu.gittoolbox.blame.calculator.persistence.BlameCalculationPersistence$cleanGarbage$1.test(BlameCalculationPersistence.kt:18)
	at java.base/java.util.Collection.removeIf(Collection.java:544)
	at zielu.gittoolbox.blame.calculator.persistence.BlameCalculationPersistence.cleanGarbage(BlameCalculationPersistence.kt:66)
	at zielu.gittoolbox.blame.calculator.persistence.BlameCalculationPersistence.initializeComponent(BlameCalculationPersistence.kt:30)
	at com.intellij.configurationStore.ComponentStoreImpl.initComponent(ComponentStoreImpl.kt:134)
	... 64 more 
```

**Comment by zielu** [comment]
On it

**Comment by zielu** [comment]
Done in 202.2.6
