### ISSUE TITLE
GitToolBox (201.4.2) - idea start get a crash(idea 2020.1.4)

### ISSUE THREAD

**Issue by Jcuke** [zielu/GitToolBox#289]
java.lang.UnsatisfiedLinkError: Unable to load library 'CoreFoundation':
dlopen(libCoreFoundation.dylib, 9): image not found
dlopen(libCoreFoundation.dylib, 9): image not found
Native library (darwin/libCoreFoundation.dylib) not found in resource path (/Applications/IntelliJ IDEA.app/Contents/lib/bootstrap.jar:/Applications/IntelliJ IDEA.app/Contents/lib/extensions.jar:/Applications/IntelliJ IDEA.app/Contents/lib/util.jar:/Applications/IntelliJ IDEA.app/Contents/lib/jdom.jar:/Applications/IntelliJ IDEA.app/Contents/lib/log4j.jar:/Applications/IntelliJ IDEA.app/Contents/lib/trove4j.jar:/Applications/IntelliJ IDEA.app/Contents/lib/jna.jar)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:302)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:455)
	at com.sun.jna.Library$Handler.<init>(Library.java:192)
	at com.sun.jna.Native.load(Native.java:596)
	at com.sun.jna.Native.load(Native.java:570)
	at com.intellij.util.text.DateFormatUtil.getMacFormats(DateFormatUtil.java:363)
	at com.intellij.util.text.DateFormatUtil.getDateTimeFormats(DateFormatUtil.java:303)
	at com.intellij.util.text.DateFormatUtil.<clinit>(DateFormatUtil.java:46)
	at zielu.gittoolbox.config.AbsoluteDateTimeStyle$1.getFormat(AbsoluteDateTimeStyle.java:14)
	at zielu.gittoolbox.ui.DatePresenterLocalGatewayImpl.getAbsoluteDateTimeFormat(DatePresenterLocalGatewayImpl.kt:8)
	at zielu.gittoolbox.ui.DatePresenterImpl.getAbsoluteDateTimeFormat(DatePresenterImpl.kt:33)
	at zielu.gittoolbox.ui.DatePresenterImpl.formatAbsoluteDate(DatePresenterImpl.kt:36)
	at zielu.gittoolbox.ui.DatePresenterImpl.formatImpl(DatePresenterImpl.kt:22)
	at zielu.gittoolbox.ui.DatePresenterImpl.format(DatePresenterImpl.kt:17)
	at zielu.gittoolbox.ui.blame.BlamePresenterLocalGateway.formatDateTime(BlamePresenterLocalGateway.kt:24)
	at zielu.gittoolbox.ui.blame.BlamePresenterImpl.getStatusBar(BlamePresenterImpl.java:58)
	at zielu.gittoolbox.ui.blame.BlameUiServiceLocalGateway.getStatusDecoration(BlameUiServiceLocalGateway.kt:69)
	at zielu.gittoolbox.ui.blame.LineState.getOrClearCachedStatus(LineState.java:97)
	at zielu.gittoolbox.ui.blame.BlameUiServiceImpl.getStatusWithCaching(BlameUiServiceImpl.java:146)
	at zielu.gittoolbox.ui.blame.BlameUiServiceImpl.lambda$getBlameStatusInternal$1(BlameUiServiceImpl.java:69)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.gittoolbox.ui.blame.BlameUiServiceImpl.getBlameStatusInternal(BlameUiServiceImpl.java:69)
	at zielu.gittoolbox.ui.blame.BlameUiServiceImpl.lambda$getBlameStatus$0(BlameUiServiceImpl.java:62)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.gittoolbox.ui.blame.BlameUiServiceImpl.getBlameStatus(BlameUiServiceImpl.java:62)
	at zielu.gittoolbox.ui.statusbar.BlameStatusWidget.updateStatus(BlameStatusWidget.java:71)
	at zielu.gittoolbox.ui.statusbar.BlameStatusWidget.updateBlame(BlameStatusWidget.java:164)
	at zielu.gittoolbox.ui.statusbar.BlameStatusWidget.updateBlame(BlameStatusWidget.java:156)
	at zielu.gittoolbox.ui.statusbar.BlameStatusWidget.access$900(BlameStatusWidget.java:35)
	at zielu.gittoolbox.ui.statusbar.BlameStatusWidget$4.lambda$exitDumbMode$0(BlameStatusWidget.java:147)
	at zielu.gittoolbox.util.DisposeSafeRunnable.run(DisposeSafeRunnable.kt:18)
	at zielu.gittoolbox.ui.util.AppUiUtil.invokeLaterIfNeeded(AppUiUtil.kt:28)
	at zielu.gittoolbox.ui.util.AppUiUtil.invokeLaterIfNeeded(AppUiUtil.kt:36)
	at zielu.gittoolbox.ui.statusbar.BlameStatusWidget$4.exitDumbMode(BlameStatusWidget.java:147)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:541)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:143)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:465)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:415)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:395)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:237)
	at com.sun.proxy.$Proxy84.beforePsiChanged(Unknown Source)
	at com.intellij.psi.impl.PsiManagerImpl.beforeChange(PsiManagerImpl.java:444)
	at com.intellij.psi.impl.PsiManagerImpl.beforePropertyChange(PsiManagerImpl.java:244)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.lambda$null$3(FileManagerImpl.java:280)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.lambda$processFileTypesChanged$4(FileManagerImpl.java:277)
	at com.intellij.psi.impl.DebugUtil.performPsiModification(DebugUtil.java:565)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.processFileTypesChanged(FileManagerImpl.java:275)
	at com.intellij.psi.impl.file.impl.FileManagerImpl$1.exitDumbMode(FileManagerImpl.java:75)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:541)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:143)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:465)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:415)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:395)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:237)
	at com.sun.proxy.$Proxy46.modificationCountChanged(Unknown Source)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.fireEvent(PsiModificationTrackerImpl.java:66)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.incCountersInner(PsiModificationTrackerImpl.java:71)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.incCounter(PsiModificationTrackerImpl.java:57)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.lambda$doIncCounter$1(PsiModificationTrackerImpl.java:53)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:976)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.doIncCounter(PsiModificationTrackerImpl.java:53)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.access$000(PsiModificationTrackerImpl.java:27)
	at com.intellij.psi.impl.PsiModificationTrackerImpl$1.exitDumbMode(PsiModificationTrackerImpl.java:47)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:541)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:143)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:465)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:426)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:415)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.lambda$createTopicHandler$3(MessageBusImpl.java:237)
	at com.sun.proxy.$Proxy75.exitDumbMode(Unknown Source)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:412)
	at com.intellij.openapi.project.DumbServiceImpl$TrackedEdtActivity.run(DumbServiceImpl.java:909)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:310)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:80)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:128)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:46)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:184)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:974)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:847)
	at com.intellij.ide.IdeEventQueue.lambda$null$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:741)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:496)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libCoreFoundation.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:191)
		... 114 more
	Suppressed: java.lang.UnsatisfiedLinkError: dlopen(libCoreFoundation.dylib, 9): image not found
		at com.sun.jna.Native.open(Native Method)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:204)
		... 114 more
	Suppressed: java.io.IOException: Native library (darwin/libCoreFoundation.dylib) not found in resource path (/Applications/IntelliJ IDEA.app/Contents/lib/bootstrap.jar:/Applications/IntelliJ IDEA.app/Contents/lib/extensions.jar:/Applications/IntelliJ IDEA.app/Contents/lib/util.jar:/Applications/IntelliJ IDEA.app/Contents/lib/jdom.jar:/Applications/IntelliJ IDEA.app/Contents/lib/log4j.jar:/Applications/IntelliJ IDEA.app/Contents/lib/trove4j.jar:/Applications/IntelliJ IDEA.app/Contents/lib/jna.jar)
		at com.sun.jna.Native.extractFromResourcePath(Native.java:1095)
		at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:276)
		... 114 more

**Comment by zielu** [comment]
@Jcuke updated to Big Sur ?

**Comment by Jcuke** [comment]
yes



发自我的iPhone


------------------ Original ------------------

**Comment by zielu** [comment]
I'll add a workaround to not use build-in platform formatter

**Comment by zielu** [comment]
Fixed in 201.4.3
