### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by ForteScarlet** [zielu/GitToolBox#311]
IDEA:  `2021.1.1`
version:  `203.5.8`
stacktrace: 
```
java.lang.ClassCastException: class com.intellij.DynamicBundle$LanguageBundleEP cannot be cast to class com.intellij.DynamicBundle$LanguageBundleEP (com.intellij.DynamicBundle$LanguageBundleEP is in unnamed module of loader com.intellij.util.lang.PathClassLoader @36f6e879; com.intellij.DynamicBundle$LanguageBundleEP is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @22f7bb55)
	at com.intellij.DynamicBundle.findLanguageBundle(DynamicBundle.java:82)
	at com.intellij.DynamicBundle.findBundle(DynamicBundle.java:36)
	at com.intellij.AbstractBundle.resolveResourceBundle(AbstractBundle.java:146)
	at com.intellij.AbstractBundle.getResourceBundle(AbstractBundle.java:116)
	at com.intellij.AbstractBundle.getMessage(AbstractBundle.java:43)
	at zielu.gittoolbox.ResBundle.message(ResBundle.kt:10)
	at zielu.gittoolbox.ui.actions.RefreshBlameAction.<init>(RefreshBlameAction.kt:12)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:240)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:220)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:551)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1601)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:14)
	at com.intellij.openapi.application.Preloader.lambda$preload$0(Preloader.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.application.Preloader.lambda$preload$1(Preloader.java:74)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by zielu** [comment]
Hi, could you add a screenshot of About IntelliJ IDEA popup ?

**Comment by ForteScarlet** [comment]
![1](https://user-images.githubusercontent.com/40045247/118606623-3c7d3180-b7ea-11eb-8315-394c03b775c5.png)
![2](https://user-images.githubusercontent.com/40045247/118606639-40a94f00-b7ea-11eb-9dde-2176fab022a6.png)
Like this?

**Comment by zielu** [comment]
This one :)

**Comment by ForteScarlet** [comment]
i'm sorry
![3](https://user-images.githubusercontent.com/40045247/118609348-376db180-b7ed-11eb-81f5-3e69c0c2520f.png)

**Comment by KingOfGitH** [comment]
我也遇到了这个问题

**Comment by zielu** [comment]
So it looks like it is somehow related to changing IDE locale to different than english. I'll try to find time over weekend to dig into this.

**Comment by zielu** [comment]
https://youtrack.jetbrains.com/issue/IDEA-268744

**Comment by zielu** [comment]
Done in 203.5.10
