### ISSUE TITLE
Indefinite UI freeze (GitToolbox 212.6.1 on IntelliJ 212.4037.9)

### ISSUE THREAD

**Issue by aaronols** [zielu/GitToolBox#319]
Hello zielu,

I am sad to see this wonderful plugin go closed-source.
But I understand that you value your time and resources.
Your work makes my day easier and i want to thank you for that.

Now with the latest version (212.6.1) of the plugin running on the latest IntelliJ 2021.2 EAP (212.4037.9), I observed an indefinite ui freeze.
It may have been a deadlock because there was <1% cpu usage.

The freeze happened after trying to pull changes from a remote repository.
The entire ui froze in the middle of the operation.
The status bar still had the progress bar for the pull operation displayed.
But the underlying git operation seems to have been successful and the repository contains all pulled commits.
Not even the title bar with the minize/maximize/close buttons was responsive anymore.
After about three minutes I killed the process.

Luckily, IntelliJ is clever about ui freezes and prompted me with the following information about the freeze:

<details>
  <summary>Stacktrace</summary>
  
  ```java
Freeze for 181 seconds
IDE KILLED! Sampled time: 169200ms, sampling rate: 100ms, GC time: 189ms (0%), Class loading: 0%, cpu load: 1%

The stack is from the thread that was blocking EDT

com.intellij.diagnostic.Freeze
	at java.base@11.0.11/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1723)
	at zielu.gittoolbox.c.J.f(SourceFile:104)
	at zielu.gittoolbox.c.J.b(SourceFile:93)
	at zielu.gittoolbox.w.f.n.a(SourceFile:59)
	at zielu.gittoolbox.w.f.n.a(SourceFile:42)
	at zielu.gittoolbox.w.f.n$$Lambda$12152/0x0000000806966c40.run(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:151)
	at zielu.a.f.a.i.a(SourceFile:22)
	at zielu.gittoolbox.w.f.n.a(SourceFile:42)
	at zielu.gittoolbox.w.f.n.b(SourceFile:27)
	at zielu.gittoolbox.w.f.n$$Lambda$3018/0x0000000802170840.run(Unknown Source)
	at com.codahale.metrics.Timer.time(Timer.java:151)
	at zielu.a.f.a.i.a(SourceFile:22)
	at zielu.gittoolbox.w.f.n.decorate(SourceFile:27)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.lambda$decorate$0(CompoundProjectViewNodeDecorator.java:47)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator$$Lambda$3015/0x0000000802177440.accept(Unknown Source)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.forEach(CompoundProjectViewNodeDecorator.java:59)
	at com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.decorate(CompoundProjectViewNodeDecorator.java:47)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$doUpdate$1(AbstractPsiBasedNode.java:195)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode$$Lambda$2977/0x00000008020e5040.run(Unknown Source)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:827)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.doUpdate(AbstractPsiBasedNode.java:145)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$update$0(AbstractPsiBasedNode.java:141)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode$$Lambda$2973/0x00000008020e6040.run(Unknown Source)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:172)
	at com.intellij.util.AstLoadingFilter$$Lambda$2975/0x00000008020e5840.compute(Unknown Source)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:130)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:119)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:109)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:141)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:78)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:30)
	at com.intellij.ui.tree.StructureTreeModel$Node.update(StructureTreeModel.java:455)
	at com.intellij.ui.tree.StructureTreeModel.invalidateInternal(StructureTreeModel.java:215)
	at com.intellij.ui.tree.StructureTreeModel.lambda$invalidate$5(StructureTreeModel.java:181)
	at com.intellij.ui.tree.StructureTreeModel$$Lambda$3267/0x00000008022ed440.apply(Unknown Source)
	at com.intellij.ui.tree.StructureTreeModel.lambda$onValidThread$2(StructureTreeModel.java:135)
	at com.intellij.ui.tree.StructureTreeModel$$Lambda$3268/0x00000008022ed840.apply(Unknown Source)
	at com.intellij.ui.tree.StructureTreeModel.lambda$onValidThread$1(StructureTreeModel.java:117)
	at com.intellij.ui.tree.StructureTreeModel$$Lambda$2967/0x00000008020e7840.run(Unknown Source)
	at com.intellij.util.concurrency.Invoker$Wrapper.get(Invoker.java:338)
	at com.intellij.util.concurrency.Invoker$Wrapper.get(Invoker.java:329)
	at com.intellij.util.concurrency.Invoker$Task.run(Invoker.java:316)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1077)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:78)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$$Lambda$735/0x0000000800aa4c40.run(Unknown Source)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:161)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:118)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils$$Lambda$737/0x0000000800aa4440.compute(Unknown Source)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:57)
	at com.intellij.openapi.progress.ProgressManager$$Lambda$738/0x0000000800aa3840.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$387/0x0000000800567440.run(Unknown Source)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:57)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:115)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:78)
	at com.intellij.util.concurrency.Invoker.invokeSafely(Invoker.java:205)
	at com.intellij.util.concurrency.Invoker.lambda$offerSafely$0(Invoker.java:183)
	at com.intellij.util.concurrency.Invoker$$Lambda$1867/0x0000000801689440.run(Unknown Source)
	at com.intellij.util.concurrency.Invoker$Background.lambda$offer$0(Invoker.java:541)
	at com.intellij.util.concurrency.Invoker$Background$$Lambda$1868/0x0000000801689840.run(Unknown Source)
	at java.base@11.0.11/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base@11.0.11/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1$$Lambda$503/0x0000000800720040.run(Unknown Source)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.11/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base@11.0.11/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base@11.0.11/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base@11.0.11/java.security.AccessController.doPrivileged(Native Method)
	at java.base@11.0.11/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base@11.0.11/java.lang.Thread.run(Thread.java:829)
  ```
</details>

<details>
  <summary>Timing breakdown</summary>
  
  ```java
 java.lang.Thread.run 169200ms
  java.util.concurrent.Executors$PrivilegedThreadFactory$1.run 169200ms
   java.security.AccessController.doPrivileged 169200ms
    java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run 169200ms
     java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run 169200ms
      java.util.concurrent.ThreadPoolExecutor$Worker.run 169200ms
       java.util.concurrent.ThreadPoolExecutor.runWorker 169200ms
        com.intellij.util.concurrency.BoundedTaskExecutor$1.run 169200ms
         com.intellij.util.ConcurrencyUtil.runUnderThreadName 169200ms
          com.intellij.util.concurrency.BoundedTaskExecutor$1$$Lambda$503/0x0000000800720040.run 169200ms
           com.intellij.util.concurrency.BoundedTaskExecutor$1.execute 169200ms
            com.intellij.util.concurrency.BoundedTaskExecutor.access$200 169200ms
             com.intellij.util.concurrency.BoundedTaskExecutor.doRun 169200ms
              com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run 169200ms
               java.util.concurrent.FutureTask.run 169200ms
                java.util.concurrent.Executors$RunnableAdapter.call 169200ms
                 com.intellij.util.concurrency.Invoker$Background$$Lambda$1868/0x0000000801689840.run 169200ms
                  com.intellij.util.concurrency.Invoker$Background.lambda$offer$0 169200ms
                   com.intellij.util.concurrency.Invoker$$Lambda$1867/0x0000000801689440.run 169200ms
                    com.intellij.util.concurrency.Invoker.lambda$offerSafely$0 169200ms
                     com.intellij.util.concurrency.Invoker.invokeSafely 169200ms
                      com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority 169200ms
                       com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority 169200ms
                        com.intellij.openapi.progress.ProgressManager.runProcess 169200ms
                         com.intellij.openapi.progress.impl.CoreProgressManager.runProcess 169200ms
                          com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress 169200ms
                           com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress 169200ms
                            com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun 169200ms
                             com.intellij.openapi.progress.impl.CoreProgressManager$$Lambda$387/0x0000000800567440.run 169200ms
                              com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2 169200ms
                               com.intellij.openapi.progress.ProgressManager$$Lambda$738/0x0000000800aa3840.run 169200ms
                                com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0 169200ms
                                 com.intellij.openapi.progress.util.ProgressIndicatorUtils$$Lambda$737/0x0000000800aa4440.compute 169200ms
                                  com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1 169200ms
                                   com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite 169200ms
                                    com.intellij.openapi.progress.util.ProgressIndicatorUtils$$Lambda$735/0x0000000800aa4c40.run 169200ms
                                     com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0 169200ms
                                      com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction 169200ms
                                       com.intellij.util.concurrency.Invoker$Task.run 169200ms
                                        com.intellij.util.concurrency.Invoker$Wrapper.get 169200ms
                                         com.intellij.util.concurrency.Invoker$Wrapper.get 169200ms
                                          com.intellij.ui.tree.StructureTreeModel$$Lambda$2967/0x00000008020e7840.run 169200ms
                                           com.intellij.ui.tree.StructureTreeModel.lambda$onValidThread$1 169200ms
                                            com.intellij.ui.tree.StructureTreeModel$$Lambda$3268/0x00000008022ed840.apply 169200ms
                                             com.intellij.ui.tree.StructureTreeModel.lambda$onValidThread$2 169200ms
                                              com.intellij.ui.tree.StructureTreeModel$$Lambda$3267/0x00000008022ed440.apply 169200ms
                                               com.intellij.ui.tree.StructureTreeModel.lambda$invalidate$5 169200ms
                                                com.intellij.ui.tree.StructureTreeModel.invalidateInternal 169200ms
                                                 com.intellij.ui.tree.StructureTreeModel$Node.update 169200ms
                                                  com.intellij.ide.util.treeView.PresentableNodeDescriptor.update 169200ms
                                                   com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation 169200ms
                                                    com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update 169200ms
                                                     com.intellij.util.AstLoadingFilter.disallowTreeLoading 169200ms
                                                      com.intellij.util.AstLoadingFilter.disallowTreeLoading 169200ms
                                                       com.intellij.util.AstLoadingFilter.disallowTreeLoading 169200ms
                                                        com.intellij.util.AstLoadingFilter$$Lambda$2975/0x00000008020e5840.compute 169200ms
                                                         com.intellij.util.AstLoadingFilter.lambda$toComputable$2 169200ms
                                                          com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode$$Lambda$2973/0x00000008020e6040.run 169200ms
                                                           com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$update$0 169200ms
                                                            com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.doUpdate 169200ms
                                                             com.intellij.openapi.application.impl.ApplicationImpl.runReadAction 169200ms
                                                              com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode$$Lambda$2977/0x00000008020e5040.run 169200ms
                                                               com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.lambda$doUpdate$1 169200ms
                                                                com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.decorate 169200ms
                                                                 com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.forEach 169200ms
                                                                  com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator$$Lambda$3015/0x0000000802177440.accept 169200ms
                                                                   com.intellij.ide.projectView.impl.CompoundProjectViewNodeDecorator.lambda$decorate$0 169200ms
                                                                    zielu.gittoolbox.w.f.n.decorate 169200ms
                                                                     zielu.a.f.a.i.a 169200ms
                                                                      com.codahale.metrics.Timer.time 169200ms
                                                                       zielu.gittoolbox.w.f.n$$Lambda$3018/0x0000000802170840.run 169200ms
                                                                        zielu.gittoolbox.w.f.n.b 169200ms
                                                                         zielu.gittoolbox.w.f.n.a 169200ms
                                                                          zielu.a.f.a.i.a 169200ms
                                                                           com.codahale.metrics.Timer.time 169200ms
                                                                            zielu.gittoolbox.w.f.n$$Lambda$12152/0x0000000806966c40.run 169200ms
                                                                             zielu.gittoolbox.w.f.n.a 169200ms
                                                                              zielu.gittoolbox.w.f.n.a 169200ms
                                                                               zielu.gittoolbox.c.J.b 169200ms
                                                                                zielu.gittoolbox.c.J.f 169200ms
                                                                                 java.util.concurrent.ConcurrentHashMap.computeIfAbsent 169200ms
  ```
</details>

I also have multiple thread dumps available.
If they help I can add them to this issue.

I was not able to reproduce the issue.
Probably because there were no new commits available at the remote to be pulled.
I had multiple project windows open at the same time.

Here is some more information about the installation:

```
IntelliJ IDEA 2021.2 EAP (Ultimate Edition)
Build #IU-212.4037.9, built on June 8, 2021
IntelliJ IDEA EAP User
Expiration date: July 8, 2021
Runtime version: 11.0.11+9-b1481.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry: search.everywhere.settings=true, ide.balloon.shadow.size=0
Non-Bundled Plugins: Batch Scripts Support (1.0.12), com.jetbrains.plugins.ini4idea (212.4037.9), com.intellij.plugins.watcher (212.4037.9), mobi.hsz.idea.gitignore (4.1.1), name.kropp.intellij.makefile (212.4037.9), org.nik.presentation-assistant (1.0.9), some.awesome (1.14), CheckStyle-IDEA (5.53.0), GrepConsole (11.9.211.6086.0), org.sonarlint.idea (4.16.0.31683), com.intellij.plugin.adernov.powershell (2.0.7), com.perl5 (212-SNAPSHOT), com.dmarcotte.handlebars (212.4037.9), Dart (212.4037.9), Pythonid (212.4037.9), com.intellij.selenium (212.4037.9), org.exbin.deltahex.intellij (0.2.4), org.jetbrains.plugins.vue (212.4037.9), org.igu.plugins.nativescript (0.21.0), izhangzhihao.rainbow.brackets (6.17), zielu.gittoolbox (212.6.1), org.asciidoctor.intellij.asciidoc (0.33.3)
Kotlin: 212-1.4.32-release-IJ4037.9
```

**Comment by zielu** [comment]
Thank you for kind words !

I'll take a look what is wrong.

**Comment by zielu** [comment]
Ok, I think I know what is wrong - nasty concurrency issue if invocations of `git` take long

**Comment by zielu** [comment]
Done in 212.6.4

**Comment by aaronols** [comment]
Thank you for fixing this issue.
Before updating the plugin I got another hang at the same code path.
After updating the plugin this issue has not happened again.

I usually read through your code changes after you fixed bugs that affected me to learn more about how plugins work and how you solve difficult problems.
I am a bit sad that I cannot do that anymore now since the plugin is now closed-source.
What would it take for you to open-source it again in the future?

**Comment by zielu** [comment]
Issue was in https://github.com/zielu/GitToolBox/blob/202-release/src/main/java/zielu/gittoolbox/cache/PerRepoInfoCacheImpl.java#L65 - computeIfPresent will lock section of ConcurrentHashMap until `git status` and other calls finish and if UI (project view in this case) comes for RepoInto it will block until `git` call is done
