### ISSUE TITLE
NPE for Show Inline Blame with new Idea

### ISSUE THREAD

**Issue by svitalsky** [zielu/GitToolBox#338]
Upon calling (with shortcut) Show Inline Blame I receive NPE (see bellow). IDEA 2021.2.1, GitToolBox 212.7.7.

java.lang.NullPointerException
	at zielu.gittoolbox.config.model.ExtrasBoolConfigOverride.copy(SourceFile:20)
	at zielu.gittoolbox.config.model.ExtrasConfig.copy(SourceFile:14)
	at zielu.gittoolbox.config.model.GitToolBoxConfig2.copy(SourceFile:72)
	at zielu.gittoolbox.w.c.run(SourceFile:67)
	at com.intellij.openapi.application.WriteAction.lambda$runAndWait$2(WriteAction.java:123)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteActionWithClass(ApplicationImpl.java:924)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:950)
	at com.intellij.openapi.application.WriteAction.computeAndWait(WriteAction.java:138)
	at com.intellij.openapi.application.WriteAction.runAndWait(WriteAction.java:122)
	at zielu.gittoolbox.w.a.a(SourceFile:65)
	at zielu.gittoolbox.v.a.f.setSelected(SourceFile:14)
	at com.intellij.openapi.actionSystem.ToggleAction.actionPerformed(ToggleAction.java:49)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:563)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$8(IdeKeyEventDispatcher.java:677)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:603)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:574)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:457)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:450)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:218)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:800)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:442)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:494)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by svitalsky** [comment]
Upon consequent calls (again with shortcut) nothing happens.

**Comment by zielu** [comment]
@svitalsky nothing happens - means it does not work or no error :)

**Comment by svitalsky** [comment]
@zielu Both, actually. Simply put, upon subsequent use of keyboard shortcut it does not react at all. First → NPE, next → nothing.

Oh, and it is the same both on Linux and Windows, if that's of any consequence.

**Comment by zielu** [comment]
I've seen this kind of config corruption at least once and it is hard to pin-point. As this part of config is deprecated in next release I will just remove it all together

**Comment by svitalsky** [comment]
Sorry, does that mean, that this functionality—Show Inline Blame—will not be available any more?

**Comment by zielu** [comment]
It will be, in essence I will just add workaround to prevent corrupted config from disabling the feature.

**Comment by svitalsky** [comment]
Great, thanks.

**Comment by zielu** [comment]
Done in (203/212).7.10

**Comment by svitalsky** [comment]
I am sorry but it is only half-solved: the NPE indeed does not appear any more, however the inline blame does not appear either. Actually, nothing at all happens upon my keyboard shortcut for this functionality. Idea 2021.2.2.

**Comment by zielu** [comment]
Maybe your git root is not added to version control - see https://github.com/zielu/GitToolBox/wiki/Manual#inline-blame-does-not-work-in-git-directory

**Comment by svitalsky** [comment]
@zielu It is not either of these: no multiple repos as modules, and my Git root is OK (it does show blame in the status line &c.). However I've learnt in the meantime it behaves even weirder: if I close Idea with inline blame "On" (not really On, as I wrote, nothing happens, visually, that is, but supposedly On) and start it again, the shortcut works as expected—shows and hides inline blame. If however I close Idea with inline blame Off, upon next start the shortcut does visually nothing (but if I call it odd-number-times and thus leave it "On", it will work again on next Idea start).

**Comment by svitalsky** [comment]
Just to confirm—the described behavior is the same on Linux and Windows.

**Comment by zielu** [comment]
I managed to reproduce it - on MacOS too - so it must be smth general related to change propagation when inline blame starts disabled. I'll take a look

**Comment by zielu** [comment]
@svitalsky root cause identified - fix on the way

**Comment by zielu** [comment]
Fix in Fixed in 203/212.7.11

**Comment by svitalsky** [comment]
Seems to be working all right (both Win and Lin). Thanks a lot.
