### ISSUE TITLE
Getting "java.lang.IndexOutOfBoundsException" on resetting (--hard) HEAD to a previous commit

### ISSUE THREAD

**Issue by vivekmore** [zielu/GitToolBox#340]
```java
Following exceptions happened soon after this one, most probably they are induced.


2021-09-10T10:31:11.194
java.lang.IndexOutOfBoundsException: Wrong line: 15. Available lines count: 14
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:200)
	at com.intellij.openapi.editor.impl.LineSet.getLineEnd(LineSet.java:194)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineEndOffset(DocumentImpl.java:1023)
	at m212.e.a(SourceFile:56)
	at m212.e.paint(SourceFile:120)
	at com.intellij.openapi.editor.impl.view.EditorPainter$Session$1.lambda$paintAfterLineEnd$6(EditorPainter.java:451)
	at com.intellij.openapi.editor.impl.view.EditorPainter$Session.lambda$paintTextWithEffects$4(EditorPainter.java:645)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.intellij.openapi.editor.impl.view.EditorPainter$Session.paintTextWithEffects(EditorPainter.java:645)
	at com.intellij.openapi.editor.impl.view.EditorPainter$Session.paint(EditorPainter.java:190)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:71)
	at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:287)
	at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1954)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:255)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1077)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:126)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5263)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1654)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1566)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:262)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5211)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5021)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:868)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:482)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)


2021-09-10T10:31:11.239
java.lang.IndexOutOfBoundsException: Wrong line: 15. Available lines count: 14
	at com.intellij.openapi.editor.impl.LineSet.checkLineIndex(LineSet.java:200)
	at com.intellij.openapi.editor.impl.LineSet.getLineEnd(LineSet.java:194)
	at com.intellij.openapi.editor.impl.DocumentImpl.getLineEndOffset(DocumentImpl.java:1023)
	at m212.e.a(SourceFile:56)
	at m212.e.paint(SourceFile:120)
	at com.intellij.openapi.editor.impl.view.EditorPainter$Session$1.lambda$paintAfterLineEnd$6(EditorPainter.java:451)
	at com.intellij.openapi.editor.impl.view.EditorPainter$Session.lambda$paintTextWithEffects$4(EditorPainter.java:645)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.intellij.openapi.editor.impl.view.EditorPainter$Session.paintTextWithEffects(EditorPainter.java:645)
	at com.intellij.openapi.editor.impl.view.EditorPainter$Session.paint(EditorPainter.java:190)
	at com.intellij.openapi.editor.impl.view.EditorPainter.paint(EditorPainter.java:71)
	at com.intellij.openapi.editor.impl.view.EditorView.paint(EditorView.java:287)
	at com.intellij.openapi.editor.impl.EditorImpl.paint(EditorImpl.java:1954)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paintComponent(EditorComponentImpl.java:255)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1077)
	at com.intellij.openapi.editor.impl.EditorComponentImpl.paint(EditorComponentImpl.java:126)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JViewport.paint(JViewport.java:737)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:237)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:910)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1086)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5263)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1654)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1566)
	at java.desktop/javax.swing.BufferStrategyPaintManager.paint(BufferStrategyPaintManager.java:262)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5211)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5021)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:868)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:482)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

----
GitToolBox version: **212.7.7**

**IDE Details:**
IntelliJ IDEA 2021.2.2 RC (Ultimate Edition)
Build #IU-212.5284.31, built on September 7, 2021

Runtime version: 11.0.12+7-b1504.28 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.5.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Non-Bundled Plugins: FrameSwitcher (3.27.0-203), net.seesharpsoft.intellij.plugins.csv (2.17.1), com.intellij.javafx (1.0.3), google-java-format (1.9.0.1), com.arcticicestudio.nord.jetbrains (0.13.0), manjaro.mpb (1.6), org.antlr.intellij.plugin (1.16), org.sonarlint.idea (5.2.0.35150), com.intellij.kubernetes (212.5284.17), com.sunny.plugin.MockitoGenPlugin (1.4.0), Builder Generator (1.1.8), VisualVMLauncher (1.20.203.4204.0), String Manipulation (8.15.203.000.3), zielu.gittoolbox (212.7.7), lermitage.intellij.extra.icons (1.61.0.203), org.asciidoctor.intellij.asciidoc (0.33.19), MavenRunHelper (4.16.212.000.0), org.jetbrains.kotlin (212-1.5.30-release-409-IJ4638.7), de.endrullis.idea.postfixtemplates (2.12.1.212), org.mapstruct.intellij (1.3.0), com.jetbrains.edu (2021.8-2021.2-298)
Kotlin: 212-1.5.30-release-409-IJ4638.7

**Comment by zielu** [comment]
Fix is already in place, just not yet released. I'll push out EAP version very soon.

**Comment by vivekmore** [comment]
Did I mention .. your plugin is awesome 👍🏼

**Comment by zielu** [comment]
Done in (203/212).7.10
