### ISSUE TITLE
An error was reported after installation  (AndroidStudio)

### ISSUE THREAD

**Issue by BaiMingxu** [zielu/GitToolBox#379]
Auto fetch failed
		Invocation failed Unexpected end of file from server
		java.lang.RuntimeException: Invocation failed Unexpected end of file from server
		at org.jetbrains.git4idea.GitAppUtil.sendXmlRequest(GitAppUtil.java:30)
		at org.jetbrains.git4idea.http.GitAskPassApp.main(GitAskPassApp.java:58)
		Caused by: java.net.SocketException: Unexpected end of file from server
		at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:866)
		at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
		at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:863)
		at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
		at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
		at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
		at org.apache.xmlrpc.DefaultXmlRpcTransport.sendXmlRpc(DefaultXmlRpcTrans... (show balloon)

**Comment by zielu** [comment]
Hi, this is not caused by the plugin itself but failure to fetch from repository. Does the same happen when you invoke IDE action Git > Fetch ?

**Comment by zielu** [comment]
Not feedback
