### ISSUE TITLE
Datagrip Runtime Exception

### ISSUE THREAD

**Issue by CarinaSchoppe** [zielu/GitToolBox#423]
Just started DataGrip

Exception should not happen...

Stacktrace
Not disposed

java.lang.RuntimeException: Cannot invoke (class=l, method=a, topic=Git ToolBox File Changes)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:639)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:395)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:374)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:433)
	at jdk.proxy10/jdk.proxy10.$Proxy138.a(Unknown Source)
	at zielu.gittoolbox.c.c.a(SourceFile:29)
	at zielu.gittoolbox.c.c.invoke(SourceFile:28)
	at zielu.a.b.n.run(SourceFile:47)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.o.a(SourceFile:21)
	at zielu.a.b.o.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.l.run(SourceFile:18)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.vfs.VirtualFile.getPath()" because "<local10>" is null
	at zielu.gittoolbox.c.d.a(SourceFile:54)
	at zielu.gittoolbox.c.m.a(SourceFile:52)
	at zielu.gittoolbox.c.m.invoke(SourceFile:51)
	at zielu.gittoolbox.C.u.a(SourceFile:12)
	at zielu.gittoolbox.c.l.a(SourceFile:51)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:655)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:621)
	... 18 more

DataGrip 2022.3 EAP
Build #DB-223.7255.83, built on October 27, 2022
Licensed to DataGrip EAP user: Carina Sophie Schoppe
Expiration date: November 25, 2022
Runtime version: 17.0.4.1+1-b653.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 16032M
Cores: 24
Registry:
    editor.focus.mode.color.light=474747
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=474747
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.tabnine.TabNine (0.7.27)
    com.wakatime.intellij.plugin (14.1.1)
    awesome.console (0.1337.12)
    Statistic (4.2.6)
    net.seesharpsoft.intellij.plugins.csv (2.21.0)
    com.github.copilot (1.1.35.2072-nightly)
    izhangzhihao.rainbow.brackets (2022.3.1)
    com.intellij.bigdatatools (223.7255.1)
    com.mallowigi (80.0.0)
    zielu.gittoolbox (212.9.12)
    org.sonarlint.idea (7.1.1.54565)
    com.chrisrm.idea.MaterialThemeUI (8.0.1)
    com.almightyalpaca.intellij.plugins.discord (1.10.0)
    krasa.CpuUsageIndicator (1.14)
    cn.yiiguxing.plugin.translate (3.3.5)
    Key Promoter X (2022.3)

**Comment by zielu** [comment]
Hi, I'll take a look into this

**Comment by zielu** [comment]
Looks like a null check was missing in one case

**Comment by zielu** [comment]
Done in 212.10.0
