### ISSUE TITLE
[BUG] IDE Internal Errors

### ISSUE THREAD

**Issue by xuemanchi** [zielu/GitToolBox#426]
**Describe the bug**

Following exceptions happened soon after this one, most probably they are induced.

2022-11-18T15:42:56.555
com.intellij.diagnostic.PluginException: Cannot create class zielu.gittoolbox.c.aK (classloader=PluginClassLoader(plugin=PluginDescriptor(name=GitToolBox, id=zielu.gittoolbox, descriptorPath=plugin.xml, path=G:\Webstorm\.WebStorm\config\plugins\gittoolbox-212.10.1.jar, version=212.10.1, package=null, isBundled=false), packagePrefix=null, instanceId=90, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:883)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:823)
	at com.intellij.serviceContainer.ComponentManagerImpl.access$createLightService(ComponentManagerImpl.kt:55)
	at com.intellij.serviceContainer.ComponentManagerImpl$getOrCreateLightService$$inlined$synchronized$lambda$1.run(ComponentManagerImpl.kt:673)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:223)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:238)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:222)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:672)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:621)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:583)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at zielu.gittoolbox.F.a.b(SourceFile:20)
	at zielu.gittoolbox.c.aE.a(SourceFile:64)
	at zielu.gittoolbox.c.e.a(SourceFile:23)
	at zielu.gittoolbox.c.e.invoke(SourceFile:22)
	at zielu.gittoolbox.c.S.a(SourceFile:9)
	at zielu.gittoolbox.c.S.invoke(SourceFile:8)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at zielu.gittoolbox.c.R.a(SourceFile:8)
	at zielu.gittoolbox.c.R.a(SourceFile:13)
	at zielu.gittoolbox.c.d.a(SourceFile:46)
	at zielu.gittoolbox.c.q.a(SourceFile:41)
	at zielu.gittoolbox.c.q.invoke(SourceFile:40)
	at zielu.gittoolbox.F.A.a(SourceFile:12)
	at zielu.gittoolbox.c.p.mappingChanged(SourceFile:40)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:646)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:629)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:399)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:378)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:437)
	at jdk.proxy2/jdk.proxy2.$Proxy114.mappingChanged(Unknown Source)
	at com.intellij.dvcs.repo.VcsRepositoryManager.checkAndUpdateRepositoriesCollection(VcsRepositoryManager.java:350)
	at com.intellij.dvcs.repo.VcsRepositoryManager$MyStartupActivity.runActivity(VcsRepositoryManager.java:84)
	at com.intellij.openapi.vcs.impl.VcsInitialization.lambda$runActivities$3(VcsInitialization.java:157)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:241)
	at com.intellij.openapi.vcs.impl.VcsInitialization.runActivities(VcsInitialization.java:157)
	at com.intellij.openapi.vcs.impl.VcsInitialization.runInitStep(VcsInitialization.java:141)
	at com.intellij.openapi.vcs.impl.VcsInitialization.execute(VcsInitialization.java:112)
	at com.intellij.openapi.vcs.impl.VcsInitialization$1.run(VcsInitialization.java:68)

**To Reproduce**

**Expected behavior**

**Plugin version**
Exact plugin version. Eg. 212.8.4
212.10.1

**IDE version**
Exact IDE and OS. You can use About > Copy 
WebStorm 2022.2.2

**Screenshots**

**Comment by xuemanchi** [comment]
sorry...
caused by wrong installation..

**Comment by zielu** [comment]
Let me guess - you extracted jar file from downloaded zip ?

**Comment by xuemanchi** [comment]
yep.. I used to install this plugin without extract :cry:

**Comment by zielu** [comment]
No worries, I was afraid smth is wrong with packaging
