### ISSUE TITLE
[BUG] error on project open

### ISSUE THREAD

**Issue by Machine-Maker** [zielu/GitToolBox#428]
**Describe the bug**
Seemed to just start happening when I open a project. I noticed my inline blames weren't showing up and saw there was this error.

stacktrace.txt: https://pastes.dev/SpV1OnncJ4
induced.txt: https://pastes.dev/BxqZK5fh7G

**To Reproduce**
Not 100% sure, maybe it has to do with a super big file? The stack trace mentions something being too big

**Expected behavior**
No error

**Plugin version**
212.10.1

**IDE version**
```
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 4, 2022
Licensed to PaperMC / Jake Potrebic
Subscription is active until June 8, 2023.
For non-commercial open source development only.
Runtime version: 17.0.4.1+7-b469.62 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.7.1)
    com.intellij.plugins.expui (0.4)
    com.intellij.ideolog (203.0.30.0)
    com.intellij.properties.bundle.editor (222.4345.14)
    ru.artyushov (1.3.0)
    org.jetbrains.kotlin (222-1.7.21-release-272-IJ4167.29)
    de.u-mass.idea.copyConstructor (1.2)
    com.intellij.guice (222.4345.14)
    org.jetbrains.idea.grammar (2021.1.2)
    com.ifillbrito.immutable (1.0)
    com.github.zzehring.intellijjsonnet (0.0.9)
    com.github.copilot (1.1.35.2063)
    com.dubreuia (2.3.0)
    mobi.hsz.idea.gitignore (4.4.2)
    com.mallowigi (73.0.0)
    org.jetbrains.plugins.vue (222.4345.21)
    com.almightyalpaca.intellij.plugins.discord (1.10.0)
    intellij.prettierJS (222.4345.14)
    Pythonid (222.4345.14)
    Builder Generator (1.3.0)
    ru.adelf.idea.dotenv (2022.2)
    dev.denwav.gradle-libs-error-suppressor (0.1.2)
    zielu.gittoolbox (212.10.1)
    org.intellij.scala (2022.2.17)
    ASM Bytecode Viewer (9.2)

Kotlin: 222-1.7.21-release-272-IJ4167.29
```

**Comment by zielu** [comment]
```
Not disposed

java.io.UTFDataFormatException: encoded string (aSByZWFs...ZSBqbXA=) too long: 266668 bytes
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:369)
	at java.base/java.io.DataOutputStream.writeUTF(DataOutputStream.java:333)
	at zielu.gittoolbox.a.a.a.a.c.a(SourceFile:29)
	at zielu.gittoolbox.a.a.a.a.c.b(SourceFile:35)
	at zielu.gittoolbox.a.a.a.a.c.a(SourceFile:24)
	at zielu.gittoolbox.a.a.a.a.c.save(SourceFile:8)
	at com.intellij.util.io.PersistentMapImpl.doPut(PersistentMapImpl.java:383)
	at com.intellij.util.io.PersistentMapImpl.put(PersistentMapImpl.java:365)
	at com.intellij.util.io.PersistentHashMap.put(PersistentHashMap.java:93)
	at zielu.gittoolbox.a.a.a.b.a(SourceFile:82)
	at zielu.gittoolbox.a.a.f.a(SourceFile:34)
	at zielu.gittoolbox.a.a.d.a(SourceFile:87)
	at zielu.gittoolbox.a.a.d.b(SourceFile:69)
	at zielu.gittoolbox.a.a.d.a(SourceFile:46)
	at zielu.gittoolbox.a.O.a(SourceFile:31)
	at zielu.gittoolbox.a.t.a(SourceFile:215)
	at zielu.gittoolbox.a.t.a(SourceFile:192)
	at zielu.gittoolbox.a.u.a(SourceFile:207)
	at zielu.gittoolbox.a.u.invoke(SourceFile:207)
	at zielu.a.i.a.h.c(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.i.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.m.b(SourceFile:37)
	at zielu.gittoolbox.a.t.run(SourceFile:207)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.gittoolbox.a.j.run(SourceFile:52)
	at zielu.a.k.f.run(SourceFile:130)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.a.d.f.run(SourceFile:70)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by zielu** [comment]
@Machine-Maker I'll take a look - this is related to persistent blame cache. I encode blames to base64 before persisting them so this might be a very long blame message.

**Comment by zielu** [comment]
Note to self: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4039553

**Comment by zielu** [comment]
Done in 213.10.2
