### ISSUE TITLE
[BUG] java.nio.file.NoSuchFileException from blame persistence

### ISSUE THREAD

**Issue by dusanmsk** [zielu/GitToolBox#431]
After purging idea caches and restarting NoSuchFile exception raises

1. Go to File->invalidate caches->and restart
2. Wait to start, reopen project
3. See error

Exact plugin version. Eg. 211.9.9

IntelliJ IDEA 2021.1.3 (Ultimate Edition)
Build #IU-211.7628.21, built on June 30, 2021
Licensed to ***
You have a perpetual fallback license for this version.
Runtime version: 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.0-18-amd64
GC: ParNew, ConcurrentMarkSweep
Memory: 16334M
Cores: 6
Non-Bundled Plugins: Gradle View (4.0.0), com.jetbrains.ChooseRuntime (1.2), com.jetbrains.gerryPurpleTheme (2022.1.28), com.markskelton.one-dark-theme (5.7.0), EclipseCodeFormatter (22.0.203.000.0-Eclipse_2021-09), zielu.gittoolbox (211.9.9), Ivy Plugin (3.6), JFormDesigner-Marketplace-Edition (8), VisualVMLauncher (1.21.211.6085.0), call-graph (0.1.17), com.github.setial (4.0.2), org.dudariev.converter.generator (1.2.0), Spock Framework Enhancements (0.12), org.jetbrains.kotlin (211-1.6.21-release-334-IJ7442.40), com.haulmont.jpab (5.10-211), Pythonid (211.7628.24), net.ashald.envfile (3.4.1), org.asciidoctor.intellij.asciidoc (0.33.21)
Kotlin: 211-1.6.21-release-334-IJ7442.40
Current Desktop: KDE

**Screenshots**
```
real size = 4096

java.nio.file.NoSuchFileException: /home/msk/.cache/JetBrains/IntelliJIdea2021.1/projects/korunka-backend-parent.69afe958/gittoolbox/blame-details/details.db.len
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
	at java.base/java.nio.file.Files.newInputStream(Files.java:156)
	at com.intellij.util.io.ResizeableMappedFile.readLength(ResizeableMappedFile.java:178)
	at com.intellij.util.io.ResizeableMappedFile.<init>(ResizeableMappedFile.java:66)
	at com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:73)
	at com.intellij.util.io.PersistentEnumerator.createDefaultEnumerator(PersistentEnumerator.java:65)
	at com.intellij.util.io.PersistentMapImpl.<init>(PersistentMapImpl.java:131)
	at com.intellij.util.io.PersistentMapBuilder.buildImplementation(PersistentMapBuilder.java:64)
	at com.intellij.util.io.PersistentMapBuilder.build(PersistentMapBuilder.java:41)
	at zielu.gittoolbox.a.a.a.c.a(SourceFile:53)
	at zielu.gittoolbox.a.a.a.c.invoke(SourceFile:42)
	at zielu.a.j.a.a(SourceFile:20)
	at zielu.gittoolbox.a.a.a.b.<init>(SourceFile:55)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:742)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:699)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:592)
	at com.intellij.serviceContainer.ComponentManagerImpl.getLightService$intellij_platform_serviceContainer(ComponentManagerImpl.kt:566)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:478)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:471)
	at zielu.gittoolbox.C.a.b(SourceFile:20)
	at zielu.gittoolbox.a.a.a.e.a(SourceFile:132)
	at zielu.gittoolbox.a.a.a.g.a(SourceFile:14)
	at zielu.gittoolbox.a.a.g.a(SourceFile:29)
	at zielu.gittoolbox.a.a.g.invoke(SourceFile:28)
	at zielu.a.i.a.e.c(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.i.a.e.a(SourceFile:10)
	at zielu.gittoolbox.a.a.f.a(SourceFile:28)
	at zielu.gittoolbox.a.a.d.a(SourceFile:79)
	at zielu.gittoolbox.a.a.d.b(SourceFile:69)
	at zielu.gittoolbox.a.a.d.a(SourceFile:44)
	at zielu.gittoolbox.a.L.a(SourceFile:30)
	at zielu.gittoolbox.a.s.a(SourceFile:212)
	at zielu.gittoolbox.a.s.a(SourceFile:188)
	at zielu.gittoolbox.a.t.a(SourceFile:203)
	at zielu.gittoolbox.a.t.invoke(SourceFile:203)
	at zielu.a.i.a.e.c(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.i.a.e.a(SourceFile:10)
	at zielu.gittoolbox.a.l.b(SourceFile:36)
	at zielu.gittoolbox.a.s.run(SourceFile:203)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.o.a(SourceFile:21)
	at zielu.a.b.o.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.l.run(SourceFile:18)
	at zielu.gittoolbox.a.i.run(SourceFile:52)
	at zielu.a.k.f.run(SourceFile:130)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.o.a(SourceFile:21)
	at zielu.a.b.o.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.l.run(SourceFile:18)
	at zielu.a.d.f.run(SourceFile:70)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.o.a(SourceFile:21)
	at zielu.a.b.o.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.l.run(SourceFile:18)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by zielu** [comment]
On it

**Comment by zielu** [comment]
Done in 213.10.2 - as 2021.3 is minimum supported version as a workaround for 2021.1 you can do the following:

1. Open `Help > Find Actions... > Registry...`
2. Find key `zielu.gittoolbox.blame.cache.persistent` and set is to `false`
