### ISSUE TITLE
NPE when opening Affected Files. [BUG]

### ISSUE THREAD

**Issue by rafaelsampaiounicid** [zielu/GitToolBox#436]
**Describe the bug**
Null Pointer Exception Throw when openning "Affected Files". It happens only once, the second time I tried to reproduce it wont happen.

**To Reproduce**
1. Place cursor on a uncommited line
2. Click on blame on statusbar 
![image](https://user-images.githubusercontent.com/120390038/207058909-86a9f4c6-5a1b-4813-9c28-631f978533de.png)
3. Click on 'Affected Files' 
![image](https://user-images.githubusercontent.com/120390038/207059455-aba96c4d-c269-4d7f-a6f8-150c0e617bc3.png)
4. Get the error 
![image](https://user-images.githubusercontent.com/120390038/207058264-1249ebb5-9b59-4db0-83e2-250f71273bde.png)

**Expected behavior**
The IDE display the changed lines.

**Plugin version**
213.10.2

**IDE version**
IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

    

**Error message**
```
java.lang.Throwable: Unsupported revision number: NULL
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at git4idea.changes.GitCommittedChangeListProvider.getOneList(GitCommittedChangeListProvider.java:158)
	at zielu.gittoolbox.E.c.D.a(SourceFile:203)
	at zielu.gittoolbox.E.c.D.a(SourceFile:193)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Screenshots**
![image](https://user-images.githubusercontent.com/120390038/207058264-1249ebb5-9b59-4db0-83e2-250f71273bde.png)

**Comment by zielu** [comment]
Hi, I'll look into this

**Comment by zielu** [comment]
Done in 213.10.4
