### ISSUE TITLE
[BUG] Exception in plugin GitToolBox (213.10.5)

### ISSUE THREAD

**Issue by mfrattola** [zielu/GitToolBox#440]
**Describe the bug**
I was loading a new project and this exception came up, saying I should report it to you

Not disposed

com.intellij.util.IncorrectOperationException: Sorry but parent: zielu.gittoolbox.a.m@19aa7741 (class zielu.gittoolbox.a.m) has already been disposed (see the cause for stacktrace) so the child: DisposableWrapper[task=Kt[task=Function0<kotlin.Unit>, active=$true]] (class zielu.a.b.j) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:143)
	at zielu.gittoolbox.F.d.a(SourceFile:11)
	at zielu.gittoolbox.F.x.b(SourceFile:35)
	at zielu.gittoolbox.a.m.a(SourceFile:50)
	at zielu.gittoolbox.a.s.a(SourceFile:108)
	at zielu.gittoolbox.a.s.a(SourceFile:24)
	at zielu.gittoolbox.a.E.a(SourceFile:95)
	at zielu.gittoolbox.a.E.invoke(SourceFile:95)
	at zielu.gittoolbox.a.t.run(SourceFile:206)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.gittoolbox.a.j.run(SourceFile:52)
	at zielu.a.k.f.run(SourceFile:130)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.a.d.f.run(SourceFile:70)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**To Reproduce**
No idea.

**Expected behavior**
No idea.

**Plugin version**
213.10.5

**IDE version**
PhpStorm 2022.3.1
Build #PS-223.8214.64, built on December 22, 2022
Licensed to Marco Frattola
You have a perpetual fallback license for this version.
Subscription is active until September 30, 2025.
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1000M
Cores: 8
Registry:
    run.processes.with.pty=TRUE

Non-Bundled Plugins:
    com.dimabdc.idea.php.phpunit (0.5.1)
    zielu.gittoolbox (213.10.5)

**Screenshots**

**Comment by zielu** [comment]
Related to how threading is implemented, will be fixed in #445
