### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by qkrtkdwns3410** [zielu/GitToolBox#442]
**Describe the bug**

**To Reproduce**
---

![image](https://user-images.githubusercontent.com/80584060/210486001-23aadbb1-e5ed-41d4-b606-b35cae8e6b8a.png)

Not disposed

java.io.IOException: readPrevChunkAddress:44,114,74556,C:\Users\ipeac\AppData\Local\JetBrains\IntelliJIdea2021.2\projects\alioilioalgo.2d33d17d\gittoolbox\blame-details\details.db.values
	at com.intellij.util.io.PersistentHashMapValueStorage.readPrevChunkAddress(PersistentHashMapValueStorage.java:655)
	at com.intellij.util.io.PersistentHashMapValueStorage.readBytes(PersistentHashMapValueStorage.java:546)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:580)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:521)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:209)
	at zielu.gittoolbox.a.a.a.b.a(SourceFile:93)
	at zielu.gittoolbox.a.a.g.a(SourceFile:29)
	at zielu.gittoolbox.a.a.g.invoke(SourceFile:28)
	at zielu.a.i.a.h.c(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.i.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.a.f.a(SourceFile:28)
	at zielu.gittoolbox.a.a.d.a(SourceFile:77)
	at zielu.gittoolbox.a.a.d.b(SourceFile:63)
	at zielu.gittoolbox.a.a.d.a(SourceFile:46)
	at zielu.gittoolbox.a.O.a(SourceFile:31)
	at zielu.gittoolbox.a.t.a(SourceFile:215)
	at zielu.gittoolbox.a.t.a(SourceFile:192)
	at zielu.gittoolbox.a.u.a(SourceFile:207)
	at zielu.gittoolbox.a.u.invoke(SourceFile:207)
	at zielu.a.i.a.h.c(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.i.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.m.b(SourceFile:37)
	at zielu.gittoolbox.a.t.run(SourceFile:207)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.gittoolbox.a.j.run(SourceFile:52)
	at zielu.a.k.f.run(SourceFile:130)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.a.d.f.run(SourceFile:70)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

---
**Expected behavior**

**Plugin version**
Exact plugin version. Eg. 212.8.4

**IDE version**
Exact IDE and OS. You can use About > Copy 

**Screenshots**

**Comment by qkrtkdwns3410** [comment]
plugin version 212.10.1
intellij ultimate 2021.2.4 build #IU-212.5712.43

**Comment by zielu** [comment]
Hi, 212.x is not really supported anymore. If going to newer IDE version is not an option as a workaround you can disable blame cache persistence.
1. `Help > Find action > Registry`
2. Find `zielu.gittoolbox.blame.cache.persistent` and disable it - restart is needed

**Comment by qkrtkdwns3410** [comment]
thanks!
