### ISSUE TITLE
Commit completion based on current branch

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#45]
Use-case: I use gitflow and want to be able to insert issue number (or some part of branch name) into commit message.

**Comment by zielu** [comment]
Exception in 2017.3 EAP
```
null
java.lang.NullPointerException
	at git4idea.GitUtil.sortFilesByGitRoot(GitUtil.java:236)
	at git4idea.GitUtil.sortFilesByGitRootsIgnoringOthers(GitUtil.java:839)
	at git4idea.GitUtil.getRepositoriesForFiles(GitUtil.java:832)
	at zielu.gittoolbox.completion.GitToolBoxCompletionProject.getRepositories(GitToolBoxCompletionProject.java:52)
	at zielu.gittoolbox.completion.GitToolBoxCompletionProject.getAffected(GitToolBoxCompletionProject.java:44)
	at zielu.gittoolbox.completion.CurrentBranchCompletionContributor$Completer.getBranchInfo(CurrentBranchCompletionContributor.java:53)
	at zielu.gittoolbox.completion.CurrentBranchCompletionContributor$Completer.addCompletions(CurrentBranchCompletionContributor.java:36)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
```

**Comment by zielu** [comment]
Exception in 2017.2.5

`Argument for @NotNull parameter 'file' of com/intellij/openapi/vfs/VfsUtilCore.isAncestor must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'file' of com/intellij/openapi/vfs/VfsUtilCore.isAncestor must not be null
	at com.intellij.openapi.vfs.VfsUtilCore.isAncestor(VfsUtilCore.java)
	at zielu.gittoolbox.compat.GitCompatUtil$GitRepoInfo.isFileInRepo(GitCompatUtil.java:36)
	at zielu.gittoolbox.compat.GitCompatUtil.lambda$getRepoFor$2(GitCompatUtil.java:25)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1353)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at zielu.gittoolbox.compat.GitCompatUtil.getRepoFor(GitCompatUtil.java:25)
	at zielu.gittoolbox.compat.GitCompatUtil.lambda$getRepositoriesForFiles$1(GitCompatUtil.java:20)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at zielu.gittoolbox.compat.GitCompatUtil.getRepositoriesForFiles(GitCompatUtil.java:21)
`

**Comment by zielu** [comment]
Update completion list when pattern is edited

**Comment by zielu** [comment]
`null
java.lang.NullPointerException
	at zielu.gittoolbox.completion.GitToolBoxCompletionProject.disposeComponent(GitToolBoxCompletionProject.java:91)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.disposeComponents(ComponentManagerImpl.java:149)
	at com.intellij.openapi.project.impl.ProjectImpl.dispose(ProjectImpl.java:369)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
`

**Comment by zielu** [comment]
In 2017.3 EAP
`com/intellij/ui/components/ValidatingTextField
java.lang.NoClassDefFoundError: com/intellij/ui/components/ValidatingTextField
`

**Comment by zielu** [comment]
Done in 173.1.0
