### ISSUE TITLE
[BUG] Cannot create class zielu.gittoolbox.E.a.f

### ISSUE THREAD

**Issue by BorzdeG** [zielu/GitToolBox#450]
**Describe the bug**
Run GoLand

**To Reproduce**
1. Launching the IDE
2. We see an error on the Welcome Screen
3. Subsequent attempts to open any project cause the IDE to hang

**Plugin version**
213.10.5  with `until-build` tag corrected to "231.*"

**IDE version**
GoLand 2023.1 EAP
Build #GO-231.6351, built on January 29, 2023

**Screenshots**
```
Cannot create listener

com.intellij.diagnostic.PluginException: Cannot create class zielu.gittoolbox.E.a.f (classloader=PluginClassLoader(plugin=PluginDescriptor(name=GitToolBox, id=zielu.gittoolbox, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/Goland/ch-1/231.6351/GoLand 2023.1 EAP.app.plugins/gittoolbox, version=213.10.5, package=null, isBundled=false), packagePrefix=null, instanceId=135, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1022)
	at com.intellij.serviceContainer.ComponentManagerImpl.createListener(ComponentManagerImpl.kt:1060)
	at com.intellij.util.messages.impl.CompositeMessageBus.subscribeLazyListeners$lambda$3(CompositeMessageBus.kt:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at com.intellij.util.messages.impl.CompositeMessageBus.subscribeLazyListeners(CompositeMessageBus.kt:111)
	at com.intellij.util.messages.impl.CompositeMessageBus.doComputeSubscribers$intellij_platform_core(CompositeMessageBus.kt:92)
	at com.intellij.util.messages.impl.MessageBusImpl.computeSubscribers$intellij_platform_core(MessageBusImpl.kt:210)
	at com.intellij.util.messages.impl.CompositeMessageBus.computeSubscribers$intellij_platform_core(CompositeMessageBus.kt:87)
	at com.intellij.util.messages.impl.MessagePublisher$publish$handlers$1.invoke(MessageBusImpl.kt:460)
	at com.intellij.util.messages.impl.MessagePublisher$publish$handlers$1.invoke(MessageBusImpl.kt:460)
	at com.intellij.util.messages.impl.MessagePublisher.publish$lambda$0(MessageBusImpl.kt:460)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.util.messages.impl.MessagePublisher.publish$intellij_platform_core(MessageBusImpl.kt:460)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:451)
	at jdk.proxy1/jdk.proxy1.$Proxy54.applicationActivated(Unknown Source)
	at com.intellij.ide.ApplicationActivationStateManager.setActive(ApplicationActivationStateManager.java:101)
	at com.intellij.ide.ApplicationActivationStateManager.updateState(ApplicationActivationStateManager.java:48)
	at com.intellij.ide.IdeEventQueueKt.processAppActivationEvent(IdeEventQueue.kt:1024)
	at com.intellij.ide.IdeEventQueueKt.access$processAppActivationEvent(IdeEventQueue.kt:1)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:547)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$6$lambda$5$lambda$4(IdeEventQueue.kt:339)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$6$lambda$5(IdeEventQueue.kt:338)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:985)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$6(IdeEventQueue.kt:336)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:824)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:378)
	at java.desktop/java.awt.SentEvent.dispatch(SentEvent.java:75)
	at java.desktop/java.awt.DefaultKeyboardFocusManager$DefaultKeyboardFocusManagerSentEvent.dispatch(DefaultKeyboardFocusManager.java:262)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.sendMessage(DefaultKeyboardFocusManager.java:289)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:439)
	at com.intellij.ide.IdeKeyboardFocusManager.lambda$dispatchEvent$0(IdeKeyboardFocusManager.java:32)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:985)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:32)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/sun.awt.SunToolkit$1.run(SunToolkit.java:516)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:786)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:737)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:659)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$9(IdeEventQueue.kt:563)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1437)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:563)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$6$lambda$5$lambda$4(IdeEventQueue.kt:339)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$6$lambda$5(IdeEventQueue.kt:338)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:985)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$6(IdeEventQueue.kt:336)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:824)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:378)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoClassDefFoundError: zielu/gittoolbox/E/a/g
	at zielu.gittoolbox.E.a.f.<clinit>(SourceFile)
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:520)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:981)
	... 71 more
Caused by: java.lang.ClassNotFoundException: zielu.gittoolbox.E.a.g PluginClassLoader(plugin=PluginDescriptor(name=GitToolBox, id=zielu.gittoolbox, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/Goland/ch-1/231.6351/GoLand 2023.1 EAP.app.plugins/gittoolbox, version=213.10.5, package=null, isBundled=false), packagePrefix=null, instanceId=135, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:237)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 75 more
```

**Comment by zielu** [comment]
You modify stuff on your own, you are on your own

**Comment by BorzdeG** [comment]
Rough. I'm not asking for a fix - just reporting that there is a problem in a future version of the IDE that is causing the IDE to hang.

**Comment by BorzdeG** [comment]
FYI: other plugins that I "enabled" like this do not cause the IDE to freeze.
And yes, I understand the risks very well, since I use nightly and EAP builds of the IDE

**Comment by zielu** [comment]
Done in 500.0.1+213

**Comment by BorzdeG** [comment]
I have already tried - no more errors
