### ISSUE TITLE
Plugin is crashing IntelliJ and WebStorm often

### ISSUE THREAD

**Issue by MikeSuiter** [zielu/GitToolBox#451]
**Describe the bug**
Opening a file crashes IntelliJ and WebStorm

**To Reproduce**
Open a file

**Expected behavior**
Don't crash IDE

**Plugin version**
213.10.5

**IDE version**
```
IntelliJ IDEA 2022.3.2 (Ultimate Edition)
Build #IU-223.8617.56, built on January 26, 2023
Runtime version: 17.0.5+1-b653.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Metal Rendering is ON
Registry:
    editor.focus.mode.color.light=415967
    ide.editor.tab.selection.animation=true
    debugger.new.tool.window.layout=true
    ide.new.editor.tabs.vertical.borders=true
    ide.experimental.ui=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=415967

Non-Bundled Plugins:
    com.intellij.plugins.watcher (223.7571.113)
    com.intellij.kubernetes (223.8617.8)
    com.intellij.guice (223.7571.182)
    mdx.js (223.8214.16)
    org.asciidoctor.intellij.asciidoc (0.38.10)
    Pythonid (223.8617.56)
    com.chrisrm.idea.MaterialThemeUI (8.4.1)
    com.mallowigi (85.1.0)
    zielu.gittoolbox (213.10.5)
    mobi.hsz.idea.gitignore (4.4.4)
    com.intellij.plugins.html.instantEditing (223.8214.16)

Kotlin: 223-1.8.0-release-345-IJ8617.56
```

**ERROR**
```
Not disposed

com.intellij.diagnostic.PluginException: Positive width should be defined for an after-line-end element by zielu.gittoolbox.E.c.a.a.d@40004ed4 [Plugin: zielu.gittoolbox]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.openapi.editor.impl.AfterLineEndInlayImpl.doUpdate(AfterLineEndInlayImpl.java:42)
	at com.intellij.openapi.editor.impl.InlayImpl.<init>(InlayImpl.java:35)
	at com.intellij.openapi.editor.impl.AfterLineEndInlayImpl.<init>(AfterLineEndInlayImpl.java:26)
	at com.intellij.openapi.editor.impl.InlayModelImpl.addAfterLineEndElement(InlayModelImpl.java:221)
	at com.intellij.openapi.editor.impl.InlayModelImpl.addAfterLineEndElement(InlayModelImpl.java:208)
	at zielu.gittoolbox.E.c.a.a.c.a(SourceFile:35)
	at zielu.gittoolbox.E.c.d.a(SourceFile:170)
	at zielu.gittoolbox.E.c.d.a(SourceFile:118)
	at zielu.gittoolbox.E.c.d.a(SourceFile:96)
	at zielu.gittoolbox.E.c.d.a(SourceFile:161)
	at zielu.gittoolbox.E.c.d.a(SourceFile:155)
	at zielu.gittoolbox.E.c.d.b(SourceFile:152)
	at zielu.gittoolbox.E.c.b.a(SourceFile:57)
	at zielu.gittoolbox.E.c.s.a(SourceFile:73)
	at zielu.gittoolbox.E.c.s.invoke(SourceFile:67)
	at zielu.a.b.l.run(SourceFile:49)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:454)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:838)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by zielu** [comment]
Hi, I'll take a look.

**Comment by zielu** [comment]
Might be related to truncation of blame to editor size, as a workaround you could disable
`Settings > Version Control > GitToolBox > Blame > Shorted to fit editor`

**Comment by zielu** [comment]
Done in 500.0.2+213
