### ISSUE TITLE
[BUG] Plugin error

### ISSUE THREAD

**Issue by 573183869** [zielu/GitToolBox#460]
Not disposed

com.intellij.util.IncorrectOperationException: Sorry but parent: zielu.gittoolbox.a.m@235d9ac (class zielu.gittoolbox.a.m) has already been disposed (see the cause for stacktrace) so the child: DisposableWrapper[task=Kt[task=Function0<kotlin.Unit>, active=$true]] (class zielu.a.b.j) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:143)
	at zielu.gittoolbox.G.d.a(SourceFile:11)
	at zielu.gittoolbox.G.x.b(SourceFile:35)
	at zielu.gittoolbox.a.m.a(SourceFile:50)
	at zielu.gittoolbox.a.s.a(SourceFile:112)
	at zielu.gittoolbox.a.s.a(SourceFile:24)
	at zielu.gittoolbox.a.E.a(SourceFile:99)
	at zielu.gittoolbox.a.E.invoke(SourceFile:99)
	at zielu.gittoolbox.a.t.run(SourceFile:210)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.gittoolbox.a.j.run(SourceFile:52)
	at zielu.a.l.f.run(SourceFile:130)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.a.e.f.run(SourceFile:70)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zielu** [comment]
Related to #445, will handle it there.
