### ISSUE TITLE
NullPointerException: Not disposed

### ISSUE THREAD

**Issue by petr-nehez** [zielu/GitToolBox#462]
No idea how it occurred, just reopened a project...

```
Not disposed

java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at git4idea.GitVcs.getInstance(GitVcs.java:82)
	at git4idea.commands.GitHandler.<init>(GitHandler.java:141)
	at git4idea.commands.GitHandler.<init>(GitHandler.java:89)
	at git4idea.commands.GitHandler.<init>(GitHandler.java:107)
	at git4idea.commands.GitTextHandler.<init>(GitTextHandler.java:45)
	at git4idea.commands.GitLineHandler.<init>(GitLineHandler.java:56)
	at zielu.gittoolbox.a.a.b.a(SourceFile:19)
	at zielu.gittoolbox.a.a.q.a(SourceFile:72)
	at zielu.gittoolbox.a.a.q.b(SourceFile:44)
	at zielu.gittoolbox.a.a.q.a(SourceFile:28)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.j.a.h.a(SourceFile:14)
	at zielu.gittoolbox.a.a.q.a(SourceFile:27)
	at zielu.gittoolbox.a.a.d.b(SourceFile:67)
	at zielu.gittoolbox.a.a.d.a(SourceFile:47)
	at zielu.gittoolbox.a.L.a(SourceFile:31)
	at zielu.gittoolbox.a.t.a(SourceFile:215)
	at zielu.gittoolbox.a.t.a(SourceFile:192)
	at zielu.gittoolbox.a.u.a(SourceFile:207)
	at zielu.gittoolbox.a.u.invoke(SourceFile:207)
	at zielu.a.j.a.h.b(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.j.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.m.a(SourceFile:37)
	at zielu.gittoolbox.a.t.run(SourceFile:207)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.gittoolbox.a.j.run(SourceFile:52)
	at zielu.a.l.f.run(SourceFile:130)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.a.e.f.run(SourceFile:70)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Version: `500.0.4+213`

**Comment by zielu** [comment]
Aah another one of those - it is on top of my priority list. It is annoying but does not break anything. Exception is coming from project being closed.

**Comment by zielu** [comment]
Will be handled in #445
