### ISSUE TITLE
[BUG] NoSuchElementException

### ISSUE THREAD

**Issue by Romen-Geng** [zielu/GitToolBox#465]
**Describe the bug**
When i use IDEA  with plugin GitToolBox(212.10.1),then i get a error like this.

---------------------
Not disposed

java.util.NoSuchElementException
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$EntryIterator.nextKey(BoundedLocalCache.java:3479)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$KeyIterator.next(BoundedLocalCache.java:3150)
	at kotlin.collections.CollectionsKt___CollectionsKt.toSet(_Collections.kt:1347)
	at zielu.gittoolbox.a.s.i(SourceFile:120)
	at zielu.gittoolbox.a.s.b(SourceFile:24)
	at zielu.gittoolbox.a.E.a(SourceFile:114)
	at zielu.gittoolbox.a.E.invoke(SourceFile:113)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.gittoolbox.a.s.b(SourceFile:113)
	at zielu.gittoolbox.a.ad.a(SourceFile:14)
	at zielu.gittoolbox.a.ag.a(SourceFile:25)
	at zielu.gittoolbox.c.au.a(SourceFile:7)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeMethod(MessageBusImpl.java:645)
	at com.intellij.util.messages.impl.MessageBusImpl.invokeListener(MessageBusImpl.java:620)
	at com.intellij.util.messages.impl.MessageBusImpl.deliverMessage(MessageBusImpl.java:417)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:390)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:33)
	at com.intellij.util.messages.impl.MessageBusImpl$MessagePublisher.invoke(MessageBusImpl.java:179)
	at com.sun.proxy.$Proxy142.a(Unknown Source)
	at zielu.gittoolbox.c.Q.a(SourceFile:125)
	at zielu.gittoolbox.c.Q.invoke(SourceFile:124)
	at zielu.gittoolbox.F.y.a(SourceFile:33)
	at zielu.gittoolbox.F.y.invoke(SourceFile:33)
	at zielu.a.b.l.run(SourceFile:49)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
-----------------------------------
**Plugin version**
GitToolBox(212.10.1)

**IDE version**
IntelliJ IDEA 2021.2.3(UItimate Edition)

**Comment by zielu** [comment]
Hi, 212.* is not really supported anymore, but I'll take a look, if fix it trivial I'll do a backport. I'll keep you posted.

**Comment by zielu** [comment]
I'll create a build with a fix.
