### ISSUE TITLE
Exception for file size (32016)

### ISSUE THREAD

**Issue by tanryberdi** [zielu/GitToolBox#472]
This exception from Goland :

storage size = 32016, file size = 32016

java.nio.file.NoSuchFileException: /Users/tanryberdi/Library/Caches/JetBrains/GoLand2023.1/projects/svi-services.401d2d/gittoolbox/blame-details/details.db_i.len
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:422)
	at java.base/java.nio.file.Files.newInputStream(Files.java:160)
	at com.intellij.util.io.ResizeableMappedFile.readLength(ResizeableMappedFile.java:200)
	at com.intellij.util.io.ResizeableMappedFile.<init>(ResizeableMappedFile.java:72)
	at com.intellij.util.io.IntToIntBtree.<init>(IntToIntBtree.java:60)
	at com.intellij.util.io.PersistentBTreeEnumerator.initBtree(PersistentBTreeEnumerator.java:278)
	at com.intellij.util.io.PersistentBTreeEnumerator.<init>(PersistentBTreeEnumerator.java:144)
	at com.intellij.util.io.PersistentEnumerator.createDefaultEnumerator(PersistentEnumerator.java:68)
	at com.intellij.util.io.PersistentMapImpl.<init>(PersistentMapImpl.java:163)
	at com.intellij.util.io.PersistentMapBuilder.buildImplementation(PersistentMapBuilder.java:90)
	at com.intellij.util.io.PersistentMapBuilder.build(PersistentMapBuilder.java:72)
	at zielu.gittoolbox.a.a.a.c.a(SourceFile:55)
	at zielu.gittoolbox.a.a.a.c.invoke(SourceFile:44)
	at zielu.a.k.a.a(SourceFile:20)
	at zielu.gittoolbox.a.a.a.b.<init>(SourceFile:57)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1007)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:970)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:774)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:726)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:670)
	at zielu.gittoolbox.G.a.b(SourceFile:20)
	at zielu.gittoolbox.a.a.a.e.a(SourceFile:135)
	at zielu.gittoolbox.a.a.a.h.a(SourceFile:14)
	at zielu.gittoolbox.a.a.g.a(SourceFile:29)
	at zielu.gittoolbox.a.a.g.invoke(SourceFile:28)
	at zielu.a.j.a.h.b(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.j.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.a.f.a(SourceFile:28)
	at zielu.gittoolbox.a.a.d.a(SourceFile:79)
	at zielu.gittoolbox.a.a.d.b(SourceFile:64)
	at zielu.gittoolbox.a.a.d.a(SourceFile:47)
	at zielu.gittoolbox.a.L.a(SourceFile:31)
	at zielu.gittoolbox.a.t.a(SourceFile:215)
	at zielu.gittoolbox.a.t.a(SourceFile:192)
	at zielu.gittoolbox.a.u.a(SourceFile:207)
	at zielu.gittoolbox.a.u.invoke(SourceFile:207)
	at zielu.a.j.a.h.b(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.j.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.m.a(SourceFile:37)
	at zielu.gittoolbox.a.t.run(SourceFile:207)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.gittoolbox.a.j.run(SourceFile:52)
	at zielu.a.l.f.run(SourceFile:130)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.a.e.f.run(SourceFile:70)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zielu** [comment]
Hi, which plugin version are you using ?

**Comment by tanryberdi** [comment]
Hi, @zielu, for my it was version 500.0.6+213

**Comment by zielu** [comment]
Hi, I investigated this and while error is shown there is nothing wrong. This is caused by cache persistence I'm using (comes with IDE), cache corruption is handled and cache is recreated, but I cannot suppress this message.

I was going to use another storage solution anyway so let's keep this issue open for reference until I implement it.

**Comment by aqeelat** [comment]
@zielu any updates on the new storage solution? The plugin currently makes git operations slow. Please look at https://youtrack.jetbrains.com/issue/IDEA-324747 for more information. If you comment there, I will give you access to the attachments in the ticket.

**Comment by zielu** [comment]
Hi @aqeelat please do share them. For new storage I only need to add cleanup of expired entries, otherwise it's working fine. Also which other git-related plugins you have installed ?

**Comment by zielu** [comment]
Done in 500.0.14+222
