### ISSUE TITLE
[BUG] com.intellij.util.IncorrectOperationException: Sorry but parent

### ISSUE THREAD

**Issue by petr-nehez** [zielu/GitToolBox#474]
**Describe the bug**
IDEA started with select project dialog only...

**To Reproduce**
No idea :(

**Plugin version**
500.0.5+213

**IDE version**
```
IntelliJ IDEA 2022.3.2 (Ultimate Edition)
Build #IU-223.8617.56, built on January 26, 2023
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 10504M
Cores: 12
Registry:
    editor.focus.mode.color.light=a2a2a2
    ide.editor.tab.selection.animation=true
    documentation.show.toolbar=true
    ide.new.editor.tabs.vertical.borders=true
    ide.balloon.shadow.size=0
    editor.focus.mode.color.dark=a2a2a2
    ide.images.show.chessboard=true
    majera.code.review.bitbucket.disable.gpu.in.jcef=false
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.jetbrains.CyanTheme (1.3)
    com.wakatime.intellij.plugin (14.1.4)
    org.dandoh.favacts (0.0.3)
    com.intellij.plugins.macoskeymap (223.7571.117)
    rasarts.espresso.light.theme (1.2.0)
    name.kropp.intellij.makefile (223.8214.6)
    com.github.today-.theme.spaceday (1.12)
    lermitage.intellij.iconviewer (1.20.0)
    org.turbanov.run.configuration.as.action (1.4.5)
    Batch Scripts Support (1.0.13)
    com.intellij.plugins.watcher (223.7571.113)
    com.mallowigi (85.1.0)
    ski.chrzanow.foldableprojectview (1.1.4)
    com.intellij.plugins.xwinkeymap (211.4961.30)
    net.seesharpsoft.intellij.plugins.file-preview (1.6.4)
    com.intellij.javafx (1.0.4)
    lermitage.intellij.extra.icons (2023.1.2)
    org.rust.lang (0.4.191.5293-223)
    zielu.cleansheet (211.3.3)
    com.tabnine.TabNine (1.0.6)
    com.layoutmanager (1.4.0)
    com.intellij.properties.bundle.editor (223.7571.203)
    com.wix.sasslint (1.1.2)
    varme.pw.oceanic-dark-theme (1.1.6)
    com.khmelyuk.multirun (1.13)
    Key Promoter X (2023.1.0)
    PsiViewer (2022.3)
    hunspell (223.8214.24)
    mobi.hsz.idea.gitignore (4.4.4)
    de.ehmkah.projects.imgdiff (1.11.0)
    ch.raffael.idea.plugins.runpopup (1.3.0)
    com.intellij.nativeDebug (223.8617.8)
    VisualVMLauncher (1.21.211.6085.0)
    CheckStyle-IDEA (5.78.0)
    JFormDesigner-Marketplace-Edition (8.0.3)
    GrepConsole (12.16.211.6693.0)
    String Manipulation (9.7.1)
    com.github.setial (4.0.2)
    EclipseCodeFormatter (22.0.203.000.0-Eclipse_2021-09)
    com.github.beansoftapp.visualgc.plugin (2022.1.0)
    org.sonarlint.idea (8.1.0.65508)
    com.jetbrains.jax.ws (223.8214.16)
    com.intellij.plugins.gnomekeymap (213.4250.391)
    net.seesharpsoft.intellij.plugins.csv (3.1.0-223)
    com.intellij.javaee.ejb (223.7571.182)
    com.majera.intellij.codereview.bitbucket (2023.2.0.223)
    com.intellij.aqua.selenium (223.8617.27)
    com.intellij.selenium (223.7571.117)
    com.intellij.plugins.html.instantEditing (223.8214.16)
    com.intellij.ideolog (203.0.30.0)
    izhangzhihao.rainbow.brackets (2023.2.6)
    pro.bashsupport (3.2.1.223)
    com.chrisrm.idea.MaterialThemeUI (8.4.1)
    zielu.gittoolbox (500.0.5+213)
    com.haulmont.jpab (2023.1.3-223)
    com.intellij.bigdatatools (223.8617.9)
    de.santiv.fastscrolling (1.2)

Kotlin: 223-1.8.0-release-345-IJ8617.56
```

```
Not disposed

com.intellij.util.IncorrectOperationException: Sorry but parent: zielu.gittoolbox.a.m@6adecaab (class zielu.gittoolbox.a.m) has already been disposed (see the cause for stacktrace) so the child: DisposableWrapper[task=Kt[task=Function0<kotlin.Unit>, active=$true]] (class zielu.a.b.j) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:143)
	at zielu.gittoolbox.G.d.a(SourceFile:11)
	at zielu.gittoolbox.G.x.b(SourceFile:35)
	at zielu.gittoolbox.a.m.a(SourceFile:50)
	at zielu.gittoolbox.a.s.a(SourceFile:112)
	at zielu.gittoolbox.a.s.a(SourceFile:24)
	at zielu.gittoolbox.a.E.a(SourceFile:99)
	at zielu.gittoolbox.a.E.invoke(SourceFile:99)
	at zielu.gittoolbox.a.t.run(SourceFile:210)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.gittoolbox.a.j.run(SourceFile:52)
	at zielu.a.l.f.run(SourceFile:130)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.a.e.f.run(SourceFile:70)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by zielu** [comment]
Hi, related to #445. New threading is almost complete.
