### ISSUE TITLE
[BUG] com.intellij.util.io.CorruptedException: Storage corrupted

### ISSUE THREAD

**Issue by javasgl** [zielu/GitToolBox#476]
**Describe the bug**
IDE Internal Errors shows `com.intellij.util.io.CorruptedException: Storage corrupted`

**To Reproduce**
Occasionally appear

**Expected behavior**
None errors shows up

**Plugin version**
500.0.6+213

**IDE version**
IntelliJ IDEA 2023.1 (Ultimate Edition)
Build #IU-231.8109.175, built on March 28, 2023
Licensed to XXX
Subscription is active until August 1, 2025.
Runtime version: 17.0.6+10-b829.5 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Registry:
    documentation.show.toolbar=true
    search.everywhere.settings=true
    ide.tooltip.initialDelay=900
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (231.8109.217)
    com.intellij.plugins.watcher (231.8109.91)
    org.jetbrains.plugins.go-template (231.8109.91)
    org.jetbrains.plugins.go (231.8109.175)
    com.jetbrains.php (231.8109.199)
    com.shuzijun.markdown-editor (2.0.5)
    me.ihxq.acejump.lite (1.2)
    com.wakatime.intellij.plugin (14.1.4)
    name.kropp.intellij.makefile (231.8109.91)
    IDEA Restart (1.0)
    com.vexus2.intellij.openingithub (1.0.6)
    pro.bashsupport (3.2.2.231)
    HighlightBracketPair (1.3.9)
    IdeaVIM (2.2.0)
    zielu.gittoolbox (500.0.6+213)
    Pythonid (231.8109.175)
    org.coffeescript (231.8109.91)

Kotlin: 231-1.8.20-IJ8109.175

**Screenshots**
![image](https://user-images.githubusercontent.com/5222868/234487278-d91f5435-0af8-42ac-a997-cd4c994ae01a.png)

```
com.intellij.util.io.CorruptedException: Storage corrupted /Users/username/Library/Caches/JetBrains/IntelliJIdea2023.1/vcs-log/trade_ecf93624_8163cfc0/hashes/storage.8_i
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.locate(IntToIntBtree.java:889)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.access$100(IntToIntBtree.java:303)
	at com.intellij.util.io.IntToIntBtree.get(IntToIntBtree.java:179)
	at com.intellij.util.io.PersistentBTreeEnumerator.enumerateImpl(PersistentBTreeEnumerator.java:544)
	at com.intellij.util.io.PersistentEnumeratorBase.lambda$doEnumerate$0(PersistentEnumeratorBase.java:260)
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:621)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:259)
	at com.intellij.util.io.PersistentEnumeratorBase.enumerate(PersistentEnumeratorBase.java:272)
	at com.intellij.vcs.log.data.VcsLogStorageImpl.getOrPut(VcsLogStorageImpl.java:93)
	at com.intellij.vcs.log.data.VcsLogStorageImpl.getCommitIndex(VcsLogStorageImpl.java:100)
	at com.intellij.vcs.log.data.VcsLogData.getCommitIndex(VcsLogData.java:265)
	at zielu.gittoolbox.y.e.a(SourceFile:19)
	at zielu.gittoolbox.b.A.a(SourceFile:24)
	at zielu.gittoolbox.b.P.a(SourceFile:44)
	at zielu.gittoolbox.b.P.a(SourceFile:38)
	at zielu.gittoolbox.b.y.run(SourceFile:35)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by zielu** [comment]
Hi, related to #472. Error is handled, but nothing I can do for now to suppress the popup.

**Comment by javasgl** [comment]
got
