### ISSUE TITLE
[BUG]Not disposed

### ISSUE THREAD

**Issue by Everglow1030** [zielu/GitToolBox#484]
**Describe the bug**
When i use IDEA with plugin GitToolBox(212.10.1),then i get a error like this.

Not disposed
java.io.IOException: java.lang.IndexOutOfBoundsException
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:278)
	at com.intellij.util.io.PersistentEnumeratorBase.enumerate(PersistentEnumeratorBase.java:290)
	at com.intellij.util.io.PersistentMapImpl.enumerate(PersistentMapImpl.java:404)
	at com.intellij.util.io.PersistentMapImpl.doPut(PersistentMapImpl.java:377)
	at com.intellij.util.io.PersistentMapImpl.put(PersistentMapImpl.java:339)
	at com.intellij.util.io.PersistentHashMap.put(PersistentHashMap.java:136)
	at zielu.gittoolbox.a.a.a.b.a(SourceFile:95)
	at zielu.gittoolbox.a.a.g.a(SourceFile:29)
	at zielu.gittoolbox.a.a.g.invoke(SourceFile:28)
	at zielu.a.i.a.h.c(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.i.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.a.f.a(SourceFile:28)
	at zielu.gittoolbox.a.a.d.a(SourceFile:77)
	at zielu.gittoolbox.a.a.d.b(SourceFile:63)
	at zielu.gittoolbox.a.a.d.a(SourceFile:46)
	at zielu.gittoolbox.a.O.a(SourceFile:31)
	at zielu.gittoolbox.a.t.a(SourceFile:215)
	at zielu.gittoolbox.a.t.a(SourceFile:192)
	at zielu.gittoolbox.a.u.a(SourceFile:207)
	at zielu.gittoolbox.a.u.invoke(SourceFile:207)
	at zielu.a.i.a.h.c(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.i.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.m.b(SourceFile:37)
	at zielu.gittoolbox.a.t.run(SourceFile:207)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.gittoolbox.a.j.run(SourceFile:52)
	at zielu.a.k.f.run(SourceFile:130)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.a.d.f.run(SourceFile:70)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IndexOutOfBoundsException
	at java.base/java.nio.Buffer.checkIndex(Buffer.java:693)
	at java.base/java.nio.DirectByteBuffer.getInt(DirectByteBuffer.java:758)
	at com.intellij.util.io.DirectBufferWrapper.getInt(DirectBufferWrapper.java:75)
	at com.intellij.util.io.IntToIntBtree$BtreePage.syncWithStore(IntToIntBtree.java:327)
	at com.intellij.util.io.IntToIntBtree$BtreePage.setAddress(IntToIntBtree.java:315)
	at com.intellij.util.io.IntToIntBtree$BtreeIndexNodeView.initTraversal(IntToIntBtree.java:536)
	at com.intellij.util.io.IntToIntBtree.get(IntToIntBtree.java:194)
	at com.intellij.util.io.PersistentBTreeEnumerator.enumerateImpl(PersistentBTreeEnumerator.java:408)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:268)
	... 48 more

**Plugin version**
212.10.1

**IDE version**
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
到期日期: July 7, 2023
运行时版本: 11.0.12+7-b1504.40 aarch64
VM: OpenJDK 64-Bit Server VM，JetBrains s.r.o.
macOS 13.1
GC: G1 Young Generation, G1 Old Generation
Memory: 24576M
Cores: 10
Registry: documentation.show.toolbar=true
Non-Bundled Plugins: com.samdark.intellij-visual-studio-code-dark-plus (2.7), IdeaVIM (1.9.2), com.github.copilot (1.2.8.2631), com.nasller.CodeGlancePro (1.3.8-Last2021.3.x), de.netnexus.camelcaseplugin (3.0.12), com.intellij.zh (212.325), com.codeium.intellij (1.2.19), co.bito.bito-intellij (1.0.138), com.luomacode.ChatMoss (1.0.7), commit-template-idea-plugin (1.2.0), com.mallowigi (50.2.0), com.starxg.mybatis-log-plugin-free (1.3.0), com.github.camork.fileExpander (2.0), com.github.beansoft.jadx.gui.idea (2022.1.0), com.intellij.kubernetes (212.5457.4), google-java-format (1.15.0.0), com.gionchat.json.bean (1.0.5), com.nnthink.aixcoder (4.1.27-2020), com.alibaba.p3c.smartfox (2.1.1), io.heidou.codesearch (1.1.0), com.alibabacloud.intellij.cosy (0.10.5-beta), org.jetbrains.plugins.vue (212.5457.27), com.shen.plugin.element (2.0), MavenRunHelper (4.19.212.000.1), org.jetbrains.kotlin (212-1.7.10-release-333-IJ5457.46), cn.yiiguxing.plugin.translate (3.5.0+203u212), izhangzhihao.rainbow.brackets (2023.2.9-ij), org.jetbrains.completion.full.line (0.2.72-203), zielu.gittoolbox (212.10.1), com.clutcher.comments_highlighter (2.4.1), com.ccnode.codegenerator.MyBatisCodeHelperPro (3.2.0)
Kotlin: 212-1.7.10-release-333-IJ5457.46

**Comment by zielu** [comment]
Hi, it's related to blame caching. New storage solution is almost done and will solve it permanently

**Comment by zielu** [comment]
Done in 500.0.14+222
