### ISSUE TITLE
[BUG] com.intellij.util.IncorrectOperationException

### ISSUE THREAD

**Issue by renatomameli** [zielu/GitToolBox#492]
Not disposed

com.intellij.util.IncorrectOperationException: Sorry but parent: zielu.gittoolbox.a.m@6cbebfc0 (class zielu.gittoolbox.a.m) has already been disposed (see the cause for stacktrace) so the child: DisposableWrapper[task=Kt[task=Function0<kotlin.Unit>, active=$true]] (class zielu.a.b.j) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:143)
	at zielu.gittoolbox.G.d.a(SourceFile:11)
	at zielu.gittoolbox.G.x.b(SourceFile:35)
	at zielu.gittoolbox.a.m.a(SourceFile:50)
	at zielu.gittoolbox.a.s.a(SourceFile:112)
	at zielu.gittoolbox.a.s.a(SourceFile:24)
	at zielu.gittoolbox.a.E.a(SourceFile:99)
	at zielu.gittoolbox.a.E.invoke(SourceFile:99)
	at zielu.gittoolbox.a.t.run(SourceFile:210)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.gittoolbox.a.j.run(SourceFile:52)
	at zielu.a.l.f.run(SourceFile:130)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.a.e.f.run(SourceFile:70)
	at zielu.a.b.f.a(SourceFile:12)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.n.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zielu** [comment]
Hi, which plugin version are you using ?

**Comment by renatomameli** [comment]
500.0.4+213

**Comment by zielu** [comment]
Please use latest one: 500.0.13

**Comment by trungdlp-wolffun** [comment]
@zielu 

Goland: Build #GO-232.8660.185, built on July 26, 2023, Plugin: **500.0.14+222**

com.intellij.util.IncorrectOperationException: Sorry but parent: services of com.intellij.openapi.project.impl.ProjectImpl@1729561850 (class com.intellij.openapi.util.Disposer$2) has already been disposed (see the cause for stacktrace) so the child: zielu.gittoolbox.a.a.a.b.b@202f1e94 (class zielu.gittoolbox.a.a.a.b.b) will never be disposed
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:43)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:161)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:935)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService$lambda$10$lambda$8(ComponentManagerImpl.kt:740)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:739)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:688)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
	at zielu.gittoolbox.H.c.b(SourceFile:20)
	at zielu.gittoolbox.a.a.a.b.c.a(SourceFile:190)
	at zielu.gittoolbox.a.a.a.c.a(SourceFile:18)
	at zielu.gittoolbox.a.a.g.a(SourceFile:29)
	at zielu.gittoolbox.a.a.g.invoke(SourceFile:28)
	at zielu.a.j.a.h.b(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.j.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.a.f.a(SourceFile:28)
	at zielu.gittoolbox.a.a.d.a(SourceFile:81)
	at zielu.gittoolbox.a.a.d.b(SourceFile:66)
	at zielu.gittoolbox.a.a.d.a(SourceFile:49)
	at zielu.gittoolbox.a.S.a(SourceFile:29)
	at zielu.gittoolbox.a.A.a(SourceFile:188)
	at zielu.gittoolbox.a.A.a(SourceFile:154)
	at zielu.gittoolbox.a.B.a(SourceFile:172)
	at zielu.gittoolbox.a.B.invoke(SourceFile:172)
	at zielu.a.j.a.h.b(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.j.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.r.a(SourceFile:36)
	at zielu.gittoolbox.a.A.a(SourceFile:172)
	at zielu.a.b.q.run(SourceFile:9)
	at zielu.a.l.r.run(SourceFile:130)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:360)
	at zielu.gittoolbox.F.h.a(SourceFile:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zielu** [comment]
Hi, I'll look into it

**Comment by zielu** [comment]
There is related IDE ticket: https://youtrack.jetbrains.com/issue/IDEA-270851

**Comment by zielu** [comment]
Partial fix in 500.0.15
