### ISSUE TITLE
[BUG] Error in Intellij Idea for GitToolBox

### ISSUE THREAD

**Issue by vishalg-yadav** [zielu/GitToolBox#497]
Getting following error in Intellij Idea
java.lang.UnsupportedOperationException
	at jetbrains.exodus.entitystore.BlobHandleGenerator.lambda$static$0(BlobHandleGenerator.java:43)
	at jetbrains.exodus.entitystore.FileSystemBlobVaultOld.nextHandle(FileSystemBlobVaultOld.java:128)
	at jetbrains.exodus.entitystore.PersistentEntityStoreImpl.createBlobHandle(PersistentEntityStoreImpl.java:1259)
	at jetbrains.exodus.entitystore.PersistentEntityStoreImpl.setBlobString(PersistentEntityStoreImpl.java:1204)
	at jetbrains.exodus.entitystore.PersistentEntity.setBlobString(PersistentEntity.java:209)
	at zielu.gittoolbox.a.a.a.b.f.a(SourceFile:13)
	at zielu.gittoolbox.a.a.a.b.b.a(SourceFile:110)
	at jetbrains.exodus.entitystore.PersistentEntityStoreImpl.executeInTransaction(PersistentEntityStoreImpl.java:699)
	at zielu.gittoolbox.a.a.a.b.b.b(SourceFile:66)
	at zielu.gittoolbox.a.a.a.b.b.a(SourceFile:55)
	at zielu.gittoolbox.a.a.f.a(SourceFile:34)
	at zielu.gittoolbox.a.a.d.a(SourceFile:96)
	at zielu.gittoolbox.a.a.d.b(SourceFile:72)
	at zielu.gittoolbox.a.a.d.a(SourceFile:49)
	at zielu.gittoolbox.a.S.a(SourceFile:29)
	at zielu.gittoolbox.a.A.a(SourceFile:188)
	at zielu.gittoolbox.a.A.a(SourceFile:154)
	at zielu.gittoolbox.a.B.a(SourceFile:172)
	at zielu.gittoolbox.a.B.invoke(SourceFile:172)
	at zielu.a.j.a.h.b(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.j.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.r.a(SourceFile:36)
	at zielu.gittoolbox.a.A.a(SourceFile:172)
	at zielu.a.b.q.run(SourceFile:9)
	at zielu.a.l.r.run(SourceFile:130)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:360)
	at zielu.gittoolbox.F.h.a(SourceFile:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
![image](https://github.com/zielu/GitToolBox/assets/32416626/00a2d223-3989-4d85-af15-c5efdc6dafae)

**Comment by chengshaohui** [comment]
Had the same problem in webstorm

**Comment by zielu** [comment]
Done in 500.0.15
