### ISSUE TITLE
[BUG] IOException (sometimes) when opening IntelliJ

### ISSUE THREAD

**Issue by blambert-delfingen** [zielu/GitToolBox#498]
First of all, thankls for this fantastic plugin :)

Sometimes, when openin IntelliJ, an error message appears.

Exact plugin version. 500.0.14+222
IDE 2023.2 Ultimate, build IU-232.8660.185
OS Windows 11 with Sophos AV (i think it's the cause)

The stacktrace in the message error box (IDE Internal Errors dialog box) is the following :

  Failed to delete D:\JetBrains0\IntelliJIdea2023.2\projects\sources.c071206\gittoolbox\blame-store-xodus\v2
  
  java.io.IOException: Unable to delete: D:\JetBrains0\IntelliJIdea2023.2\projects\sources.c071206\gittoolbox\blame-store-xodus\v2
at jodd.io.FileUtil.checkDeleteSuccessful(FileUtil.java:1634)
at jodd.io.FileUtil.deleteDir(FileUtil.java:512)
at zielu.gittoolbox.a.a.a.b.b.<init>(SourceFile:43)
at zielu.gittoolbox.a.a.a.b.b.<init>(SourceFile:51)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:976)
at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:954)
at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:933)
at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService$lambda$10$lambda$8(ComponentManagerImpl.kt:740)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:64)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:739)
at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:688)
at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:630)
at zielu.gittoolbox.H.c.b(SourceFile:20)
at zielu.gittoolbox.a.a.a.b.c.a(SourceFile:190)
at zielu.gittoolbox.a.a.a.c.a(SourceFile:18)
at zielu.gittoolbox.a.a.g.a(SourceFile:29)
at zielu.gittoolbox.a.a.g.invoke(SourceFile:28)
at zielu.a.j.a.h.b(SourceFile:10)
at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
at zielu.a.j.a.h.a(SourceFile:10)
at zielu.gittoolbox.a.a.f.a(SourceFile:28)
at zielu.gittoolbox.a.a.d.a(SourceFile:81)
at zielu.gittoolbox.a.a.d.b(SourceFile:66)
at zielu.gittoolbox.a.a.d.a(SourceFile:49)
at zielu.gittoolbox.a.S.a(SourceFile:29)
at zielu.gittoolbox.a.A.a(SourceFile:188)
at zielu.gittoolbox.a.A.a(SourceFile:154)
at zielu.gittoolbox.a.B.a(SourceFile:172)
at zielu.gittoolbox.a.B.invoke(SourceFile:172)
at zielu.a.j.a.h.b(SourceFile:10)
at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
at zielu.a.j.a.h.a(SourceFile:10)
at zielu.gittoolbox.a.r.a(SourceFile:36)
at zielu.gittoolbox.a.A.a(SourceFile:172)
at zielu.a.b.q.run(SourceFile:9)
at zielu.a.l.r.run(SourceFile:130)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:360)
at zielu.gittoolbox.F.h.a(SourceFile:109)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:29)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zielu** [comment]
Done in 500.0.15
