### ISSUE TITLE
[BUG] Null pointer exception

### ISSUE THREAD

**Issue by arrivingskills** [zielu/GitToolBox#500]
**Describe the bug**
Null pointer exception on initial load of PyCharm 2023.2.1 (Professional Edition) Build #PY-232.9559.58, built on August 22, 2023
from the plugin. Note it worked prior to upgrade.

java.lang.NullPointerException
	at zielu.gittoolbox.a.a.a.a.b.a(SourceFile:123)
	at jetbrains.exodus.entitystore.PersistentEntityStoreImpl.computeInTransaction(PersistentEntityStoreImpl.java:748)
	at zielu.gittoolbox.a.a.a.a.b.a(SourceFile:116)
	at zielu.gittoolbox.a.a.g.a(SourceFile:29)
	at zielu.gittoolbox.a.a.g.invoke(SourceFile:28)
	at zielu.a.j.a.h.b(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.j.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.a.f.a(SourceFile:28)
	at zielu.gittoolbox.a.a.d.a(SourceFile:81)
	at zielu.gittoolbox.a.a.d.b(SourceFile:66)
	at zielu.gittoolbox.a.a.d.a(SourceFile:49)
	at zielu.gittoolbox.a.S.a(SourceFile:29)
	at zielu.gittoolbox.a.A.a(SourceFile:188)
	at zielu.gittoolbox.a.A.a(SourceFile:154)
	at zielu.gittoolbox.a.B.a(SourceFile:172)
	at zielu.gittoolbox.a.B.invoke(SourceFile:172)
	at zielu.a.j.a.h.b(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.j.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.r.a(SourceFile:36)
	at zielu.gittoolbox.a.A.a(SourceFile:172)
	at zielu.a.b.q.run(SourceFile:10)
	at zielu.a.k.r.run(SourceFile:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:360)
	at zielu.gittoolbox.F.h.a(SourceFile:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zielu** [comment]
On it

**Comment by zielu** [comment]
Looks like some inconsistency in blame storage that I need to investigate deeper. As a workaround you can [invalidate caches ](https://man.sr.ht/~zielu/gittoolbox-man/manual.md#cache-invalidation)

**Comment by arrivingskills** [comment]
Thank you
—
https://www.buymeacoffee.com/andykmiles
https://www.patreon.com/andykmiles

**Comment by zielu** [comment]
I made some improvements to blame storage, could you try [latest EAP build](https://man.sr.ht/~zielu/gittoolbox-man/manual.md#eap-release-channel) ?

**Comment by arrivingskills** [comment]
Yes I will - thank you

--

**Comment by arrivingskills** [comment]
It’s working great! Thank you, fantastic service.

--

**Comment by zielu** [comment]
500.0.18
