### ISSUE TITLE
[BUG] exception occurring sometimes while doing Git Update from git window

### ISSUE THREAD

**Issue by blambert-delfingen** [zielu/GitToolBox#501]
**Describe the bug**
An error notification appears sometimes when i click on a branch in the git tool window and do an "update" action.
It somehow does the update.

**To Reproduce**
(See description)

**Plugin version**
Exact plugin version. 500.0.15+ 222

**IDE version**
IntelliJ IDEA 2023.1.5 (Ultimate Edition)
Build #IU-231.9392.1, built on July 25, 2023
Licensed to DELFINGEN Industry S.A. / Benjamin Lambert
You have a perpetual fallback license for this version.
Subscription is active until March 30, 2024.
Runtime version: 17.0.7+10-b829.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1998M
Cores: 8
Registry:
    debugger.click.disable.breakpoints=true
    documentation.show.toolbar=true
    debugger.valueTooltipAutoShowOnSelection=true

Non-Bundled Plugins:
    me.klez.jasper-report-support (1.0.8)
    MultiHighlight (3.1.0)
    Key Promoter X (2023.2.0)
    io.github.aveenstra.run-anything (2.0)
    com.intellij.ideolog (222.1.0.0)
    com.khmelyuk.multirun (1.13)
    com.intellij.nativeDebug (231.9392.3)
    com.tabnine.TabNine (1.0.51)
    com.github.janneri.innerbuildergeneratorintellijplugin (1.1.8)
    com.intellij.guice (231.8109.90)
    org.jetbrains.kotlin (231-1.9.10-release-459-IJ8770.65)
    marcglasberg.HibernateInspectionsPlugin (1.6)
    com.dguner.lombok-builder-helper (1.5.0)
    InnerBuilder Continued (1.0.5)
    com.kn.diagrams.generator.generator (2022.2.0)
    org.jetbrains.plugins.spotbugs (1.2.5)
    JettyRunner-GK (1.4.20)
    String Manipulation (9.11.3)
    com.intellij.javaee.ejb (231.8109.90)
    at.kienmeier.plugins.creational.stepbuilder (1.0.0)
    PlantUML integration (6.4.0-IJ2022.2)
    com.intellij.spring.shell (231.8109.90)
    com.intellij.javaee.webSocket (231.8109.90)
    com.intellij.spring.websocket (231.8770.17)
    com.jetbrains.jax.ws (231.8109.90)
    com.intellij.spring.batch (231.8770.17)
    com.intellij.spring.webflow (231.9225.16)
    ch.newinstance.plugin.mavendependencychecker (1.8.1)
    MavenRunHelper (4.23.222.2964.0)
    com.yiycf.plugins.mavenDependencyHelper (2.5)
    org.kubicz.mavenexecutor.plugin.id (2.1.1)
    appland.appmap (0.45.5)
    Jetty (231.8109.90)
    com.intellij.javaee.batch (231.8109.90)
    org.sonarlint.idea (9.0.0.75308)
    com.intellij.spring.ws (231.8770.17)
    com.github.lppedd.idea-return-highlighter (0.8.3)
    SequenceDiagram (3.0.5)
    org.jetbrains.research.refactorinsight (2023.1-4.0)
    ru.adelf.idea.dotenv (2023.1)
    zielu.gittoolbox (500.0.15+222)
    com.intellij.plugins.html.instantEditing (231.8770.15)
    spy-js (231.8109.91)
    org.vepanimas.uml.javascript (0.2.0)
    izhangzhihao.rainbow.brackets (2023.3.4)
    ch.docksnet.rgraph (3.1.1)

Kotlin: 231-1.9.10-release-459-IJ8770.65

Stacktrace :
java.lang.AssertionError: Cannot create class zielu.gittoolbox.a.a.a.a.b (classloader=PluginClassLoader(plugin=PluginDescriptor(name=GitToolBox, id=zielu.gittoolbox, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.1\plugins\gittoolbox, version=500.0.15+222, package=null, isBundled=false), packagePrefix=null, instanceId=287, state=active))
	at com.intellij.openapi.diagnostic.DefaultLogger.error(DefaultLogger.java:54)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:240)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.setException(SchedulingWrapper.java:288)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.intellij.diagnostic.PluginException: Cannot create class zielu.gittoolbox.a.a.a.a.b (classloader=PluginClassLoader(plugin=PluginDescriptor(name=GitToolBox, id=zielu.gittoolbox, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\IntelliJIdea2023.1\plugins\gittoolbox, version=500.0.15+222, package=null, isBundled=false), packagePrefix=null, instanceId=287, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1034)
	at com.intellij.serviceContainer.ComponentManagerImpl.createLightService(ComponentManagerImpl.kt:970)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService$lambda$9$lambda$7(ComponentManagerImpl.kt:778)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeNonCancelableSection$3(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$computeInNonCancelableSection$4(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.Cancellation.computeInNonCancelableSection(Cancellation.java:99)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeInNonCancelableSection(CoreProgressManager.java:230)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:221)
	at com.intellij.serviceContainer.ComponentManagerImpl.getOrCreateLightService(ComponentManagerImpl.kt:777)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:726)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:670)
	at zielu.gittoolbox.H.c.b(SourceFile:20)
	at zielu.gittoolbox.a.a.a.a.c.a(SourceFile:175)
	at zielu.gittoolbox.a.a.a.c.a(SourceFile:15)
	at zielu.gittoolbox.a.a.g.a(SourceFile:29)
	at zielu.gittoolbox.a.a.g.invoke(SourceFile:28)
	at zielu.a.j.a.h.b(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.j.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.a.f.a(SourceFile:28)
	at zielu.gittoolbox.a.a.d.a(SourceFile:81)
	at zielu.gittoolbox.a.a.d.b(SourceFile:66)
	at zielu.gittoolbox.a.a.d.a(SourceFile:49)
	at zielu.gittoolbox.a.S.a(SourceFile:29)
	at zielu.gittoolbox.a.A.a(SourceFile:188)
	at zielu.gittoolbox.a.A.a(SourceFile:154)
	at zielu.gittoolbox.a.B.a(SourceFile:172)
	at zielu.gittoolbox.a.B.invoke(SourceFile:172)
	at zielu.a.j.a.h.b(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.j.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.r.a(SourceFile:36)
	at zielu.gittoolbox.a.A.a(SourceFile:172)
	at zielu.a.b.q.run(SourceFile:10)
	at zielu.a.k.r.run(SourceFile:129)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:361)
	at zielu.gittoolbox.F.h.a(SourceFile:109)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1007)
	... 60 more
Caused by: jetbrains.exodus.ExodusException: Can't acquire environment lock after 0 ms.

 Lock owner info: 
null
	at jetbrains.exodus.log.Log.tryLock(Log.kt:805)
	at jetbrains.exodus.log.Log.<init>(Log.kt:117)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.kt:117)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.kt:81)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.kt:77)
	at jetbrains.exodus.env.Environments$newInstance$4.invoke(Environments.kt:46)
	at jetbrains.exodus.env.Environments$newInstance$4.invoke(Environments.kt:46)
	at jetbrains.exodus.env.Environments.prepare(Environments.kt:120)
	at jetbrains.exodus.env.Environments.newInstance(Environments.kt:46)
	at jetbrains.exodus.env.Environments.newInstance(Environments.kt:43)
	at zielu.gittoolbox.a.a.a.a.t.b(SourceFile:33)
	at zielu.gittoolbox.a.a.a.a.t.a(SourceFile:28)
	at zielu.gittoolbox.a.a.a.a.b.<init>(SourceFile:33)
	at zielu.gittoolbox.a.a.a.a.b.<init>(SourceFile:36)
	... 66 more

**Comment by zielu** [comment]
I made some improvements to blame storage, could you try [latest EAP build](https://man.sr.ht/~zielu/gittoolbox-man/manual.md#eap-release-channel) ?

**Comment by blambert-delfingen** [comment]
Hi @zielu , thanks for such a quick action ! I'm unfortunately stuck with version 2023.1.5 as of now, i'll let this tab opened and push an answer as soon as i get one.

**Comment by zielu** [comment]
@blambert-delfingen that EAP build should work for 2022.2 and up.

**Comment by zielu** [comment]
500.0.18
