### ISSUE TITLE
[BUG] Error on IDE open 'unrecognized format string 'h:mm B''

### ISSUE THREAD

**Issue by behzadsh** [zielu/GitToolBox#521]
**Describe the bug**
Every time I open any of the IntelliJ IDEs that have the GitToolBox plugin installed, I get the following error:

I also tried to uninstall and reinstall the plugin, but nothing changed.

```
Exception in plugin GitToolBox (500.1.2+222)
java.lang.IllegalArgumentException: unrecognized format string 'h:mm B'
	at com.intellij.util.text.DateFormatUtil.formatFromString(DateFormatUtil.java:453)
	at com.intellij.util.text.DateFormatUtil.getMacFormat(DateFormatUtil.java:365)
	at com.intellij.util.text.DateFormatUtil.getMacFormats(DateFormatUtil.java:350)
	at com.intellij.util.text.DateFormatUtil.getDateTimeFormats(DateFormatUtil.java:286)
	at com.intellij.util.text.DateFormatUtil.<clinit>(DateFormatUtil.java:53)
	at zielu.gittoolbox.j.a.<clinit>(SourceFile:19)
	at zielu.gittoolbox.G.e.a(SourceFile:10)
	at zielu.gittoolbox.G.f.a(SourceFile:45)
	at zielu.gittoolbox.G.f.a(SourceFile:41)
	at zielu.gittoolbox.G.f.b(SourceFile:28)
	at zielu.gittoolbox.G.f.a(SourceFile:21)
	at zielu.gittoolbox.G.c.ab.a(SourceFile:26)
	at zielu.gittoolbox.G.c.Z.a(SourceFile:24)
	at zielu.gittoolbox.G.c.l.a(SourceFile:131)
	at zielu.gittoolbox.G.c.l.a(SourceFile:102)
	at zielu.gittoolbox.G.c.l.a(SourceFile:185)
	at zielu.gittoolbox.G.c.l.a(SourceFile:179)
	at zielu.gittoolbox.G.c.l.b(SourceFile:168)
	at zielu.gittoolbox.G.c.j.a(SourceFile:69)
	at zielu.gittoolbox.G.c.z.a(SourceFile:90)
	at zielu.gittoolbox.G.c.z.invoke(SourceFile:84)
	at zielu.gittoolbox.F.g.b(SourceFile:55)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$15(BackgroundTaskUtil.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at zielu.gittoolbox.F.g.b(SourceFile:101)
	at zielu.gittoolbox.F.a.b(SourceFile:35)
	at zielu.gittoolbox.F.g.a(SourceFile:55)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1430)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Plugin version**
500.1.2+222

**IDE version**
GoLand 2023.3.1
Build #GO-233.11799.286, built on December 11, 2023

also in
PhpStorm 2023.3.1
Build #PS-233.11799.297, built on December 12, 2023

**Screenshots**
![Screenshot 2023-12-17 at 3 24 17 in the afternoon](https://github.com/zielu/GitToolBox/assets/635441/29f728a3-ac24-47ad-87c6-1b4c880ebff3)

**Comment by zielu** [comment]
Hi, I'll look into it.

**Comment by zielu** [comment]
Looks like it's IDE issue, I'll add workaround in my code.

**Comment by zielu** [comment]
https://youtrack.jetbrains.com/issue/IDEA-341203/IllegalArgumentException-unrecognized-format-string-hmm-B

**Comment by zielu** [comment]
@behzadsh 500.1.3+222 contains workaround for this issue

**Comment by YannCebron** [comment]
@behzadsh What is your exact OS version? What system locale do you have set? Could you please share screenshot from _System Settings -> Language & Region_?

**Comment by behzadsh** [comment]
> @behzadsh What is your exact OS version?

MacOS Sonoma 14.2

> What system locale do you have set? Could you please share screenshot from System Settings -> Language & Region?

![Screenshot 2023-12-20 at 8 33 33 in the evening](https://github.com/zielu/GitToolBox/assets/635441/4ce0faaf-1af7-4df3-be82-a806fe8fc233)

@YannCebron
