### ISSUE TITLE
[BUG]  IntelliJ IDEA pop up an error

### ISSUE THREAD

**Issue by Ginsanity0914** [zielu/GitToolBox#529]
**Describe the bug**
There just an error message, but I don't know exactly what it will affect

**To Reproduce**
just open a project

**Plugin version**
212.10.1

**IDE version**
IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Licensed to fuzzes ally
You have a perpetual fallback license for this version.
Subscription is active until December 31, 2099.
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 7090M
Cores: 16
Non-Bundled Plugins: io.zhile.research.ide-eval-resetter (2.3.5), com.nasller.CodeGlancePro (1.3.8-Last2021.3.x), GrepConsole (12.22.1-IJ2021.1), com.alibaba.p3c.smartfox (2.1.1), cn.cloud.auto.restful.tool (1.4.5), zielu.gittoolbox (212.10.1), cn.yiiguxing.plugin.translate (3.5.6+203u212), com.baomidou.plugin.idea.mybatisPlus (1.7.2)
Kotlin: 212-1.5.10-release-IJ5284.40

**Screenshots**
Not disposed

java.io.EOFException
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:202)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:614)
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:569)
	at zielu.gittoolbox.a.a.a.a.c.b(SourceFile:64)
	at zielu.gittoolbox.a.a.a.a.c.a(SourceFile:43)
	at zielu.gittoolbox.a.a.a.a.c.read(SourceFile:8)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:584)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:521)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:209)
	at zielu.gittoolbox.a.a.a.b.a(SourceFile:93)
	at zielu.gittoolbox.a.a.g.a(SourceFile:29)
	at zielu.gittoolbox.a.a.g.invoke(SourceFile:28)
	at zielu.a.i.a.h.c(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.i.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.a.f.a(SourceFile:28)
	at zielu.gittoolbox.a.a.d.a(SourceFile:77)
	at zielu.gittoolbox.a.a.d.b(SourceFile:63)
	at zielu.gittoolbox.a.a.d.a(SourceFile:46)
	at zielu.gittoolbox.a.O.a(SourceFile:31)
	at zielu.gittoolbox.a.t.a(SourceFile:215)
	at zielu.gittoolbox.a.t.a(SourceFile:192)
	at zielu.gittoolbox.a.u.a(SourceFile:207)
	at zielu.gittoolbox.a.u.invoke(SourceFile:207)
	at zielu.a.i.a.h.c(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.i.a.h.a(SourceFile:10)
	at zielu.gittoolbox.a.m.b(SourceFile:37)
	at zielu.gittoolbox.a.t.run(SourceFile:207)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.gittoolbox.a.j.run(SourceFile:52)
	at zielu.a.k.f.run(SourceFile:130)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at zielu.a.d.f.run(SourceFile:70)
	at zielu.a.b.f.a(SourceFile:11)
	at zielu.a.b.m.a(SourceFile:21)
	at zielu.a.b.m.invoke(SourceFile:18)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.a.b.j.run(SourceFile:18)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
![image](https://github.com/zielu/GitToolBox/assets/52951854/cacdac8a-ff0c-4b51-a2a1-8592f3a58692)

**Comment by zielu** [comment]
Hi, as a workaround you can disable the persistence:
1.  Help > Find Action...
2. Registry...
3. Find key: `zielu.gittoolbox.blame.cache.persistent`
4. Uncheck it
5. Restart

I have no plans to update versions before 500.x.y.
