### ISSUE TITLE
[BUG] InvalidVirtualFileAccessException: Accessing invalid virtual file

### ISSUE THREAD

**Issue by tinhcao-unite** [zielu/GitToolBox#538]
**Describe the bug**
I got the exception below while trying to switch between branches
`com.intellij.openapi.vfs.InvalidVirtualFileAccessException: Accessing invalid virtual file: file:///Users/***/*.java; original:2387087; found:-; File.exists()=false
	at com.intellij.psi.impl.file.impl.FileManagerImpl.getCachedPsiFile(FileManagerImpl.java:367)
	at zielu.gittoolbox.G.c.a.K.a(SourceFile:212)
	at zielu.gittoolbox.G.c.a.K.invoke(SourceFile:212)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:170)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:809)
	at zielu.gittoolbox.G.c.a.E.a(SourceFile:213)
	at zielu.gittoolbox.G.c.a.E.invoke(SourceFile:201)
	at zielu.gittoolbox.F.g.c(SourceFile:69)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:843)
	at com.intellij.openapi.application.impl.ApplicationImpl$4.run(ApplicationImpl.java:463)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithEnabledImplicitRead(RwLockHolder.kt:75)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithImplicitRead(RwLockHolder.kt:67)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWithImplicitRead(ApplicationImpl.java:1436)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:124)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:44)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:695)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$12(IdeEventQueue.kt:589)
	at com.intellij.openapi.application.impl.RwLockHolder.runWithoutImplicitRead(RwLockHolder.kt:44)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:589)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:72)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:354)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:793)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:1014)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1014)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:349)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:848)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:391)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
`

**To Reproduce**
1. Create a new branch, do some changes, commit
2. Switch back to the main branch

**Expected behavior**
Nothing happened

**Plugin version**
500.2.0+233

**IDE version**
IntelliJ IDEA 2023.3.4 (Ultimate Edition)
Build #IU-233.14475.28, built on February 13, 2024
Licensed to ***
Subscription is active until ***.
For educational use only.
Runtime version: 17.0.10+1-b1087.17 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.7.4
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
  debugger.watches.in.variables=false
  editor.minimap.enabled=true
  jdk.downloader=false
Non-Bundled Plugins:
  com.intellij.plugins.watcher (233.13135.65)
  com.andrey4623.rainbowcsv (2.0.2)
  CMD Support (1.0.5)
  com.vecheslav.darculaSolidTheme (1.0.3)
  com.github.chencn.yamlandprops (1.0.5)
  mobi.hsz.idea.gitignore (4.5.2)
  org.jetbrains.plugins.go-template (233.11799.172)
  de.santiv.fastscrolling (1.2)
  uk.co.ben-gibson.remote.repository.mapper (4.4.0)
  com.intellij.plugins.macoskeymap (232.6095.10)
  name.kropp.intellij.makefile (233.13135.65)
  dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
  org.intellij.plugins.hcl (233.13135.65)
  com.github.copilot (1.5.0.5148)
  com.intellij.properties.bundle.editor (233.11799.172)
  EclipseCodeFormatter (23.3.223.000.0-Eclipse_2023-03)
  Stapler plugin for IntelliJ IDEA (3.0.3)
  GenerateSerialVersionUID (3.0.3)
  net.seesharpsoft.intellij.plugins.csv (3.3.0-233)
  com.intellij.guice (233.11799.196)
  PlantUML integration (7.7.0-IJ2023.2)
  com.jetbrains.jax.ws (233.13135.65)
  appland.appmap (0.59.0)
  com.dmarcotte.handlebars (233.11799.172)
  com.intellij.lang.jsgraphql (233.13135.65)
  org.mapstruct.intellij (1.6.1)
  hdzi.idea-editstarters-plugin (3.2.2)
  com.jetbrains.packagesearch.intellij-plugin (233.11800.8)
  me.mbolotov.cypress (1.6.2)
  mdx.js (233.11799.172)
  org.sonarlint.idea (10.4.0.77904)
  Pythonid (233.14475.28)
  zielu.gittoolbox (500.2.0+233)
  com.intellij.bigdatatools.core (233.14475.28)
  ru.adelf.idea.dotenv (2024.1)
  MavenRunHelper (4.27.1-IJ2022.2)
  org.intellij.scala (2023.3.27)
  MetricsReloaded (1.12)
  net.ashald.envfile (3.4.2)
Kotlin: 233.14475.28-IJ

**Screenshots**
![Uploading 2024-03-12-21.04.58.png…]()

**Comment by zielu** [comment]
Hi, I'll look into it.

**Comment by zielu** [comment]
Done in 500.2.1

**Comment by tinhcao-unite** [comment]
Thanks for the fix @zielu, I will check it today and let you know the result.

**Comment by tinhcao-unite** [comment]
Thanks for the fix, @zielu; I don't see it anymore 👍
