### ISSUE TITLE
173.1.1 hangs in Idea 2017.3.1.EAP

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#54]
```at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
	at com.intellij.dvcs.repo.VcsRepositoryManager.a(VcsRepositoryManager.java:200)
	at com.intellij.dvcs.repo.VcsRepositoryManager.a(VcsRepositoryManager.java:141)
	at com.intellij.dvcs.repo.VcsRepositoryManager.getRepositoryForRoot(VcsRepositoryManager.java:120)
	at com.intellij.dvcs.repo.VcsRepositoryManager.getRepositoryForFile(VcsRepositoryManager.java:110)
	at com.intellij.dvcs.repo.VcsRepositoryManager.getRepositoryForFile(VcsRepositoryManager.java:94)
	at zielu.gittoolbox.ui.projectView.node.DecorableModuleNode.getRepoForRoot(DecorableModuleNode.java:30)
	at zielu.gittoolbox.ui.projectView.node.DecorableModuleNode.getRepo(DecorableModuleNode.java:22)
	at zielu.gittoolbox.ui.projectView.ProjectViewDecorator.decorate(ProjectViewDecorator.java:36)
```

**Comment by zielu** [comment]
Fixed in 173.1.2
