### ISSUE TITLE
[BUG] java.net.URISyntaxException in Repository Links

### ISSUE THREAD

**Issue by BD4vid777** [zielu/GitToolBox#540]
Some Error in JetBRains

![image](https://github.com/zielu/GitToolBox/assets/64140934/655375d2-071e-46b4-ad51-ddcc0a0d779d)

`java.util.concurrent.ExecutionException: java.lang.RuntimeException: Cannot invoke (class=H, method=a, topic=Status cache change)
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.tryAwaitFuture(BackgroundTaskUtil.java:313)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$createBackgroundTask$9(BackgroundTaskUtil.java:292)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:130)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:162)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:250)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:238)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$createBackgroundTask$12(BackgroundTaskUtil.java:305)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:244)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:222)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.RuntimeException: Cannot invoke (class=H, method=a, topic=Status cache change)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:677)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:423)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:402)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:461)
	at jdk.proxy9/jdk.proxy9.$Proxy168.a(Unknown Source)
	at zielu.gittoolbox.c.Q.a(SourceFile:133)
	at zielu.gittoolbox.c.Q.invoke(SourceFile:132)
	at zielu.gittoolbox.b.a(SourceFile:87)
	at zielu.gittoolbox.H.A.b(SourceFile:29)
	at zielu.gittoolbox.H.B.a(SourceFile:41)
	at zielu.a.b.h.run(SourceFile:10)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$submitTask$8(BackgroundTaskUtil.java:266)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$createBackgroundTask$10(BackgroundTaskUtil.java:302)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:73)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:685)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:641)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:78)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:73)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$createBackgroundTask$11(BackgroundTaskUtil.java:297)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 12 more
Caused by: java.net.URISyntaxException: Illegal character in fragment at index 62: https://github.com/BD4vid777/vida-frontend/pull/new/fix_#5851_#6087
	at java.base/java.net.URI$Parser.fail(URI.java:2976)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3147)
	at java.base/java.net.URI$Parser.parse(URI.java:3191)
	at java.base/java.net.URI.<init>(URI.java:623)
	at zielu.gittoolbox.u.e.d.a(SourceFile:94)
	at zielu.gittoolbox.u.e.d.a(SourceFile:30)
	at zielu.gittoolbox.u.e.f.a(SourceFile:193)
	at zielu.gittoolbox.u.e.f.invoke(SourceFile:191)
	at zielu.gittoolbox.u.q.a(SourceFile:57)
	at zielu.gittoolbox.u.q.invoke(SourceFile:56)
	at zielu.gittoolbox.u.p.a(SourceFile:80)
	at zielu.gittoolbox.u.p.a(SourceFile:56)
	at zielu.gittoolbox.u.p.a(SourceFile:16)
	at zielu.gittoolbox.u.e.d.a(SourceFile:191)
	at zielu.gittoolbox.u.U.a(SourceFile:446)
	at zielu.gittoolbox.u.U.invoke(SourceFile:438)
	at zielu.gittoolbox.s.c.c(SourceFile:84)
	at zielu.gittoolbox.u.az.a(SourceFile:27)
	at zielu.gittoolbox.u.J.a(SourceFile:438)
	at zielu.gittoolbox.u.aF.a(SourceFile:25)
	at zielu.gittoolbox.u.aF.invoke(SourceFile:23)
	at zielu.gittoolbox.s.c.a(SourceFile:100)
	at zielu.gittoolbox.u.aD.a(SourceFile:23)
	at zielu.gittoolbox.u.I.a(SourceFile:15)
	at zielu.gittoolbox.u.I.invoke(SourceFile:14)
	at zielu.gittoolbox.s.c.a(SourceFile:100)
	at zielu.gittoolbox.u.H.a(SourceFile:14)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:700)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:660)
	... 36 more
`

**Comment by zielu** [comment]
Hi, I'm on it

**Comment by zielu** [comment]
Fixed in 500.2.2
