### ISSUE TITLE
[BUG] `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon.

### ISSUE THREAD

**Issue by ForsakenHarmony** [zielu/GitToolBox#543]
**Describe the bug**
```java
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'zielu.gittoolbox.G.a.a.a' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: zielu.gittoolbox]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Plugin version & IDE version**
```
GoLand 2024.1 RC
Build #GO-241.14494.155, built on March 21, 2024
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4
Non-Bundled Plugins:
  zielu.gittoolbox (500.2.2+233)
```

**Comment by zielu** [comment]
Done in 500.2.3
