### ISSUE TITLE
[BUG] java.lang.NullPointerException

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#546]
**Describe the bug**
java.lang.NullPointerException
```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at git4idea.GitVcs.getInstance(GitVcs.java:82)
	at git4idea.commands.GitHandler.<init>(GitHandler.java:141)
	at git4idea.commands.GitHandler.<init>(GitHandler.java:89)
	at git4idea.commands.GitHandler.<init>(GitHandler.java:107)
	at git4idea.commands.GitTextHandler.<init>(GitTextHandler.java:45)
	at git4idea.commands.GitLineHandler.<init>(GitLineHandler.java:57)
	at zielu.gittoolbox.C.f.a(SourceFile:70)
	at zielu.gittoolbox.C.f.a(SourceFile:60)
	at zielu.gittoolbox.C.f.a(SourceFile:45)
	at zielu.gittoolbox.c.D.a(SourceFile:25)
	at zielu.gittoolbox.c.D.invoke(SourceFile:24)
	at zielu.a.j.a.h.b(SourceFile:10)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.a.j.a.h.a(SourceFile:10)
	at zielu.gittoolbox.c.A.a(SourceFile:24)
	at zielu.gittoolbox.c.K.a(SourceFile:100)
	at zielu.gittoolbox.c.at.a(SourceFile:64)
	at zielu.gittoolbox.c.at.invoke(SourceFile:63)
	at zielu.a.m.d.a(SourceFile:32)
	at zielu.gittoolbox.c.Z.b(SourceFile:63)
	at zielu.gittoolbox.c.Z.a(SourceFile:49)
	at zielu.gittoolbox.c.Z.a(SourceFile:17)
	at zielu.gittoolbox.c.ap.a(SourceFile:39)
	at zielu.gittoolbox.c.ap.invoke(SourceFile:38)
	at zielu.a.m.d.a(SourceFile:23)
	at zielu.gittoolbox.c.Z.a(SourceFile:38)
	at zielu.gittoolbox.c.Z.a(SourceFile:17)
	at zielu.gittoolbox.c.ao.a(SourceFile:120)
	at zielu.gittoolbox.c.ao.invoke(SourceFile:120)
	at zielu.gittoolbox.c.ae.a(SourceFile:220)
	at zielu.a.b.h.run(SourceFile:10)
	at zielu.a.k.h.run(SourceFile:145)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:360)
	at zielu.gittoolbox.F.g.a(SourceFile:137)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**To Reproduce**
N/A

**Expected behavior**
No exception

**Plugin version**
N/A

**IDE version**
N/A

**Screenshots**
N/A

**Comment by zielu** [comment]
Done in 500.2.7
