### ISSUE TITLE
[BUG][JB] Error on IDE start

### ISSUE THREAD

**Issue by ColiZei** [zielu/GitToolBox#566]
**Describe the bug**
Hi,

always on IDE start i got the error below.
I don't know why and what it breaks.

**To Reproduce**
1. Start the IDE

**Expected behavior**
There should be not an error.

**Plugin version**
500.2.15+242

**IDE version**
PhpStorm 2024.2.0.1
Build #PS-242.20224.427, built on August 21, 2024
Runtime version: 21.0.3+13-b509.4 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Fedora Linux 6.10.6-200.fc40.x86_64
Current Desktop: GNOME

**Screenshots**
![image](https://github.com/user-attachments/assets/86ea7324-7c18-4a18-8ef4-fb250300d321)

Log:
```
java.lang.Throwable: com.intellij.openapi.vcs.VcsNotifier <clinit> requests com.intellij.notification.NotificationGroupManager instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1588)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1557)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:746)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:690)
	at com.intellij.notification.NotificationGroupManager.getInstance(NotificationGroupManager.java:19)
	at com.intellij.openapi.vcs.VcsNotifier.<clinit>(VcsNotifier.java:23)
	at git4idea.fetch.GitFetchSupportImpl$fetch$1.invoke(GitFetchSupportImpl.kt:130)
	at git4idea.fetch.GitFetchSupportImpl$fetch$1.invoke(GitFetchSupportImpl.kt:112)
	at git4idea.fetch.GitFetchSupportImpl.withIndicator(GitFetchSupportImpl.kt:225)
	at git4idea.fetch.GitFetchSupportImpl.fetch(GitFetchSupportImpl.kt:112)
	at git4idea.fetch.GitFetchSupportImpl.fetchRemotes(GitFetchSupportImpl.kt:106)
	at zielu.gittoolbox.j.y.u(y.java:12)
	at zielu.gittoolbox.j.K.X(K.java:53)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:136)
	at zielu.intellij.e.x.W.f(W.java:6)
	at zielu.gittoolbox.j.K.K(K.java:114)
	at zielu.gittoolbox.j.K.W(K.java:123)
	at zielu.gittoolbox.j.K.J(K.java:66)
	at zielu.gittoolbox.j.K.i(K.java:39)
	at zielu.intellij.c.k.run(k.java:3)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$runUnderDisposeAwareIndicator$15(BackgroundTaskUtil.java:371)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:366)
	at zielu.gittoolbox.N.d.R(d.java:5)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:30)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:212)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by zielu** [comment]
Hi, I'll look into it

**Comment by zielu** [comment]
Looks like it's IDE issue. Error, while ugly, does not break anything. I reaported https://youtrack.jetbrains.com/issue/IJPL-161396/VcsNotifier-error-on-creation

**Comment by ColiZei** [comment]
Ok nice! Thank you!

**Comment by zielu** [comment]
JB resolved it
