### ISSUE TITLE
[BUG] requested as a service, but it is a component

### ISSUE THREAD

**Issue by zielu** [zielu/GitToolBox#571]
**To Reproduce**
Happens randomly and restart usually helps.

**Plugin version**
600.0.1+242

**Comment by zielu** [comment]
```
com.intellij.diagnostic.PluginException: zielu.gittoolbox.C.h.o requested as a service, but it is a component - convert it to a service or change call to project.getComponent() [Plugin: zielu.gittoolbox]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:768)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceIfCreated(ComponentManagerImpl.kt:711)
	at zielu.gittoolbox.j.d.Q(d.java:1)
	at zielu.gittoolbox.j.d.h(d.java:27)
	at zielu.gittoolbox.C.h.dh.r(dh.java:2)
	at zielu.gittoolbox.C.h.dR.invokeSuspend(dR.java:2)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at com.intellij.openapi.application.impl.DispatchedRunnable.run(DispatchedRunnable.kt:44)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:236)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:25)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:218)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:117)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:43)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:679)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:574)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:356)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:844)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:355)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1047)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:87)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:922)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1047)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1056)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:109)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1056)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:350)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:396)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by zielu** [comment]
```
com.intellij.diagnostic.PluginException: zielu.gittoolbox.e.L requested as a service, but it is a component - convert it to a service or change call to project.getComponent() [Plugin: zielu.gittoolbox]
            at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
            at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
            at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:763)
            at com.intellij.serviceContainer.ComponentManagerImpl.getServiceIfCreated(ComponentManagerImpl.kt:706)
            at zielu.gittoolbox.I.h.x(h.java:6)
            at zielu.gittoolbox.I.h.N(h.java:34)
            at zielu.gittoolbox.e.V.Y(V.java:7)
            at zielu.gittoolbox.e.Z.c(Z.java:11)
            at zielu.gittoolbox.e.G.k(G.java:1)
            at zielu.gittoolbox.y.V.A(V.java:4)
            at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:722)
            at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:686)
            at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:445)
            at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:424)
            at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
            at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:483)
            at jdk.proxy13/jdk.proxy13.$Proxy240.A(Unknown Source)
            at zielu.gittoolbox.y.w.m(w.java:61)
            at zielu.gittoolbox.y.w.j(w.java:35)
            at zielu.gittoolbox.p.A(p.java:7)
            at zielu.gittoolbox.I.k.invokeSuspend(k.java:3)
            at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
            at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
            at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
            at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

**Comment by ap-wtioit** [comment]
also happens to me:
```
com.intellij.diagnostic.PluginException: zielu.gittoolbox.o.q.P requested as a service, but it is a component - convert it to a service or change call to project.getComponent() [Plugin: zielu.gittoolbox]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:763)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceIfCreated(ComponentManagerImpl.kt:706)
	at zielu.gittoolbox.W.P.l(P.java:31)
	at zielu.gittoolbox.W.P.Z(P.java:12)
	at zielu.gittoolbox.o.q.N.x(N.java:3)
	at zielu.gittoolbox.o.q.d.f(d.java:31)
	at zielu.gittoolbox.o.q.b.p(b.java:2)
	at zielu.gittoolbox.c.x.h(x.java:4)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:722)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:682)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:445)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:424)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:483)
	at jdk.proxy9/jdk.proxy9.$Proxy183.h(Unknown Source)
	at zielu.gittoolbox.c.e.w(e.java:50)
	at zielu.gittoolbox.c.e.C(e.java:77)
	at zielu.gittoolbox.E.v(E.java:3)
	at zielu.gittoolbox.W.Z.o(Z.java:6)
	at zielu.gittoolbox.c.e.R(e.java:63)
	at zielu.gittoolbox.c.M.X(M.java:131)
	at zielu.gittoolbox.c.M.z(M.java:19)
	at zielu.gittoolbox.c.M.A(M.java:120)
	at zielu.gittoolbox.c.a.invokeSuspend(a.java)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```
And the report problem link goes to https://www.lukasz-zielinski.com/ which is not really helping.
![image](https://github.com/user-attachments/assets/41a1acf6-67a5-4817-8b07-6215f0e8e352)

```
PyCharm 2024.2.4 (Professional Edition)
Build #PY-242.23726.102, built on October 22, 2024
Licensed to Redacted
Subscription is active until Redacted
Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-48-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 16384M
Cores: 16
Registry:
  i18n.locale=
Non-Bundled Plugins:
  com.intellij.classic.ui (242.20224.159)
  com.jetbrains.space (242.23726.16)
  com.perl5 (2024.2.3)
  com.intellij.ideolog (242.23726.110)
  ir.msdehghan.plugins.ansible (0.92)
  com.intellij.ml.llm (242.23726.20)
  at.wtioit.intellij.plugins.odoo (0.6.11)
  pro.bashsupport (4.3.2.242)
  net.seesharpsoft.intellij.plugins.csv (4.0.0)
  org.exbin.deltahex.intellij (0.2.10.1)
  mobi.hsz.idea.gitignore (4.5.4)
  zielu.gittoolbox (600.0.5+242)
Current Desktop: ubuntu:GNOME
```

**Comment by zielu** [comment]
Done in 600.0.7+242
