### ISSUE TITLE
Error in IntelliJ

### ISSUE THREAD

**Issue by ved-asole** [zielu/GitToolBox#575]
Error

```java
com.intellij.diagnostic.PluginException: zielu.gittoolbox.y.u.L requested as a service, but it is a component - convert it to a service or change call to project.getComponent() [Plugin: zielu.gittoolbox]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:763)
	at com.intellij.serviceContainer.ComponentManagerImpl.getServiceIfCreated(ComponentManagerImpl.kt:706)
	at zielu.gittoolbox.Q.v.m(v.java:37)
	at zielu.gittoolbox.Q.v.a(v.java:33)
	at zielu.gittoolbox.y.u.c.D(c.java:4)
	at zielu.gittoolbox.y.u.U.J(U.java:1)
	at zielu.gittoolbox.y.u.G.Y(G.java:1)
	at zielu.gittoolbox.i.I.a(I.java:2)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeMethod(MessageBusImpl.kt:722)
	at com.intellij.util.messages.impl.MessageBusImplKt.invokeListener(MessageBusImpl.kt:682)
	at com.intellij.util.messages.impl.MessageBusImplKt.deliverMessage(MessageBusImpl.kt:445)
	at com.intellij.util.messages.impl.MessageBusImplKt.pumpWaiting(MessageBusImpl.kt:424)
	at com.intellij.util.messages.impl.MessageBusImplKt.access$pumpWaiting(MessageBusImpl.kt:1)
	at com.intellij.util.messages.impl.MessagePublisher.invoke(MessageBusImpl.kt:483)
	at jdk.proxy17/jdk.proxy17.$Proxy212.a(Unknown Source)
	at zielu.gittoolbox.i.k.f(k.java:46)
	at zielu.gittoolbox.i.k.k(k.java:47)
	at zielu.gittoolbox.M.O(M.java:5)
	at zielu.gittoolbox.Q.j.invokeSuspend(j.java:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)

```

**Comment by zielu** [comment]
Hi, which plugin version is that ?

**Comment by ved-asole** [comment]
Currently it is 600.0.5+242

**Comment by zielu** [comment]
Done in 600.0.7+242
