### ISSUE TITLE
PhpStorm 9 error

### ISSUE THREAD

**Issue by glassdimly** [zielu/GitToolBox#7]
I got this error and had to disable GitToolBox. PHPStorm 9.0 was crashing when loading projects with git support enabled.

This seemed to happen on Java update from 8.51 to 8.52. Sorry, the bug report is incomplete because I had a hard time getting the trace before PHPStorm crashed.
```
java/util/Objects
java.lang.NoClassDefFoundError: java/util/Objects
	at zielu.gittoolbox.cache.CachedStatus.update(CachedStatus.java:31)
	at zielu.gittoolbox.cache.PerRepoStatusCache.get(PerRepoStatusCache.java:48)
	at zielu.gittoolbox.ui.GitStatusWidget.runUpdate(GitStatusWidget.java:146)
	at zielu.gittoolbox.ui.GitStatusWidget.selectionChanged(GitStatusWidget.java:114)
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:322)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:309)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:295)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:288)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
	at com.sun.proxy.$Proxy80.selectionChanged(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$17.run(FileEditorManagerImpl.java:1585)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$14$1.run(FileEditorManagerImpl.java:1016)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:672)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:656)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:626)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:108)
	at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by zielu** [comment]
Which java version are you using to run PHPStorm ? It looks like you are running under Java 6.
It should be visible in Help -> About dialog.

**Comment by glassdimly** [comment]
Looks like PhpStorm requires JDK 1.6 on Mac: https://intellij-support.jetbrains.com/hc/en-us/articles/206827547-Selecting-the-JDK-version-the-IDE-will-run-under

Here's a screenshot of my about version: http://glui.me/?i=71rsx1evoyc3dez/2015-07-23_at_1.36_PM.png/
