### ISSUE TITLE
bug with webstorm 2018.1.1

### ISSUE THREAD

**Issue by janbomber** [zielu/GitToolBox#83]
Hi
just after webstorm update, i get the following error

gitToolBox Version : 181.0.2

Error message:
Unable to serialize GitToolBoxProjectSettings state: org/apache/commons/lang3/builder/EqualsBuilder

Details
`
Unable to serialize GitToolBoxProjectSettings state: org/apache/commons/lang3/builder/EqualsBuilder
java.lang.NoClassDefFoundError: org/apache/commons/lang3/builder/EqualsBuilder
	at zielu.gittoolbox.config.CommitCompletionConfig.equals(CommitCompletionConfig.java:73)
	at java.util.AbstractList.equals(AbstractList.java:523)
	at com.intellij.openapi.util.Comparing.equal(Comparing.java:43)
	at com.intellij.util.xmlb.SkipDefaultsSerializationFilter.equal(SkipDefaultsSerializationFilter.java:52)
	at com.intellij.util.xmlb.SkipDefaultsSerializationFilter.equal(SkipDefaultsSerializationFilter.java:20)
	at com.intellij.util.xmlb.BeanBinding.serializeInto(BeanBinding.java:83)
	at com.intellij.util.xmlb.BeanBinding.serialize(BeanBinding.java:68)
	at com.intellij.configurationStore.XmlSerializer.serialize(xmlSerializer.kt:51)
	at com.intellij.configurationStore.XmlSerializer.serialize$default(xmlSerializer.kt:45)
	at com.intellij.configurationStore.SaveSessionBaseKt.serializeState(SaveSessionBase.kt:57)
	at com.intellij.configurationStore.SaveSessionBase.setState(SaveSessionBase.kt:29)
	at com.intellij.configurationStore.StateStorageManagerImpl$startExternalization$1.setState(StateStorageManagerImpl.kt:439)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:269)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:215)
	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:154)
	at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:40)
	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:331)
	at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.java:315)
	at com.intellij.openapi.components.impl.stores.StoreUtil.saveProject(StoreUtil.java:128)
	at com.intellij.openapi.components.impl.stores.StoreUtil.saveDocumentsAndProjectsAndApp(StoreUtil.java:119)
	at com.intellij.openapi.application.impl.ApplicationImpl.saveAll(ApplicationImpl.java:1429)
	at com.intellij.openapi.application.impl.ApplicationImpl.saveAll(ApplicationImpl.java:1423)
	at com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:126)
	at com.intellij.ide.SaveAndSyncHandlerImpl$2.a(SaveAndSyncHandlerImpl.java:94)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.ide.SaveAndSyncHandlerImpl$2.onFrameDeactivated(SaveAndSyncHandlerImpl.java:92)
	at com.intellij.ide.FrameStateManagerImpl.a(FrameStateManagerImpl.java:84)
	at com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:32)
	at com.intellij.ide.FrameStateManagerImpl$2.a(FrameStateManagerImpl.java:70)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:231)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:405)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:330)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:371)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:447)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:431)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:415)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.p(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:720)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

**Comment by zielu** [comment]
Fixed in 181.0.3
