### ISSUE TITLE
Error while calling if active ...

### ISSUE THREAD

**Issue by dodalovic** [zielu/GitToolBox#99]
```
Error while calling if active

java.lang.Throwable: Control-flow exceptions (like ProcessCanceledException) should never be logged
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:102)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:149)
	at zielu.gittoolbox.fetch.AutoFetch.callIfActive(AutoFetch.java:272)
	at zielu.gittoolbox.fetch.AutoFetchTask.tryExecuteFetch(AutoFetchTask.java:137)
	at zielu.gittoolbox.fetch.AutoFetchTask.doFetch(AutoFetchTask.java:123)
	at zielu.gittoolbox.fetch.AutoFetchTask.tryToFetch(AutoFetchTask.java:110)
	at zielu.gittoolbox.fetch.AutoFetchTask.access$200(AutoFetchTask.java:33)
	at zielu.gittoolbox.fetch.AutoFetchTask$1.lambda$run$0(AutoFetchTask.java:168)
	at zielu.gittoolbox.fetch.AutoFetch.runIfActive(AutoFetch.java:263)
	at zielu.gittoolbox.fetch.AutoFetchTask$1.run(AutoFetchTask.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:736)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:310)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.openapi.progress.ProcessCanceledException
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.throwIfCanceled(AbstractProgressIndicatorBase.java:144)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorBase.checkCanceled(AbstractProgressIndicatorBase.java:135)
	at com.intellij.openapi.progress.util.ProgressWindow$MyDelegate.checkCanceled(ProgressWindow.java:371)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.delegate(AbstractProgressIndicatorExBase.java:184)
	at com.intellij.openapi.progress.util.AbstractProgressIndicatorExBase.checkCanceled(AbstractProgressIndicatorExBase.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.doCheckCanceled(CoreProgressManager.java:120)
	at com.intellij.openapi.progress.ProgressManager.checkCanceled(ProgressManager.java:208)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.readLock(ReadMostlyRWLock.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl.startRead(ApplicationImpl.java:957)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:947)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:57)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.syncPublisher(BackgroundTaskUtil.java:294)
	at git4idea.update.GitFetcher.fetchNatively(GitFetcher.java:193)
	at git4idea.update.GitFetcher.fetchAll(GitFetcher.java:170)
	at git4idea.update.GitFetcher.fetch(GitFetcher.java:84)
	at zielu.gittoolbox.fetch.GtFetcher.doFetchRoots(GtFetcher.java:85)
	at zielu.gittoolbox.fetch.GtFetcher.lambda$fetchRoots$0(GtFetcher.java:69)
	at com.codahale.metrics.Timer.timeSupplier(Timer.java:133)
	at zielu.gittoolbox.fetch.GtFetcher.fetchRoots(GtFetcher.java:69)
	at zielu.gittoolbox.fetch.AutoFetchTask.executeFetch(AutoFetchTask.java:149)
	at zielu.gittoolbox.fetch.AutoFetchTask.lambda$tryExecuteFetch$1(AutoFetchTask.java:139)
	at zielu.gittoolbox.util.DisposeSafeCallable.call(DisposeSafeCallable.java:28)
	at zielu.gittoolbox.fetch.AutoFetch.callIfActive(AutoFetch.java:270)
	... 20 more
```

Latest Intellij ultimate @ latest MacOS

**Comment by zielu** [comment]
Fixed in 182.3.0
